import { useEffect, useRef, useState } from 'react';
import { Text, View } from 'react-native';
import { router } from 'expo-router';
import { randomUUID } from 'expo-crypto';
import { ToolPage, ToolField, ToolButton } from '@/src/components/toolkit';
import { ChoiceField } from '@/src/components/choice-field';
import { useAuth } from '@/src/auth/auth-context';
import { useAppearance } from '@/src/lib/appearance';
import { api } from '@/src/lib/api';
import { readCache, writeCache } from '@/src/lib/device-cache';
type Draft={kind:string;body:string;options:string[];hours:string;requestId:string;closesAt?:string};
export default function PublishingCreate(){const {user}=useAuth();return <AccountPublisher key={user?.id}/>;}
function AccountPublisher(){
 const {user}=useAuth(),{theme}=useAppearance();
 const [formats,setFormats]=useState<string[]>([]),[kind,setKind]=useState('POLL'),[body,setBody]=useState(''),[options,setOptions]=useState(['','']),[hours,setHours]=useState('24'),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const request=useRef(randomUUID()),closing=useRef<string|undefined>(undefined),locked=useRef(false),alive=useRef(true),draftKey=`publisher-draft.${user?.id}`;
 useEffect(()=>{alive.current=true;void Promise.all([api<{formats:string[]}>('/v1/student/publishing/capabilities'),readCache<Draft>(draftKey)]).then(([r,d])=>{if(!alive.current)return;setFormats(r.formats);if(d){setKind(d.kind);setBody(d.body);setOptions(d.options);setHours(d.hours);request.current=d.requestId;closing.current=d.closesAt;}else if(!r.formats.includes('POLL'))setKind(r.formats[0]??'POLL');setReady(true);}).catch(e=>{if(alive.current)setError(e.message);});return()=>{alive.current=false;};},[draftKey]);
 useEffect(()=>{if(!ready||busy)return;const timer=setTimeout(()=>void writeCache(draftKey,{kind,body,options,hours,requestId:request.current,closesAt:closing.current}),250);return()=>clearTimeout(timer);},[kind,body,options,hours,ready,busy,draftKey]);
 function changed(){request.current=randomUUID();closing.current=undefined;setError('');}
 const choices=formats.flatMap(value=>value==='POLL'?[{value:'POLL',label:'Poll · visible voters'},{value:'ANONYMOUS_POLL',label:'Anonymous poll'}]:[{value,label:value==='QA'?'Q&A':'Anonymous Q&A'}]);
 const poll=kind==='POLL'||kind==='ANONYMOUS_POLL',format=poll?'POLL':kind,allowed=formats.includes(format);
 async function publish(){if(locked.current||!allowed)return;locked.current=true;setBusy(true);setError('');try{closing.current??=new Date(Date.now()+Number(hours)*3600000).toISOString();const result=await api<{id:string}>('/v1/student/publishing/posts',{method:'POST',body:JSON.stringify({requestId:request.current,format,anonymousPoll:kind==='ANONYMOUS_POLL',body,...poll?{options}:{},closesAt:closing.current})});await writeCache(draftKey,null);if(alive.current)router.replace({pathname:'/publishing-post',params:{id:result.id}});}catch(e){if(alive.current)setError(e instanceof Error?e.message:'Your draft is saved. Try again.');}finally{locked.current=false;if(alive.current)setBusy(false);}}
 return <ToolPage title="Create campus post"><View style={{gap:16,paddingVertical:16}}>{error?<Text accessibilityRole="alert" style={{color:theme.error}}>{error}</Text>:null}{!ready?<Text style={{color:theme.textMuted}}>Loading your publishing access…</Text>:!formats.length?<Text style={{color:theme.text}}>Polls and Q&A require publishing access. Contact your campus administrator.</Text>:<><ChoiceField label="Post format" value={kind} options={choices} disabled={busy} onChange={value=>{changed();setKind(value);}}/><ToolField label={poll?'Poll question':'Question or invitation'} value={body} multiline maxLength={5000} editable={!busy} onChangeText={value=>{changed();setBody(value);}}/>{poll?<>{options.map((value,index)=><View key={index} style={{gap:6}}><ToolField label={`Option ${index+1}`} value={value} maxLength={100} editable={!busy} onChangeText={next=>{changed();setOptions(current=>current.map((old,i)=>i===index?next:old));}}/>{options.length>2?<ToolButton secondary label={`Remove option ${index+1}`} disabled={busy} onPress={()=>{changed();setOptions(current=>current.filter((_,i)=>i!==index));}}/>:null}</View>)}{options.length<6?<ToolButton secondary label="Add option" disabled={busy} onPress={()=>{changed();setOptions(current=>[...current,'']);}}/>:null}</>:null}<ChoiceField label="Accept responses for" value={hours} options={[{value:'24',label:'24 hours'},{value:'72',label:'3 days'},{value:'168',label:'7 days'},{value:'720',label:'30 days'}]} disabled={busy} onChange={value=>{changed();setHours(value);}}/><Text style={{color:theme.textMuted,lineHeight:22}}>{kind==='ANONYMOUS_POLL'?'Only vote totals will be visible. Voter identities stay private.':kind==='POLL'?'Students can see each voter’s name and chosen option before and after voting.':kind==='ANONYMOUS_QA'?'Answers start in your private inbox with the sender’s name hidden. Only you can publish an answer with your reply.':'Answers start in your private inbox. Only you can publish an answer with your reply.'}</Text><ToolButton label={busy?'Publishing…':'Publish'} disabled={busy||!allowed||!body.trim()||poll&&(options.some(value=>!value.trim())||new Set(options.map(value=>value.trim().toLowerCase())).size!==options.length)} onPress={()=>void publish()}/></>}</View></ToolPage>;
}
