"use client";
import{useEffect,useState,type FormEvent}from'react';import{portalApi}from'@/lib/api';import{useAdminContext}from'./admin-context';import{PortalShell}from'./portal-shell';
type Row={id:string;name:string;faculty_id?:string;department_id?:string;code?:string;award?:string;normal_duration_years?:number;primary_source_url?:string};type Data={faculties:Row[];departments:Row[];programmes:Row[]};
export function AcademicStructure(){const{scope,scopedPath,can}=useAdminContext();return <Editor key={scope} scope={scope} path={scopedPath('/v1/admin/academic/catalogue')} editable={can('academic.manage')}/>;}
function Editor({scope,path,editable}:{scope:string;path:string;editable:boolean}){const[data,setData]=useState<Data>(),[kind,setKind]=useState<'faculty'|'department'|'programme'>('faculty'),[editing,setEditing]=useState<Row|null>(null),[key,setKey]=useState(''),[search,setSearch]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[version,setVersion]=useState(0);
useEffect(()=>{let active=true;void portalApi<Data>(path).then(r=>{if(active)setData(r);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[path,version]);
const rows=data?.[kind==='faculty'?'faculties':kind==='department'?'departments':'programmes']??[];
async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!scope||busy)return;const form=e.currentTarget,v=new FormData(form),text=(n:string)=>String(v.get(n)??'').trim();const requestId=editing?.id||key||crypto.randomUUID();setKey(requestId);setBusy(true);setError('');try{await portalApi('/v1/admin/academic/catalogue',{method:'POST',body:JSON.stringify({id:requestId,universityId:scope,kind,parentId:text('parent')||undefined,name:text('name'),code:text('code'),award:text('award'),durationYears:text('duration')?Number(text('duration')):null,sourceUrl:text('source'),sourceVerified:v.has('verified'),reason:text('reason')})});setEditing(null);setKey('');form.reset();setVersion(n=>n+1);}catch(e){setError(e instanceof Error?e.message:'Could not save this academic record.');}finally{setBusy(false);}}
return <PortalShell active="admin" eyebrow="Reviewed academic data" title="Faculties, departments & programmes" description="Maintain the actual organisation, degree awards and durations of each university.">{error&&<p role="alert">{error}</p>}<div className="workspace-toolbar">{(['faculty','department','programme'] as const).map(k=><button key={k} className={`button button--${kind===k?'primary':'secondary'}`} onClick={()=>{setKind(k);setEditing(null);setKey('');}}>{k==='faculty'?'Faculties':k==='department'?'Departments':'Programmes'}</button>)}<input aria-label="Search academic records" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search names"/></div><div className="table-scroll"><table className="operational-table"><thead><tr><th>Name</th><th>Award / duration</th><th/></tr></thead><tbody>{rows.filter(r=>r.name.toLowerCase().includes(search.toLowerCase())).map(r=><tr key={r.id}><td>{r.name}</td><td>{r.award||'—'}{r.normal_duration_years?` · ${r.normal_duration_years} years`:''}</td><td>{editable&&scope&&<button onClick={()=>setEditing(r)}>Edit</button>}</td></tr>)}</tbody></table></div>{editable&&scope?<form className="form-stack panel" onSubmit={save} key={kind+(editing?.id??'new')}><h2>{editing?'Edit':'Add'} {kind}</h2><label>Name<input required name="name" defaultValue={editing?.name} minLength={2} maxLength={160}/></label>{kind!=='faculty'&&<label>{kind==='department'?'Faculty':'Department'}<select required name="parent" defaultValue={editing?.faculty_id??editing?.department_id??''}><option value="">Choose</option>{data?.[kind==='department'?'faculties':'departments'].map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label>}{kind==='programme'&&<><label>Programme code<input name="code" defaultValue={editing?.code} maxLength={24}/></label><label>Degree award<input name="award" placeholder="B.Eng" defaultValue={editing?.award} maxLength={30}/></label><label>Normal duration (years)<input type="number" name="duration" min={1} max={10} step={0.5} defaultValue={editing?.normal_duration_years}/></label></>}<label>Primary source<input required name="source" type="url" defaultValue={editing?.primary_source_url} placeholder="https://…"/></label><label>Reason<textarea required name="reason" minLength={10} maxLength={1000}/></label><label><input required type="checkbox" name="verified"/>I checked this against the university’s source.</label><button className="button button--primary" disabled={busy}>{busy?'Saving…':'Save reviewed record'}</button>{editing&&<button type="button" onClick={()=>setEditing(null)}>Cancel</button>}</form>:<p>Choose a university above to edit its academic structure.</p>}</PortalShell>;}
