"use client";
import { useEffect, useState } from "react";
import { portalApi } from "@/lib/api";
import { downloadCsv } from "@/lib/csv";
import { useAdminContext } from "./admin-context";
import { HorizontalBars } from "./analytics-visuals";
import { FinanceMetrics, type FinanceSummary } from "./finance-reporting";
import styles from "./admin-reporting.module.css";

const today=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Africa/Lagos",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
type Report={day:string;timeZone:string;generatedAt:string;provisional:boolean;counts:Record<string,number|null>;activity:{event_name:string;count:number;users:number}[];changes:{event_name:string;count:number}[];campaigns:{status:string;count:number}[]|null;finance:FinanceSummary|null;coverage:{definition:string;recordChangesStartedAt:string|null;signinsStartedAt:string|null}};
type Response={ready:false;message:string}|{ready:true;report:Report;availableDays:string[]};
const names:Record<string,string>={signups:"New accounts",signed_in_users:"Accounts signed in",resumed_users:"Sessions resumed",active_users:"Active accounts",recorded_activities:"Recorded activities",posts_created:"Posts created",posts_published:"Posts published",products_created:"Products added",product_updates:"Product updates",sales_recorded:"Sales recorded",coupons_created:"Coupons created",agents_approved:"Agents approved",messages_sent:"Messages sent",foreground_seconds:"App foreground time"};
const duration=(seconds:number)=>`${Math.floor(seconds/3600)}h ${Math.floor(seconds%3600/60)}m`;
export function DailyAppReport({refresh=0}:{refresh?:number}) {
 const{can,scopedPath}=useAdminContext();const[day,setDay]=useState(today),[retry,setRetry]=useState(0),[loaded,setLoaded]=useState<{key:string;data?:Response;error?:string}>();
 const path=scopedPath(`/v1/admin/reports/daily?date=${day}${retry ? "&refresh=true" : ""}`),key=`${path}:${retry}:${refresh}`;
 useEffect(()=>{if(!can("analytics.view"))return;const c=new AbortController();void portalApi<Response>(path,{signal:c.signal}).then(data=>{if(!c.signal.aborted)setLoaded({key,data});}).catch(e=>{if(!c.signal.aborted)setLoaded({key,error:e instanceof Error?e.message:"The daily report could not load."});});return()=>c.abort();},[path,key,can]);
 if(!can("analytics.view"))return null;const value=loaded?.key===key?loaded:undefined,data=value?.data,report=data?.ready?data.report:null;
 function exportReport(){if(!report)return;const rows=Object.entries(report.counts).map(([metric,value])=>({day:report.day,metric:names[metric]??metric,value:value??"Unavailable"}));downloadCsv(`kampusone-daily-${report.day}.csv`,["day","metric","value"],rows);}
 return <section className={`panel ${styles.section}`}><div className={styles.header}><div><p className="section-kicker">Daily app record · West Africa Time</p><h2>What happened on KampusOne</h2><p>Choose a day to revisit its saved report.</p></div><div className={styles.controls}><label>Report date<input type="date" value={day} min="2020-01-01" max={today()} onChange={e=>{if(e.target.value)setDay(e.target.value);}}/></label>{data?.ready&&data.availableDays.length>1&&<label>Saved reports<select value={day} onChange={e=>setDay(e.target.value)}>{data.availableDays.map(date=><option key={date}>{date}</option>)}</select></label>}<button className="button button--secondary" onClick={()=>setRetry(n=>n+1)}>Refresh</button><button className="button button--secondary" disabled={!report} onClick={exportReport}>Export day</button></div></div>
 {!value?<div className="table-skeleton" aria-busy="true" aria-label="Loading daily report"><div/><div/><div/></div>:value.error?<section className="state-panel state-panel--error" role="alert"><p>{value.error}</p><button className="button button--secondary" onClick={()=>setRetry(n=>n+1)}>Try again</button></section>:data?.ready===false?<p className="state-panel">{data.message}</p>:report?<><div className={styles.grid}>{Object.entries(report.counts).map(([metric,count])=><article className={styles.metric} key={metric}><span>{names[metric]??metric}</span><strong>{count===null?"Unavailable":metric==="foreground_seconds"?duration(count):count.toLocaleString()}</strong></article>)}</div><div className={styles.charts}><HorizontalBars title="Activity recorded this day" rows={report.activity.map(r=>({label:r.event_name.replaceAll("_"," "),value:r.count}))}/><HorizontalBars title="Publishing and operations" rows={report.changes.map(r=>({label:r.event_name.replaceAll("_"," "),value:r.count}))}/></div>{report.campaigns&&report.campaigns.length>0&&<HorizontalBars title="Campaign recipient states" rows={report.campaigns.map(r=>({label:r.status.replaceAll("_"," "),value:r.count}))}/>}<details><summary>Measurement and collection details</summary><p className={styles.coverage}>{report.coverage.definition}<br/>Record changes collected from {report.coverage.recordChangesStartedAt?new Date(report.coverage.recordChangesStartedAt).toLocaleString("en-NG",{timeZone:"Africa/Lagos"}):"this release"}. Sign-in events first recorded {report.coverage.signinsStartedAt?new Date(report.coverage.signinsStartedAt).toLocaleString("en-NG",{timeZone:"Africa/Lagos"}):"after the first successful sign-in on this release"}.</p></details>{report.finance&&<details><summary>Revenue and expenses for this day</summary><FinanceMetrics summary={report.finance}/></details>}<p className="field-help">{report.provisional?"Recent report. Late offline measurements can update it for 48 hours. ":"Saved historical report. "}Captured {new Date(report.generatedAt).toLocaleString("en-NG",{timeZone:"Africa/Lagos"})} WAT.</p></>:null}
 </section>;
}
