"use client";
import {useCallback,useEffect,useState,type FormEvent} from 'react';
import {portalApi} from '@/lib/api';
import {useAdminContext} from './admin-context';
type Code={id:string;code:string;scope:string;percent:number;ends_at:string;max_uses:number;per_user_limit:number;active:boolean;uses:number;budget_kobo:number};
export function DiscountCodes(){
 const {scope,access,can,scopedPath}=useAdminContext(),[codes,setCodes]=useState<Code[]>([]),[version,setVersion]=useState(0),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let live=true;void portalApi<{codes:Code[]}>(scopedPath('/v1/discounts/admin')).then(r=>{if(live)setCodes(r.codes);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[scopedPath,version]);
 const refresh=useCallback(()=>setVersion(v=>v+1),[]);
 async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');setNotice('');const form=event.currentTarget,d=new FormData(form);try{await portalApi('/v1/discounts/admin',{method:'POST',body:JSON.stringify({universityId:d.get('universityId'),code:d.get('code'),scope:d.get('scope'),percent:Number(d.get('percent')),endsAt:new Date(String(d.get('endsAt'))).toISOString(),maxUses:Number(d.get('maxUses')),perUserLimit:Number(d.get('perUserLimit')),budgetKobo:Math.round(Number(d.get('budget'))*100)})});form.reset();setNotice('Code created. Supplier earnings are preserved; the platform funds the discount.');refresh();}catch(e){setError(e instanceof Error?e.message:'The code could not be saved.');}finally{setBusy(false);}}
 async function toggle(code:Code){setBusy(true);setError('');try{await portalApi('/v1/discounts/admin/'+code.id,{method:'PUT',body:JSON.stringify({active:!code.active})});refresh();}catch(e){setError(e instanceof Error?e.message:'The code could not be changed.');}finally{setBusy(false);}}
 return <section className="panel"><p className="eyebrow">Discounts</p><h2>Scoped percentage codes</h2><p className="field-help">Codes apply only to their university and purchase category. Supplier earnings stay intact. The campaign budget caps the platform’s total discount spend, including open reservations.</p>{error?<p className="form-error" role="alert">{error}</p>:null}{notice?<p className="form-success" role="status">{notice}</p>:null}{can('finance.review')?<form className="form-grid manage-form" onSubmit={create}><label>University<select name="universityId" defaultValue={scope} required><option value="" disabled>Select university</option>{access?.universities?.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label><label>Code<input name="code" required pattern="[A-Za-z0-9_-]{3,32}" maxLength={32} placeholder="CAMPUS10"/></label><label>Purchase category<select name="scope"><option value="KIRA">Kira Pro</option><option value="STORE">Vendor orders</option><option value="RIDER">Rider delivery · in-app fare</option><option value="TUTORIAL">Tutor bookings</option><option value="MATERIAL">Learning materials</option></select></label><label>Discount %<input name="percent" type="number" min="1" max="90" defaultValue="10" required/></label><label>Campaign budget · ₦<input name="budget" type="number" min="1" max="20000000" step="0.01" required/></label><label>Expires<input name="endsAt" type="datetime-local" required/></label><label>Maximum uses<input name="maxUses" type="number" min="1" max="100000" defaultValue="20" required/></label><label>Uses per account<input name="perUserLimit" type="number" min="1" max="20" defaultValue="1" required/></label><label className="consent-row"><input type="checkbox" required/>Approve the platform-funded discount and its spending cap.</label><button className="button button--primary" disabled={busy}>Create code</button></form>:null}<div className="table-scroll"><table className="operational-table"><thead><tr><th>Code</th><th>Category</th><th>Discount</th><th>Uses</th><th>Expiry</th><th>State</th><th/></tr></thead><tbody>{codes.map(code=><tr key={code.id}><td>{code.code}</td><td>{code.scope}</td><td>{code.percent}%</td><td>{code.uses}/{code.max_uses}</td><td>{new Date(code.ends_at).toLocaleString()}</td><td>{code.active?'Enabled':'Disabled'}</td><td>{can('finance.review')?<button disabled={busy} onClick={()=>void toggle(code)}>{code.active?'Disable':'Enable'}</button>:null}</td></tr>)}</tbody></table></div></section>;
}
