"use client";
import { useEffect, useState, type FormEvent } from "react";
import { portalApi } from "@/lib/api";
import { useAdminContext } from "./admin-context";
import { PortalShell } from "./portal-shell";
import { HorizontalBars } from "./analytics-visuals";
import styles from "./admin-reporting.module.css";

export type FinanceSummary={platform_revenue_kobo:number;expenses_kobo:number;commission_kobo:number;vendor_proceeds_kobo:number;marketplace_revenue_kobo:number;gmv_kobo:number;transactions_processed:number;transactions_definition?:string;profit_kobo:number;arr_kobo:number|null;arr_definition:string;definition:string;breakdown:{account_code:string;account_type:string;amount_kobo:number}[]};
type Expense={id:string;institution_id:string;category:string;description:string;amount_kobo:string;incurred_on:string};
type Data={ready:false;message:string}|{ready:true;summary:FinanceSummary;expenses:Expense[];generatedAt:string};
const money=(kobo:number)=>new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN",minimumFractionDigits:0,maximumFractionDigits:2}).format(kobo/100);
const today=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Africa/Lagos",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
export function FinanceMetrics({summary}:{summary:FinanceSummary}){
 const rows:[string,string,string][]=[["Store GMV",money(summary.gmv_kobo),"Journal-backed product sales and delivery"],["Transactions processed",summary.transactions_processed.toLocaleString(),summary.transactions_definition??"Recorded transactions"],["Platform revenue",money(summary.platform_revenue_kobo),"Recognized journal revenue"],["Marketplace revenue",money(summary.marketplace_revenue_kobo),"Platform revenue outside Kira access"],["Total commission",money(summary.commission_kobo),"Commission account, after reversals"],["Vendor proceeds",money(summary.vendor_proceeds_kobo),"Allocated seller earnings"],["Recorded expenses",money(summary.expenses_kobo),"Processing, promotions and incurred costs"],[summary.profit_kobo<0?"Recorded loss":"Recorded profit",money(summary.profit_kobo),"Revenue less recorded expenses"],["ARR",summary.arr_kobo===null?"Not applicable":money(summary.arr_kobo),"Monthly prepaid access does not auto renew"]];
 return <div className={styles.section}><div className={`${styles.grid} ${styles.financeGrid}`}>{rows.map(([label,value,caption])=><article className={styles.metric} key={label}><span>{label}</span><strong>{value}</strong><small>{caption}</small></article>)}</div><p className={styles.coverage}>{summary.definition} {summary.arr_definition}</p><div className={styles.charts}><HorizontalBars title="Revenue accounts" rows={summary.breakdown.filter(r=>r.account_type==="REVENUE").map(r=>({label:r.account_code.replaceAll("_"," "),value:r.amount_kobo}))} valueLabel={money}/><HorizontalBars title="Expense accounts" rows={summary.breakdown.filter(r=>r.account_type==="EXPENSE").map(r=>({label:r.account_code.replaceAll("_"," "),value:r.amount_kobo}))} valueLabel={money}/></div></div>;
}
export function FinancialReporting({compact=false,refresh=0}:{compact?:boolean;refresh?:number}){
 const{can,scopedPath}=useAdminContext(),[version,setVersion]=useState(0),[saved,setSaved]=useState(false),[loaded,setLoaded]=useState<{key:string;data?:Data;error?:string}>();const path=scopedPath("/v1/admin/finance/reporting"),key=`${path}:${refresh}:${version}`;
 useEffect(()=>{if(!can("finance.view"))return;const c=new AbortController();void portalApi<Data>(path,{signal:c.signal}).then(data=>{if(!c.signal.aborted)setLoaded({key,data});}).catch(e=>{if(!c.signal.aborted)setLoaded({key,error:e instanceof Error?e.message:"Finance report unavailable."});});return()=>c.abort();},[path,key,can]);
 if(!can("finance.view"))return null;const value=loaded?.key===key?loaded:undefined,data=value?.data;
 return <section className={`panel ${styles.section}`}><div className={styles.header}><div><p className="section-kicker">Recorded finance · lifetime</p><h2>Revenue, earnings and expenses</h2></div><button className="button button--secondary" onClick={()=>setVersion(n=>n+1)}>Refresh finance</button></div>{saved&&<p role="status" className="workspace-notice">Expense recorded. It records an incurred cost and payable; no bank payment was initiated.</p>}{!value?<div className="table-skeleton" aria-busy="true" aria-label="Loading financial report"><div/><div/></div>:value.error?<p className="state-panel state-panel--error" role="alert">{value.error}</p>:data?.ready===false?<p className="state-panel">{data.message}</p>:data?.ready?<><FinanceMetrics summary={data.summary}/>{!compact&&<><ExpenseEntry onSaved={()=>{setSaved(true);setVersion(n=>n+1);}}/><div className="table-scroll"><table className="operational-table"><caption>Recorded operating expenses · latest 200 entries</caption><thead><tr><th>Incurred</th><th>Category</th><th>Description</th><th>Amount</th></tr></thead><tbody>{data.expenses.map(e=><tr key={e.id}><td>{e.incurred_on}</td><td>{e.category}</td><td>{e.description}</td><td>{money(Number(e.amount_kobo))}</td></tr>)}</tbody></table>{!data.expenses.length&&<p className="table-empty">No operating expenses recorded yet.</p>}</div><ExpenseCalculator/></>}</>:null}</section>;
}
function ExpenseEntry({onSaved}:{onSaved:()=>void}){
 const{scope,access,can}=useAdminContext(),[requestId,setRequestId]=useState(()=>crypto.randomUUID()),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const form=e.currentTarget,d=new FormData(form),amount=Number(d.get("amount"));if(!Number.isFinite(amount)||amount<=0){setNotice("Enter a positive expense amount.");return;}setBusy(true);setNotice("");try{await portalApi("/v1/admin/finance/reporting/expenses",{method:"POST",body:JSON.stringify({requestId,universityId:d.get("universityId"),category:d.get("category"),description:d.get("description"),amountKobo:Math.round(amount*100),incurredOn:d.get("incurredOn")})});form.reset();setRequestId(crypto.randomUUID());setNotice("Expense recorded in a balanced journal. It records a payable; it does not initiate a bank payment.");onSaved();}catch(e){setNotice(e instanceof Error?e.message:"Expense could not be recorded. Retry keeps the same request to prevent duplicates.");}finally{setBusy(false);}}
 if(!can("finance.review"))return null;
 return <section><h3>Record an operating expense</h3><p className="field-help">Records are retained in the ledger. Enter an incurred business cost once.</p><form className={styles.form} onSubmit={save}><fieldset disabled={busy} className={styles.full}><div className={styles.form}><label>University<select name="universityId" defaultValue={scope} required><option value="">Choose university</option>{access?.universities?.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label><label>Category<select name="category">{["Hosting","Marketing","Transport","Equipment","Staff","Other"].map(c=><option key={c}>{c}</option>)}</select></label><label>Amount · ₦<input name="amount" type="number" min="0.01" max="2000000000" step="0.01" required/></label><label>Incurred date<input name="incurredOn" type="date" min="2020-01-01" max={today()} defaultValue={today()} required/></label><label className={styles.full}>Description<textarea name="description" minLength={3} maxLength={1000} required placeholder="What this expense covered"/></label><button className="button button--primary">{busy?"Recording…":"Record expense"}</button></div></fieldset></form>{notice&&<p role="status" className="workspace-notice">{notice}</p>}</section>;
}
function ExpenseCalculator(){const[revenue,setRevenue]=useState(""),[expenses,setExpenses]=useState("");const result=Math.round((Number(revenue||0)-Number(expenses||0))*100);return <section className={styles.calculator}><div><h3>Quick profit calculator</h3><p className="field-help">Try a scenario. These figures are not written to the ledger.</p></div><div className={styles.form}><label>Revenue · ₦<input type="number" min="0" step="0.01" value={revenue} onChange={e=>setRevenue(e.target.value)}/></label><label>Expenses · ₦<input type="number" min="0" step="0.01" value={expenses} onChange={e=>setExpenses(e.target.value)}/></label></div><output aria-live="polite">{result<0?"Loss":"Profit"}: {money(Number.isFinite(result)?result:0)}</output></section>;}
export function FinancialReportingPage(){const{scopeLabel}=useAdminContext();return <PortalShell active="admin" eyebrow={scopeLabel} title="Revenue and expenses" description="Posted revenue, allocated earnings and a journal of incurred operating costs."><FinancialReporting/></PortalShell>;}
