"use client";
import {useCallback,useEffect,useState} from 'react';
import {MapCaptureReview} from './map-capture-review';
import {MapGeometryPreview} from './map-geometry-preview';
import {portalApi} from '@/lib/api';
type Candidate={id:string;name:string|null;feature_kind:string;source_feature_id:string;matched_place_id:string|null;geometry:{type:string;coordinates:unknown};tags:Record<string,unknown>};
type Review={imports:{id:string;status:string;diagnostics:{error?:string;fetched?:number;candidates?:number}}[];candidates:Candidate[];missions:{id:string;title:string;kind:string;status:string}[]};
export function MapStudio({campusId,places}:{campusId:string;places:{id:string;name:string}[]}){
 const [review,setReview]=useState<Review|null>(null),[selected,setSelected]=useState<Candidate|null>(null),[name,setName]=useState(''),[placeId,setPlaceId]=useState(''),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const load=useCallback(()=>portalApi<Review>(`/v1/maps/admin/campuses/${campusId}/review`).then(r=>{setReview(r);setError('');}).catch(e=>setError(e.message)),[campusId]);
 useEffect(()=>{let alive=true;void portalApi<Review>(`/v1/maps/admin/campuses/${campusId}/review`).then(r=>{if(alive)setReview(r);}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[campusId]);
 useEffect(()=>{if(!review?.imports.some(job=>job.status==='RUNNING'))return;const timer=setInterval(()=>void load(),3000);return()=>clearInterval(timer);},[review,load]);
 async function start(){setBusy(true);setError('');try{await portalApi('/v1/maps/admin/imports',{method:'POST',body:JSON.stringify({campusId,requestKey:crypto.randomUUID()})});await load();}catch(e){setError(e instanceof Error?e.message:'Discovery failed.');}finally{setBusy(false);}}
 async function decision(value:'APPROVE'|'MERGE'|'REJECT'){if(!selected)return;setBusy(true);setError('');try{await portalApi(`/v1/maps/admin/candidates/${selected.id}/decision`,{method:'POST',body:JSON.stringify({decision:value,...name?{name}:{},...placeId?{placeId}:{},note})});setSelected(null);await load();}catch(e){setError(e instanceof Error?e.message:'Decision could not save.');}finally{setBusy(false);}}
 return <><MapCaptureReview campusId={campusId} places={places}/><section className="panel map-studio"><div className="workspace-toolbar"><div><p className="eyebrow">Map Studio</p><h2>Discover, review and publish</h2><p className="field-help">Existing campus names and aliases stay intact. Discovery creates candidates; review controls publication.</p></div><button className="button button--primary" onClick={()=>void start()} disabled={busy||review?.imports.some(job=>job.status==='RUNNING')}>Discover OpenStreetMap features</button></div>{error?<p className="form-error" role="alert">{error}</p>:null}{review?.imports.slice(0,3).map(job=><p key={job.id} className="field-help">{job.status.toLowerCase()} · {job.diagnostics.error??`${job.diagnostics.fetched??0} features fetched · ${job.diagnostics.candidates??0} candidates`}</p>)}<div className="map-review-grid"><div className="table-scroll"><table className="operational-table"><thead><tr><th>Candidate</th><th>Type</th><th>Match</th><th/></tr></thead><tbody>{review?.candidates.map(candidate=><tr key={candidate.id}><td>{candidate.name??candidate.source_feature_id}</td><td>{candidate.feature_kind.toLowerCase()}</td><td>{places.find(p=>p.id===candidate.matched_place_id)?.name??'Unmatched'}</td><td><button onClick={()=>{setSelected(candidate);setName(candidate.name??'');setPlaceId(candidate.matched_place_id??'');setNote('');}}>Review</button></td></tr>)}</tbody></table>{review&&!review.candidates.length?<p>No pending candidates.</p>:null}</div>{selected?<div className="form-stack"><h3>Review {selected.feature_kind.toLowerCase()}</h3><MapGeometryPreview geometry={selected.geometry} label={selected.name??selected.source_feature_id}/><a href={`https://www.openstreetmap.org/${selected.source_feature_id}`} target="_blank" rel="noreferrer">Open original feature</a><p className="field-help">{Object.entries(selected.tags).filter(([key])=>key!=='node_ids').map(([key,value])=>`${key}: ${String(value)}`).join(' · ')}</p><label>Name<input value={name} onChange={e=>setName(e.target.value)} maxLength={180}/></label><label>Merge / entrance place<select value={placeId} onChange={e=>setPlaceId(e.target.value)}><option value="">New place / no match</option>{places.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Review note<textarea value={note} onChange={e=>setNote(e.target.value)} minLength={3} maxLength={1000}/></label><div className="form-actions"><button disabled={busy||note.trim().length<3} onClick={()=>void decision(placeId?'MERGE':'APPROVE')}>Approve {placeId?'and merge':''}</button><button disabled={busy||note.trim().length<3} onClick={()=>void decision('REJECT')}>Reject</button></div></div>:<p>Select a candidate to review its source, geometry and campus match.</p>}</div></section></>;
}
