"use client";
import {useEffect,useState} from 'react';
import {portalApi} from '@/lib/api';
import {useAdminContext} from './admin-context';
const labels={push_enabled:'Native push',alarms_enabled:'Class and custom alarm sync',newsletter_enabled:'Newsletter push',announcements_enabled:'Announcement push',campus_updates_enabled:'Campus update push',email_enabled:'Queued transactional email'};
type Policy=Record<keyof typeof labels,boolean>;
export function NotificationRuntimeControls(){const {scope,scopedPath,scopeLabel,can}=useAdminContext();const [policy,setPolicy]=useState<Policy|null>(null),[effective,setEffective]=useState<Policy|null>(null),[note,setNote]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);useEffect(()=>{let alive=true;void portalApi<{policy:Policy;effective:Policy}>(scopedPath('/v1/notifications/admin/runtime')).then(r=>{if(alive){setPolicy(r.policy);setEffective(r.effective);}}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[scope,scopedPath]);async function save(){if(!policy)return;setBusy(true);setError('');try{const r=await portalApi<{policy:Policy;effective:Policy}>(scopedPath('/v1/notifications/admin/runtime'),{method:'PUT',body:JSON.stringify({policy,note})});setPolicy(r.policy);setEffective(r.effective);setNote('');}catch(e){setError(e instanceof Error?e.message:'Controls failed to save.');}finally{setBusy(false);}}
 if(!can('notifications.manage'))return null;return <section className="panel"><h2>Delivery controls</h2><p className="scope-caption">{scopeLabel}</p>{error?<p role="alert" className="form-error">{error}</p>:null}{policy?<div className="form-stack"><div className="form-grid">{Object.entries(labels).map(([key,label])=><label key={key}><input type="checkbox" disabled={busy} checked={policy[key as keyof Policy]} onChange={e=>setPolicy({...policy,[key]:e.target.checked})}/>{label}{effective?.[key as keyof Policy]===false&&policy[key as keyof Policy]?<small>Paused by the global control</small>:null}</label>)}</div><label>Reason for this change<textarea value={note} onChange={e=>setNote(e.target.value)} minLength={3} maxLength={1000}/></label><p className="field-help">Paused deliveries remain queued. Alarm changes reach devices when the app next synchronizes. Account security and sign-in emails remain available.</p><button disabled={busy||note.trim().length<3} className="button button--primary" onClick={()=>void save()}>Save delivery controls</button></div>:<p>Loading controls…</p>}</section>;
}
