"use client";
import {useEffect,useState} from "react";
import {portalApi} from "@/lib/api";
import {useAdminContext} from "./admin-context";
import {DonutBreakdown,HorizontalBars} from "./analytics-visuals";
import styles from "./admin-reporting.module.css";
type Report={ready:true;totals:{day:string;foreground_seconds:number;users:number;samples:number};users:{user_id:string;display_name:string|null;username:string|null;foreground_seconds:number;platforms:string[]}[];screens:{screen:string;foreground_seconds:number}[];definition:string;timeZone:string}|{ready:false;message:string};
const duration=(seconds:number)=>`${Math.floor(seconds/3600)}h ${Math.floor(seconds%3600/60)}m ${seconds%60}s`;
const today=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Africa/Lagos",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
export function ScreenTimeReport(){const{scopedPath,can}=useAdminContext(),[day,setDay]=useState(today),[version,setVersion]=useState(0),[loaded,setLoaded]=useState<{key:string;data?:Report;error?:string}>();const path=scopedPath(`/v1/usage/admin/today?date=${day}`),key=`${path}:${version}`;useEffect(()=>{if(!can("analytics.view"))return;const c=new AbortController();void portalApi<Report>(path,{signal:c.signal}).then(data=>{if(!c.signal.aborted)setLoaded({key,data});}).catch(e=>{if(!c.signal.aborted)setLoaded({key,error:e instanceof Error?e.message:"Usage could not load."});});return()=>c.abort();},[path,key,can]);if(!can("analytics.view"))return null;const current=loaded?.key===key?loaded:undefined,report=current?.data;
return <section className={`panel ${styles.section}`}><div className={styles.header}><h2>Measured app usage</h2><div className={styles.controls}><label>Usage date<input type="date" value={day} min="2020-01-01" max={today()} onChange={e=>{if(e.target.value)setDay(e.target.value);}}/></label><button className="button button--secondary" onClick={()=>setVersion(n=>n+1)}>Refresh usage</button></div></div>{!current?<div className="table-skeleton" aria-busy="true" aria-label="Loading usage"><div/><div/></div>:current.error?<div className="state-panel state-panel--error" role="alert"><p>{current.error}</p><button className="button button--secondary" onClick={()=>setVersion(n=>n+1)}>Retry</button></div>:report?.ready===false?<p className="state-panel">{report.message}</p>:report?.ready?<><p>{report.totals.day} · West Africa Time · <strong>{duration(report.totals.foreground_seconds)}</strong> across {report.totals.users} accounts.</p><p className="field-help">{report.definition}</p>{!report.totals.samples?<p className="state-panel">No foreground samples were recorded for this day.</p>:<><div className={styles.charts}><HorizontalBars title="Foreground time by screen" rows={report.screens.map(s=>({label:s.screen,value:s.foreground_seconds}))} valueLabel={duration}/><DonutBreakdown title="Accounts by observed platform" rows={Object.entries(report.users.flatMap(u=>u.platforms).reduce<Record<string,number>>((counts,platform)=>{counts[platform]=(counts[platform]??0)+1;return counts;},{})).map(([label,value])=>({label,value}))}/></div><p className="field-help">An account can appear on more than one platform. The account table shows the latest 500 measured accounts.</p><div className="table-scroll"><table className="operational-table"><thead><tr><th>Account</th><th>Foreground time</th><th>Platforms</th></tr></thead><tbody>{report.users.map(u=><tr key={u.user_id}><td>{u.display_name??u.username??u.user_id}</td><td>{duration(u.foreground_seconds)}</td><td>{u.platforms.join(", ")}</td></tr>)}</tbody></table></div></>}</>:null}</section>;}
