"use client";
import{useEffect,useState,type FormEvent}from"react";
import{portalApi}from"@/lib/api";
import{useAdminContext}from"./admin-context";
type Sound={id:string;name:string;url:string;is_default:boolean};
export function SoundCatalogue(){const{scope,scopedPath,can}=useAdminContext(),[items,setItems]=useState<Sound[]>([]),[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState(""),[name,setName]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0);const allowed=can("notifications.manage");
useEffect(()=>{let active=true;if(allowed)void portalApi<{sounds:Sound[]}>(scopedPath('/v1/notifications/admin/sounds')).then(r=>{if(active)setItems(r.sounds);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[allowed,scopedPath,revision]);
useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview);},[preview]);
async function save(e:FormEvent){e.preventDefault();if(!file||busy)return;setBusy(true);setError("");try{const form=new FormData();form.append('kind','notification-sound');form.append('file',file);const media=await portalApi<{id:string}>('/v1/media',{method:'POST',body:form});await portalApi('/v1/notifications/admin/sounds',{method:'POST',body:JSON.stringify({name,mediaId:media.id,...(scope?{universityId:scope}:{})})});setFile(null);setName("");setRevision(v=>v+1);}catch(e){setError(e instanceof Error?e.message:'Could not save this sound.');}finally{setBusy(false);}}
async function choose(id:string){setBusy(true);try{await portalApi(`/v1/notifications/admin/sounds/${id}/default`,{method:'PUT'});setRevision(v=>v+1);}catch(e){setError(e instanceof Error?e.message:'Could not change the default.');}finally{setBusy(false);}}
if(!allowed)return null;return <section className="panel"><h2>Notification sounds</h2><p>Upload an MP3 or WAV under 2 MB. The chosen sound is used for browser reminders. Custom native sounds must be bundled into an Android/iOS release.</p>{error&&<p role="alert">{error}</p>}<form className="form-stack" onSubmit={save}><label>Sound name<input required maxLength={80} minLength={2} value={name} onChange={e=>setName(e.target.value)}/></label><label>Audio file<input type="file" accept="audio/mpeg,audio/wav,.mp3,.wav" disabled={busy} onChange={e=>{const chosen=e.target.files?.[0];if(chosen&&chosen.size>2*1024*1024){setError('Choose a file under 2 MB.');return;}setFile(chosen??null);setPreview(chosen?URL.createObjectURL(chosen):"");}}/></label>{file&&<><audio controls preload="metadata" src={preview} aria-label="Sound preview"/><button type="button" onClick={()=>setFile(null)}>Remove file</button></>}<button className="button button--primary" disabled={busy||!file}>{busy?'Saving…':'Add sound'}</button></form>{items.map(s=><div key={s.id} className="workspace-toolbar"><strong>{s.name}</strong><audio controls preload="none" src={s.url} aria-label={s.name}/><button disabled={busy||s.is_default} onClick={()=>void choose(s.id)}>{s.is_default?'Default':'Set default'}</button></div>)}</section>;}
