"use client";
import {useEffect,useState,type FormEvent} from 'react';
import {useSearchParams} from 'next/navigation';
import {usePortalAuth} from './auth-provider';
import {portalApi} from '@/lib/api';
import {PhoneField,BirthDateField} from './intake-fields';
import {AgentApplicationIllustration} from './agent-illustrations';
export function TrustedVendorApplication(){
 const params=useSearchParams(),{user}=usePortalAuth(),token=params.get('invite')??'';
 const [invite,setInvite]=useState<{university_name:string,application_id:string|null}|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[phone,setPhone]=useState(''),[birth,setBirth]=useState(''),[photo,setPhoto]=useState(''),[submitted,setSubmitted]=useState(false),[request,setRequest]=useState('');
 useEffect(()=>{let active=true;void portalApi<{invite:{university_name:string,application_id:string|null}}>('/v1/trusted-vendors/invite',{method:'POST',body:JSON.stringify({token})}).then(r=>{if(active){setInvite(r.invite);setSubmitted(Boolean(r.invite.application_id));setRequest(crypto.randomUUID());}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[token,user?.id]);
 async function upload(file:File){setBusy(true);setError('');try{const r=await portalApi<{id:string}>('/v1/media?kind=avatar&name='+encodeURIComponent(file.name),{method:'POST',headers:{'Content-Type':file.type},body:file});setPhoto(r.id);}catch(e){setError(e instanceof Error?e.message:'Photo could not upload.');}finally{setBusy(false);}}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const d=new FormData(e.currentTarget);try{await portalApi('/v1/trusted-vendors/submit',{method:'POST',body:JSON.stringify({token,requestId:request,businessName:d.get('businessName'),legalName:d.get('legalName'),birthDate:birth,description:d.get('description'),address:d.get('address'),category:d.get('category'),campus:d.get('campus'),phone,...(photo?{profileMediaId:photo}:{}),adultAuthorized:true,terms:true})});setSubmitted(true);}catch(e){setError(e instanceof Error?e.message:'Your application is kept. Try again.');}finally{setBusy(false);}}
 return <main className="agent-login-page"><section className="agent-login-shell agent-onboarding-form" style={{maxWidth:620}}><AgentApplicationIllustration step={2} complete={submitted}/><p className="eyebrow">By invitation</p><h1>{submitted?'Your business is under review':'Set up your vendor profile'}</h1><p>{invite?.university_name}</p><p className="field-help">Your inviting team has waived ordinary application documents. An administrator will verify your business and contact details before approval.</p>{error?<p role="alert" className="form-error">{error}</p>:null}{submitted?<><p>We’ll email the decision. Once approved, your agent dashboard includes your shop and bank setup.</p><a className="button button--primary" href="https://agents.kampusone.app/agents/dashboard">Open agent dashboard</a></>:invite?<form className="form-stack" onSubmit={submit}><label>Business name<input name="businessName" required minLength={2} maxLength={160} placeholder="e.g. Osas Kitchen"/></label><label>Your legal name<input name="legalName" required minLength={2} maxLength={160} placeholder="e.g. Osas Egharevba" autoComplete="name"/></label><BirthDateField value={birth} onChange={setBirth}/><PhoneField id="trusted-phone" label="Business contact" value={phone} onChange={setPhone}/><label>Business category<select name="category">{['Restaurant','Supermarket','Groceries','Fashion','Beauty','Electronics','Printing','Other'].map(c=><option key={c}>{c}</option>)}</select></label><label>Campus or service area<input name="campus" required maxLength={100} placeholder="e.g. Ugbowo campus"/></label><label>Business address<input name="address" required minLength={10} maxLength={500} placeholder="e.g. June 12 shopping complex"/></label><label>Business description<textarea name="description" required minLength={20} maxLength={2000} placeholder="What do you sell and when are you available?"/></label><label>Business profile photo · optional<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file);}}/>{photo?<span className="field-help">Photo saved.</span>:null}</label><label className="consent-row"><input type="checkbox" required/>I’m at least 18 and authorised to represent this business.</label><label className="consent-row"><input type="checkbox" required/>I accept the KampusOne agent terms and confirm these details are accurate.</label><button className="button button--primary button--wide" disabled={busy||!phone||!birth||!request}>{busy?'Saving…':'Submit vendor profile'}</button></form>:!error?<p>Checking your invitation…</p>:null}</section></main>;
}
