"use client";
import {useEffect,useState,type FormEvent} from 'react';
import {portalApi} from '@/lib/api';
import {useAdminContext} from './admin-context';
type Row={id:string,display_name:string,email:string,status:string,revision:string,legal_name:string,phone_e164:string,description:string,address:string,category:string,campus:string,review_note:string|null,invitation_reason:string,business_document_ids:string[]};
export function TrustedVendorAdmin(){const {scope,access,can,scopedPath}=useAdminContext(),[rows,setRows]=useState<Row[]>([]),[version,setVersion]=useState(0),[error,setError]=useState(''),[url,setUrl]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{if(!can('agents.review'))return;let active=true;void portalApi<{applications:Row[]}>(scopedPath('/v1/trusted-vendors/admin')).then(r=>{if(active)setRows(r.applications);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[scopedPath,version,can]);
 async function invite(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const d=new FormData(e.currentTarget);try{const r=await portalApi<{url:string}>('/v1/trusted-vendors/admin/invites',{method:'POST',body:JSON.stringify({universityId:d.get('universityId'),email:d.get('email'),reason:d.get('reason')})});setUrl(r.url);}catch(e){setError(e instanceof Error?e.message:'Invitation could not be prepared.');}finally{setBusy(false);}}
 async function review(e:FormEvent<HTMLFormElement>,r:Row){e.preventDefault();const d=new FormData(e.currentTarget);setBusy(true);setError('');try{await portalApi('/v1/trusted-vendors/admin/'+r.id+'/review',{method:'POST',body:JSON.stringify({revision:r.revision,decision:d.get('decision'),note:d.get('note'),verifiedBusinessAndContact:true,verifiedDocuments:true})});setVersion(v=>v+1);}catch(e){setError(e instanceof Error?e.message:'Review could not finish.');}finally{setBusy(false);}}
 async function openDocument(id:string){setBusy(true);setError('');try{const r=await portalApi<{url:string}>('/v1/media/'+id+'/access',{method:'POST'});window.location.assign(r.url);}catch(e){setError(e instanceof Error?e.message:'Document could not be opened.');}finally{setBusy(false);}}
 if(!can('agents.review'))return null;
 return <section className="panel"><h2>Invited vendors</h2><p className="field-help">Create a seven-day invitation for one email address. Exclusive invitees still upload private school or business evidence; CAC registration remains optional. Creating a link does not send a campaign.</p>{error?<p className="form-error" role="alert">{error}</p>:null}<form className="form-grid manage-form" onSubmit={invite}><label>University<select name="universityId" defaultValue={scope} required><option value="">Select university</option>{access?.universities?.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label><label>Invited email<input type="email" name="email" required placeholder="owner@example.com"/></label><label>Why this business is trusted<textarea name="reason" required minLength={10} maxLength={2000}/></label><button className="button button--primary" disabled={busy}>Create invitation link</button></form>{url?<label>Share this link with the invited business<input readOnly value={url} onFocus={e=>e.target.select()}/></label>:null}{rows.map(r=><article className="panel" key={r.id}><h3>{r.display_name} · {r.status}</h3><p>{r.legal_name} · {r.email} · {r.phone_e164}</p><p>{r.category} · {r.campus} · {r.address}</p><p>{r.description}</p><p className="field-help">Invitation reason: {r.invitation_reason}</p><div className="form-stack"><p className="field-help">Business evidence: {r.business_document_ids?.length??0} private file{(r.business_document_ids?.length??0)===1?'':'s'}.</p>{can('agents.verify')?r.business_document_ids?.map((documentId,index)=><button key={documentId} type="button" className="button" disabled={busy} onClick={()=>void openDocument(documentId)}>Open document {index+1}</button>):<p className="field-help">Document viewing requires agent verification permission.</p>}</div>{r.review_note?<p>Reviewer note: {r.review_note}</p>:null}{['SUBMITTED','IN_REVIEW'].includes(r.status)?<form className="form-stack" onSubmit={e=>void review(e,r)}><label>Decision<select name="decision"><option value="APPROVED">Approve invited vendor</option><option value="REJECTED">Reject</option></select></label><label>Verification note<textarea name="note" required minLength={20} maxLength={2000} placeholder="Record how the business and contact were verified."/></label><label className="consent-row"><input type="checkbox" required/>I reviewed the uploaded business evidence and verified the business and authorised adult contact.</label><button className="button button--primary" disabled={busy}>Save review</button></form>:null}</article>)}</section>;
}
