import test from 'node:test';
import assert from 'node:assert/strict';
import { aiDay, aiLimit, generateAI, parseTimetableJSON, providerConfiguration, selectAIProvider } from '../server/src/lib/ai-provider.ts';
const env={AI_ASSISTANT_ENABLED:'true',HF_TOKEN:'synthetic-token',HF_CHAT_MODEL:'test/chat',HF_VISION_MODEL:'test/vision'};
const hf=(content='Answer',finish_reason='stop')=>Response.json({choices:[{message:{content},finish_reason}]});
for(const mode of ['study','summary','quiz','notes','timetable'])test(`${mode} uses HF exclusively with backend credentials`,async()=>{
 let calls=0;const result=await generateAI(env,{mode,prompt:'Learn physics'},async(url,init)=>{calls++;assert.equal(url,'https://router.huggingface.co/v1/chat/completions');assert.equal(init.headers.Authorization,'Bearer synthetic-token');const body=JSON.parse(init.body);assert.equal(body.model,'test/chat');assert.equal(body.messages.at(-1).content,'Learn physics');return hf();});assert.equal(calls,1);assert.equal(result.text,'Answer');assert.equal(result.provider,'huggingface');
});
test('images use configured vision model and private inline bytes',async()=>{await generateAI(env,{mode:'study',prompt:'Explain',media:{mimeType:'image/png',data:'aGVsbG8='}},async(url,init)=>{const body=JSON.parse(init.body);assert.equal(body.model,'test/vision');assert.equal(body.messages.at(-1).content[1].image_url.url,'data:image/png;base64,aGVsbG8=');return hf();});});
test('PDF extraction happens before inference, without switching provider',async()=>{let calls=0;await assert.rejects(generateAI(env,{mode:'timetable',prompt:'',media:{mimeType:'application/pdf',data:'cGRm'}},async()=>{calls++;return hf();}),{reason:'AI_UNSUPPORTED_MEDIA'});assert.equal(calls,0);assert.equal(selectAIProvider('timetable','application/pdf'),'huggingface');});
test('missing config and kill switch stop provider I/O',async()=>{let calls=0;const network=async()=>{calls++;return hf();};await assert.rejects(generateAI({...env,AI_ASSISTANT_ENABLED:'false'},{mode:'study',prompt:'x'},network),{reason:'AI_DISABLED'});await assert.rejects(generateAI({...env,HF_VISION_MODEL:''},{mode:'study',prompt:'x',media:{mimeType:'image/png',data:'eA=='}},network),{reason:'AI_NOT_CONFIGURED'});assert.equal(calls,0);assert.deepEqual(providerConfiguration({},'study').missing,['HF_TOKEN','HF_CHAT_MODEL']);});
for(const [status,reason]of[[401,'AI_PROVIDER_AUTH'],[403,'AI_PROVIDER_AUTH'],[402,'AI_PROVIDER_LIMIT'],[429,'AI_PROVIDER_LIMIT'],[404,'AI_PROVIDER_UNAVAILABLE'],[500,'AI_PROVIDER_UNAVAILABLE']])test(`HTTP ${status} is sanitized without retry or fallback`,async()=>{let calls=0;await assert.rejects(generateAI(env,{mode:'study',prompt:'x'},async()=>{calls++;return new Response('PRIVATE_SOURCE',{status});}),e=>e.reason===reason&&!e.message.includes('PRIVATE_SOURCE'));assert.equal(calls,1);});
test('history is bounded to six turns',async()=>{const history=Array.from({length:9},(_,i)=>({prompt:`Q${i}`,text:`A${i}`}));await generateAI(env,{mode:'study',prompt:'Next',history},async(url,init)=>{const body=JSON.parse(init.body);assert.equal(body.messages.length,14);assert.equal(body.messages[1].content,'Q3');return hf();});});
test('empty, incomplete and invalid responses fail clearly',async()=>{await assert.rejects(generateAI(env,{mode:'study',prompt:'x'},async()=>hf('')),{reason:'AI_EMPTY_OUTPUT'});await assert.rejects(generateAI(env,{mode:'study',prompt:'x'},async()=>hf('Partial','length')),{reason:'AI_INCOMPLETE'});await assert.rejects(generateAI(env,{mode:'study',prompt:'x'},async()=>new Response('not JSON')));});
test('timeout has a distinct safe failure',async()=>{await assert.rejects(generateAI(env,{mode:'study',prompt:'x'},async()=>{throw new DOMException('secret','TimeoutError');}),{reason:'AI_TIMEOUT'});});
test('JSON timetable shape is bounded',()=>{assert.deepEqual(parseTimetableJSON('```json\n{"entries":[],"warnings":["ambiguous",2]}\n```'),{documentType:'class_timetable',entries:[],events:[],warnings:['ambiguous']});for(const invalid of['{oops','{"classes":[]}'])assert.throws(()=>parseTimetableJSON(invalid),{reason:'AI_INVALID_OUTPUT'});assert.throws(()=>parseTimetableJSON(JSON.stringify({entries:Array(41).fill({})})),{reason:'AI_TOO_MANY_CLASSES'});});
test('limits preserve zero and fail closed',()=>{assert.equal(aiLimit(undefined,5,100),5);for(const value of['0','wat','-1','1.5'])assert.equal(aiLimit(value,5,100),0);assert.equal(aiLimit('1000',5,100),100);});
test('daily global capacity resets at midnight WAT',()=>{assert.deepEqual(aiDay(Date.parse('2026-09-24T23:00:00Z')),{startsAt:'2026-09-24T23:00:00.000Z',resetsAt:'2026-09-25T23:00:00.000Z'});});
