import {useCallback,useEffect,useRef,useState} from 'react';
import {Ionicons} from '@expo/vector-icons';
import {Image,Pressable,Share,Text,View} from 'react-native';
import {router,useFocusEffect} from 'expo-router';
import {randomUUID} from 'expo-crypto';
import {useAuth} from '@/src/auth/auth-context';
import {ToolButton,ToolField,ToolPage} from '@/src/components/toolkit';
import {ScreenSkeleton} from '@/src/components/skeleton';
import {useAppearance} from '@/src/lib/appearance';
import {api} from '@/src/lib/api';
type Post={id:string;title:string;body:string;display_name:string;username:string;avatar_url:string|null;urgent:boolean;venue:string|null;created_at:string;poll_options:string[];votes:{index:number;count:number}[];my_vote:number|null;comment_count:number};
type Comment={id:string;body:string;display_name:string;username:string;author_user_id:string;avatar_url:string|null;created_at:string};
type Detail={group:{id:string;kind:'COMMUNITY'|'STUDY_GROUP';name:string;description:string;members:number;joined_at:string|null;member_role:string|null;owner_user_id:string};canPost:boolean};
export function StudentGroup({id}:{id:string}){
 const {theme}=useAppearance(),{user}=useAuth();const [data,setData]=useState<Detail|null>(null),[posts,setPosts]=useState<Post[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[composer,setComposer]=useState(false),[title,setTitle]=useState(''),[body,setBody]=useState(''),[urgent,setUrgent]=useState(false),[venue,setVenue]=useState(''),[poll,setPoll]=useState(''),[addMember,setAddMember]=useState(false),[username,setUsername]=useState(''),[openComments,setOpenComments]=useState<string|null>(null),[comments,setComments]=useState<Comment[]>([]),[comment,setComment]=useState(''),[requestId,setRequestId]=useState(randomUUID());
 const base='/v1/communities/groups/'+id;
 const generation=useRef(0);
 useEffect(()=>{generation.current++;setData(null);setPosts([]);setComments([]);setOpenComments(null);setComposer(false);},[id,user?.id]);
 const load=useCallback(async()=>{const token=++generation.current;setError('');try{const d=await api<Detail>(base);if(token!==generation.current)return;setData(d);if(d.group.joined_at){const p=await api<{posts:Post[]}>(base+'/posts');if(token===generation.current)setPosts(p.posts??[]);}else setPosts([]);}catch(e){if(token===generation.current)setError(e instanceof Error?e.message:'Could not load your group.');}},[base,user?.id]);
 useFocusEffect(useCallback(()=>{void load();},[load]));
 async function act(path:string,payload:unknown,method='POST'){setBusy(true);setError('');try{await api(base+path,{method,body:JSON.stringify(payload)});await load();return true;}catch(e){setError(e instanceof Error?e.message:'Could not save.');return false;}finally{setBusy(false);}}
 async function showComments(postId:string){setOpenComments(postId);setComment('');setComments([]);setError('');try{const r=await api<{comments:Comment[]}>(base+'/posts/'+postId+'/comments');setComments(r.comments??[]);}catch(e){setError(e instanceof Error?e.message:'Could not load comments.');}}
 const text={fontFamily:theme.font.body,color:theme.text,fontSize:14,lineHeight:23},muted={...text,color:theme.textMuted,fontSize:12};
 const profile=(name:string,handle:string,avatar:string|null)=><Pressable accessibilityRole="button" onPress={()=>router.push({pathname:'/profile',params:{username:handle}})} style={{flexDirection:'row',gap:10,alignItems:'center'}}>{avatar?<Image source={{uri:avatar}} style={{width:34,height:34,borderRadius:17}}/>:<View style={{width:34,height:34,borderRadius:17,alignItems:'center',justifyContent:'center',backgroundColor:theme.surfaceTint}}><Text style={text}>{name.slice(0,1)}</Text></View>}<View><Text style={[text,{fontFamily:theme.font.semibold}]}>{name}</Text><Text style={muted}>@{handle}</Text></View></Pressable>;
 return <ToolPage title={data?.group.name??'Community'} action={<Pressable accessibilityRole="button" onPress={()=>void Share.share({message:`${data?.group.name??'Community'}\nhttps://kampusone-mobile-preview.vercel.app/community?id=${id}&kind=${data?.group.kind??'COMMUNITY'}`})} style={{minHeight:44,justifyContent:'center'}}><Text style={[text,{color:theme.deepBrand}]}>Share</Text></Pressable>} onRefresh={()=>void load()}>
 {error?<View style={{padding:14,borderRadius:12,backgroundColor:theme.surfaceMuted,marginBottom:14}}><Text accessibilityRole="alert" style={[text,{color:theme.error}]}>{error}</Text><ToolButton secondary label="Try again" onPress={()=>void load()}/></View>:null}
 {!data?<ScreenSkeleton/>:<>
 <Text style={muted}>{data.group.kind==='STUDY_GROUP'?'STUDY GROUP':'COMMUNITY'} · {data.group.members} members</Text><Text style={[text,{marginVertical:12}]}>{data.group.description}</Text>
 {!data.group.joined_at?<><Text style={[text,{color:theme.textMuted,marginBottom:14}]}>Join to see updates{data.group.kind==='STUDY_GROUP'?' and study insights':''}. Only members can open this feed.</Text><ToolButton disabled={busy} label={data.group.kind==='STUDY_GROUP'?'Join study group':'Follow community'} onPress={()=>void act('/join',{})}/></>:<>
 <View style={{gap:10,marginVertical:14}}>{data.group.kind==='STUDY_GROUP'?<ToolButton label="Study now and view insights" onPress={()=>router.push({pathname:'/study-history',params:{id,name:data.group.name}})}/>:null}{data.canPost?<ToolButton secondary label={composer?'Close draft':'Write an update'} disabled={busy} onPress={()=>{setComposer(v=>!v);setRequestId(randomUUID());}}/>:null}{data.group.member_role==='ADMIN'?<ToolButton secondary label={addMember?'Cancel adding member':'Add a member'} onPress={()=>setAddMember(v=>!v)}/>:null}</View>
 {addMember?<View style={{marginBottom:20}}><ToolField label="Student username" value={username} onChangeText={setUsername} placeholder="@username" autoCapitalize="none"/><ToolButton label="Add member" disabled={busy||username.replace('@','').trim().length<3} onPress={()=>void act('/members',{username}).then(ok=>{if(ok){setUsername('');setAddMember(false);}})}/></View>:null}
 {composer?<View style={{padding:18,borderRadius:18,borderWidth:1,borderColor:theme.border,backgroundColor:theme.surface,marginBottom:20}}>
 <ToolField label="Title" value={title} maxLength={140} onChangeText={v=>{setTitle(v);setRequestId(randomUUID());}}/><ToolField label="Update" value={body} multiline maxLength={5000} onChangeText={v=>{setBody(v);setRequestId(randomUUID());}}/>
 {data.group.member_role==='ADMIN'?<Pressable accessibilityRole="checkbox" accessibilityState={{checked:urgent}} onPress={()=>{setUrgent(v=>!v);setRequestId(randomUUID());}} style={{paddingVertical:14}}><View style={{flexDirection:'row',alignItems:'center',gap:10}}><Ionicons name={urgent?'checkbox':'square-outline'} size={22} color={theme.deepBrand}/><Text style={text}>Urgent update</Text></View><Text style={muted}>Use for important changes such as a new class venue.</Text></Pressable>:null}
 {urgent?<ToolField label="New venue (optional)" value={venue} maxLength={180} onChangeText={v=>{setVenue(v);setRequestId(randomUUID());}}/>:null}
 <ToolField label="Poll options (optional)" value={poll} multiline maxLength={650} onChangeText={v=>{setPoll(v);setRequestId(randomUUID());}} placeholder={'One option per line. Add 2 to 6 options.'}/>
 <ToolButton disabled={busy||!title.trim()||!body.trim()} label={busy?'Publishing…':'Publish update'} onPress={()=>void act('/posts',{title,body,urgent,venue:venue.trim()||undefined,pollOptions:poll.split('\n').map(v=>v.trim()).filter(Boolean),requestId}).then(ok=>{if(ok){setComposer(false);setTitle('');setBody('');setPoll('');setVenue('');setUrgent(false);setRequestId(randomUUID());}})}/>
 </View>:null}
 {posts.length?posts.map(post=><View key={post.id} style={{paddingVertical:20,borderBottomWidth:1,borderColor:theme.border,gap:12}}>
 {profile(post.display_name,post.username,post.avatar_url)}<Text style={muted}>{new Date(post.created_at).toLocaleString('en-NG')}{post.urgent?' · URGENT':''}</Text><Text style={{fontFamily:theme.font.displayStrong,fontSize:19,color:theme.text}}>{post.title}</Text><Text style={text}>{post.body}</Text>{post.venue?<Text style={[text,{fontFamily:theme.font.semibold}]}>New venue · {post.venue}</Text>:null}
 {post.poll_options?.map((option,index)=>{const count=post.votes?.find(v=>v.index===index)?.count??0;return <Pressable key={index} accessibilityRole="button" accessibilityState={{selected:post.my_vote===index,disabled:busy}} disabled={busy} onPress={()=>void act('/posts/'+post.id+'/vote',{optionIndex:index})} style={{padding:14,borderRadius:12,borderWidth:1,borderColor:post.my_vote===index?theme.deepBrand:theme.border,backgroundColor:post.my_vote===index?theme.surfaceTint:theme.surface}}><Text style={text}>{option} · {count} votes{post.my_vote===index?' · Your vote':''}</Text></Pressable>;})}
 <Pressable accessibilityRole="button" onPress={()=>openComments===post.id?setOpenComments(null):void showComments(post.id)} style={{minHeight:44,justifyContent:'center'}}><Text style={[text,{color:theme.deepBrand}]}>{post.comment_count} comments</Text></Pressable>
 {openComments===post.id?<View style={{gap:12,padding:14,borderRadius:14,backgroundColor:theme.surfaceMuted}}>{comments.map(c=><View key={c.id} style={{gap:6}}>{profile(c.display_name,c.username,c.avatar_url)}<Text style={text}>{c.body}</Text>{c.author_user_id===user?.id?<Pressable onPress={()=>void act('/posts/'+post.id+'/comments/'+c.id,{},'DELETE').then(ok=>{if(ok)void showComments(post.id);})} disabled={busy}><Text style={[muted,{color:theme.error,paddingVertical:8}]}>Delete my comment</Text></Pressable>:null}</View>)}<ToolField label="Your comment" value={comment} maxLength={2000} onChangeText={setComment} multiline/><ToolButton label="Send comment" disabled={busy||!comment.trim()} onPress={()=>void act('/posts/'+post.id+'/comments',{body:comment}).then(ok=>{if(ok)void showComments(post.id);})}/></View>:null}
 </View>):<Text style={[text,{color:theme.textMuted,paddingVertical:28}]}>No updates yet. {data.canPost?'Write the first one.':'Updates from the admin will appear here.'}</Text>}
 {data.group.owner_user_id!==user?.id?<ToolButton secondary disabled={busy} label={data.group.kind==='STUDY_GROUP'?'Leave study group':'Unfollow community'} onPress={()=>void act('/join',{},'DELETE')}/>:null}
 </>}
 </>}
 </ToolPage>;
}
