import {CommunitySubscriptionSheet,CommunityRequestInbox} from './community-requests';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Ionicons} from '@expo/vector-icons';
import {Alert,Image,Modal,Pressable,ScrollView,Switch,Text,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {router,useFocusEffect} from 'expo-router';
import {randomUUID} from 'expo-crypto';
import {useAuth} from '@/src/auth/auth-context';
import {ToolButton,ToolField,ToolPage} from '@/src/components/toolkit';
import {ScreenSkeleton} from '@/src/components/skeleton';
import {useAppearance} from '@/src/lib/appearance';
import {api} from '@/src/lib/api';
import {pickAndUpload} from '@/src/lib/uploads';
import {pushSetupAvailability,registerPushDevice} from '@/src/lib/push-registration';
import {normalizeGroupDetail,normalizeGroupPosts,normalizeGroupComments,normalizeGroupMembers,type GroupDetail,type GroupPost,type GroupComment,type GroupMember} from '@/src/lib/student-group-state';
import {shareItem} from '@/src/lib/share-content';
import {feedTime} from '@/src/lib/feed-time';

function GroupAvatar({name,uri,size=44}:{name:string;uri:string|null;size?:number}){
 const {theme}=useAppearance(),[failed,setFailed]=useState(false);
 useEffect(()=>setFailed(false),[uri]);
 return uri&&!failed?<Image accessibilityLabel={`${name} profile picture`} source={{uri}} onError={()=>setFailed(true)} style={{width:size,height:size,borderRadius:Math.max(8,size*.18)}}/>:<View style={{width:size,height:size,borderRadius:Math.max(8,size*.18),alignItems:'center',justifyContent:'center',backgroundColor:theme.surfaceTint}}><Text style={{fontFamily:theme.font.displayStrong,fontSize:size*.38,color:theme.deepBrand}}>{name.trim().slice(0,1).toUpperCase()||'K'}</Text></View>;
}
export function StudentGroup({id}:{id:string}){
 const {theme}=useAppearance(),{user}=useAuth();
 const [data,setData]=useState<GroupDetail|null>(null),[posts,setPosts]=useState<GroupPost[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[composer,setComposer]=useState(false),[title,setTitle]=useState(''),[body,setBody]=useState(''),[urgent,setUrgent]=useState(false),[venue,setVenue]=useState(''),[poll,setPoll]=useState(''),[details,setDetails]=useState(false),[addMember,setAddMember]=useState(false),[username,setUsername]=useState(''),[openComments,setOpenComments]=useState<string|null>(null),[comments,setComments]=useState<GroupComment[]>([]),[comment,setComment]=useState(''),[requestId,setRequestId]=useState(randomUUID());
 const [subscribeOpen,setSubscribeOpen]=useState(false),[requestsOpen,setRequestsOpen]=useState(false),[editGuidelines,setEditGuidelines]=useState('');
 const [membersOpen,setMembersOpen]=useState(false),[members,setMembers]=useState<GroupMember[]>([]),[membersLoading,setMembersLoading]=useState(false),[notificationPrompt,setNotificationPrompt]=useState(false);
 const [postImage,setPostImage]=useState<{id:string;url:string}|null>(null),[commentImage,setCommentImage]=useState<{id:string;url:string}|null>(null),[mediaUploading,setMediaUploading]=useState(false);
 const [editing,setEditing]=useState(false),[editName,setEditName]=useState(''),[editDescription,setEditDescription]=useState(''),[editAvatar,setEditAvatar]=useState<string|null>(null),[editAvatarId,setEditAvatarId]=useState<string|null>(null),[membersCanPost,setMembersCanPost]=useState(true),[uploading,setUploading]=useState(false);
 const base='/v1/communities/groups/'+id,generation=useRef(0),commentGeneration=useRef(0),mutation=useRef(false);
 useEffect(()=>{generation.current++;commentGeneration.current++;setData(null);setPosts([]);setComments([]);setOpenComments(null);setComposer(false);setPostImage(null);setCommentImage(null);setEditing(false);setMembersOpen(false);},[id,user?.id]);
 const load=useCallback(async()=>{
  const token=++generation.current;setError('');
  try{const d=normalizeGroupDetail(await api<unknown>(base),id);if(token!==generation.current)return;setData(d);
   if(d.group.joined_at){const p=await api<unknown>(base+'/posts');if(token===generation.current)setPosts(normalizeGroupPosts(p));}else setPosts([]);
  }catch(e){if(token===generation.current)setError(e instanceof Error?e.message:'Could not load your community.');}
 },[base,id,user?.id]);
 useFocusEffect(useCallback(()=>{void load();return()=>{generation.current++;commentGeneration.current++;};},[load]));
 async function act(path:string,payload:unknown,method='POST'){
  if(mutation.current)return false;mutation.current=true;setBusy(true);setError('');
  try{await api(base+path,{method,body:JSON.stringify(payload)});await load();return true;}catch(e){setError(e instanceof Error?e.message:'Could not save. Your draft is kept.');return false;}finally{mutation.current=false;setBusy(false);}
 }
 async function showComments(postId:string){const token=++commentGeneration.current;setOpenComments(postId);setComment('');setCommentImage(null);setComments([]);setError('');try{const r=await api<unknown>(base+'/posts/'+postId+'/comments');if(token===commentGeneration.current)setComments(normalizeGroupComments(r));}catch(e){if(token===commentGeneration.current)setError(e instanceof Error?e.message:'Could not load comments.');}}
 async function attachPostImage(){if(mediaUploading)return;setMediaUploading(true);setError('');try{const image=await pickAndUpload('post');if(image)setPostImage({id:image.id,url:image.url});}catch(e){setError(e instanceof Error?e.message:'Could not add this image.');}finally{setMediaUploading(false);}}
 async function attachCommentImage(){if(mediaUploading)return;setMediaUploading(true);setError('');try{const image=await pickAndUpload('post');if(image)setCommentImage({id:image.id,url:image.url});}catch(e){setError(e instanceof Error?e.message:'Could not add this reply image.');}finally{setMediaUploading(false);}}
 function deletePost(post:GroupPost){Alert.alert('Delete update?','This removes the update and its comments from the community.',[{text:'Cancel',style:'cancel'},{text:'Delete',style:'destructive',onPress:()=>void act('/posts/'+post.id,{},'DELETE')}]);}
 async function showMembers(){setMembersOpen(true);setMembersLoading(true);setMembers([]);try{setMembers(normalizeGroupMembers(await api<unknown>(base+'/members')));}catch(e){setError(e instanceof Error?e.message:'Could not load members.');setMembersOpen(false);}finally{setMembersLoading(false);}}
 function edit(){if(!data)return;setEditName(data.group.name);setEditDescription(data.group.description);setEditGuidelines(data.group.guidelines);setMembersCanPost(data.group.members_can_post);setEditAvatar(data.group.avatar_url);setEditAvatarId(data.group.avatar_media_id);setError('');setEditing(true);}
 async function photo(){if(uploading)return;setUploading(true);setError('');try{const image=await pickAndUpload('post');if(image){setEditAvatar(image.url);setEditAvatarId(image.id);}}catch(e){setError(e instanceof Error?e.message:'Could not upload this photo.');}finally{setUploading(false);}}
 async function notifications(enabled:boolean){
  setNotificationPrompt(false);
  const saved=await act('/notifications',{enabled},'PATCH');
  if(saved&&enabled&&user?.id&&pushSetupAvailability().available){try{await registerPushDevice(user.id,true);}catch(e){setError(e instanceof Error?e.message:'Notifications are on in KampusOne. Allow device notifications in Settings to receive push alerts.');}}
 }
 const text={fontFamily:theme.font.body,color:theme.text,fontSize:14,lineHeight:23},muted={...text,color:theme.textMuted,fontSize:12},admin=data?.group.member_role==='ADMIN';
 const profile=(name:string,handle:string,avatar:string|null,role?:string)=><View style={{flexDirection:'row',alignItems:'center',gap:10}}><Pressable accessibilityRole="button" accessibilityLabel={`Open ${name}'s profile`} disabled={!handle} onPress={()=>router.push({pathname:'/profile',params:{username:handle}})} style={{flex:1,flexDirection:'row',gap:10,alignItems:'center'}}><GroupAvatar name={name} uri={avatar}/><View style={{flex:1}}><Text style={[text,{fontFamily:theme.font.semibold}]}>{name}</Text>{handle?<Text style={muted}>@{handle}</Text>:null}</View></Pressable>{role==='ADMIN'?<View style={{flexDirection:'row',alignItems:'center',gap:4,backgroundColor:theme.surfaceTint,paddingHorizontal:8,paddingVertical:5,borderRadius:7}}><Ionicons name="shield-checkmark-outline" size={13} color={theme.deepBrand}/><Text style={[muted,{color:theme.deepBrand,fontFamily:theme.font.semibold}]}>Admin</Text></View>:null}</View>;
 const errorMessage=error?<View style={{padding:14,borderRadius:12,backgroundColor:theme.surfaceMuted,marginBottom:14}}><Text accessibilityRole="alert" style={[text,{color:theme.error}]}>{error}</Text>{!editing?<ToolButton secondary label="Try again" onPress={()=>void load()}/>:null}</View>:null;
 return <ToolPage title={data?.group.kind==='STUDY_GROUP'?'Study group':'Community'} action={<View style={{flexDirection:'row',gap:4}}>{admin?<Pressable accessibilityRole="button" accessibilityLabel="Edit community profile and posting settings" onPress={edit} style={{minHeight:44,minWidth:44,alignItems:'center',justifyContent:'center'}}><Ionicons name="settings-outline" size={22} color={theme.deepBrand}/></Pressable>:null}<Pressable accessibilityRole="button" accessibilityLabel="Share community" onPress={()=>void shareItem(data?.group.kind==='STUDY_GROUP'?'study-group':'community',id,data?.group.name??'Community').catch(()=>setError('Could not share this community.'))} style={{minHeight:44,minWidth:44,alignItems:'center',justifyContent:'center'}}><Ionicons name="share-outline" size={22} color={theme.deepBrand}/></Pressable></View>} onRefresh={()=>void load()}>
 {errorMessage}
 {!data?<ScreenSkeleton/>:<>
  <View style={{padding:20,gap:14,backgroundColor:theme.surfaceTint,borderRadius:24,borderWidth:1,borderColor:theme.border,marginBottom:18}}>
   <GroupAvatar name={data.group.name} uri={data.group.avatar_url} size={84}/>
   <View style={{gap:5}}><Text accessibilityRole="header" style={{fontFamily:theme.font.displayStrong,fontSize:27,lineHeight:33,color:theme.text}}>{data.group.name}</Text><Text style={muted}>{data.group.kind==='STUDY_GROUP'?'Study group':'Community'}</Text></View>
   {data.group.description?<Text style={text}>{data.group.description}</Text>:null}
   <Pressable accessibilityRole="button" accessibilityLabel="View community members" onPress={()=>void showMembers()} style={{minHeight:44,flexDirection:'row',gap:7,alignItems:'center'}}><Ionicons name="people-outline" size={18} color={theme.textMuted}/><Text style={[text,{fontFamily:theme.font.semibold}]}>{data.group.members} {data.group.kind==='COMMUNITY'?(data.group.members===1?'subscriber':'subscribers'):(data.group.members===1?'member':'members')}</Text><Ionicons name="chevron-forward" size={14} color={theme.textMuted}/></Pressable>
   {!data.group.joined_at?<ToolButton disabled={busy} label={data.group.kind==='STUDY_GROUP'?'Join study group':data.group.request_status==='PENDING'?'Request pending':'Subscribe'} onPress={()=>{if(data.group.kind==='COMMUNITY')setSubscribeOpen(true);else void act('/join',{}).then(ok=>{if(ok)setNotificationPrompt(true);});}}/>:<View style={{flexDirection:'row',gap:10,alignItems:'center'}}><View style={{flex:1}}>{data.group.owner_user_id!==user?.id?<ToolButton secondary disabled={busy} label={data.group.kind==='STUDY_GROUP'?'Leave study group':'Subscribed'} onPress={()=>void act('/join',{},'DELETE')}/>:<Text style={[text,{fontFamily:theme.font.semibold,color:theme.deepBrand}]}>Your community</Text>}</View><Pressable accessibilityRole="switch" accessibilityState={{checked:data.group.notifications_enabled,disabled:busy}} accessibilityLabel="Community post notifications" disabled={busy} onPress={()=>void notifications(!data.group.notifications_enabled)} style={{minHeight:48,minWidth:48,borderRadius:12,borderWidth:1,borderColor:theme.border,alignItems:'center',justifyContent:'center',backgroundColor:data.group.notifications_enabled?theme.surfaceTint:theme.surface}}><Ionicons name={data.group.notifications_enabled?'notifications':'notifications-off-outline'} size={21} color={theme.deepBrand}/></Pressable></View>}
   {admin?<Pressable accessibilityRole="button" accessibilityLabel={`Subscription requests, ${data.group.pending_requests} pending`} onPress={()=>setRequestsOpen(true)} style={{flexDirection:'row',alignItems:'center',gap:10,padding:14,minHeight:52,borderRadius:14,backgroundColor:theme.surface}}><Ionicons name="person-add-outline" size={21} color={theme.deepBrand}/><Text style={[text,{flex:1,fontFamily:theme.font.semibold}]}>Subscription requests</Text><View style={{backgroundColor:theme.deepBrand,paddingHorizontal:9,paddingVertical:4,borderRadius:10}}><Text style={{color:'#fff',fontFamily:theme.font.semibold}}>{data.group.pending_requests}</Text></View><Ionicons name="chevron-forward" size={17} color={theme.deepBrand}/></Pressable>:null}
   {data.group.joined_at?<Text style={muted}>{data.group.notifications_enabled?'Notifications on':'Notifications off'} · {data.group.members_can_post?'Members can post':'Only admins can post'}</Text>:null}
  </View>
  <View style={{borderBottomWidth:1,borderColor:theme.border,marginBottom:16}}/>
  {!data.group.joined_at?<Text style={[text,{color:theme.textMuted,paddingVertical:22}]}>Subscribe to see posts and receive updates from this community.</Text>:<>
   {data.group.kind==='STUDY_GROUP'?<ToolButton label="Study now and view insights" onPress={()=>router.push({pathname:'/study-history',params:{id,name:data.group.name}})}/>:null}
   {data.canPost?<Pressable accessibilityRole="button" accessibilityLabel={composer?'Close draft':'Share something with your community…'} disabled={busy} onPress={()=>{setComposer(v=>!v);if(!composer)setRequestId(randomUUID());}} style={{minHeight:64,flexDirection:'row',alignItems:'center',gap:12,borderWidth:1,borderColor:theme.border,borderRadius:16,padding:14,backgroundColor:theme.surface,marginVertical:10}}><Ionicons name="create-outline" size={23} color={theme.deepBrand}/><Text style={[text,{flex:1,color:theme.textMuted}]}>{composer?'Close draft':'Share something with your community…'}</Text><Ionicons name={composer?'chevron-up':'chevron-forward'} size={18} color={theme.textMuted}/></Pressable>:null}
   {composer?<View style={{padding:16,borderRadius:16,borderWidth:1,borderColor:theme.border,backgroundColor:theme.surface,marginBottom:18,gap:10}}>
    <ToolField label="Your post" value={body} placeholder="What would you like to share?" multiline maxLength={5000} onChangeText={v=>{setBody(v);setRequestId(randomUUID());}}/>
    {postImage?<View style={{gap:8}}><Image accessibilityLabel="Selected community post image" source={{uri:postImage.url}} resizeMode="cover" style={{width:'100%',aspectRatio:1.55,borderRadius:16,backgroundColor:theme.surfaceMuted}}/><Pressable accessibilityRole="button" onPress={()=>{setPostImage(null);setRequestId(randomUUID());}} style={{minHeight:44,alignSelf:'flex-start',justifyContent:'center'}}><Text style={[muted,{color:theme.error}]}>Remove image</Text></Pressable></View>:null}
    <Pressable accessibilityRole="button" disabled={mediaUploading} onPress={()=>void attachPostImage()} style={{minHeight:46,flexDirection:'row',alignItems:'center',gap:8}}><Ionicons name="image-outline" size={21} color={theme.deepBrand}/><Text style={[text,{color:theme.deepBrand}]}>{mediaUploading?'Adding image…':postImage?'Replace image':'Add image'}</Text></Pressable>
    <Pressable accessibilityRole="button" accessibilityState={{expanded:details}} onPress={()=>setDetails(v=>!v)} style={{minHeight:44,flexDirection:'row',alignItems:'center',gap:8}}><Ionicons name={details?'remove-circle-outline':'add-circle-outline'} size={20} color={theme.deepBrand}/><Text style={[text,{color:theme.deepBrand}]}>{details?'Hide post options':'Add a title, poll or urgent update'}</Text></Pressable>
    {details?<>
     <ToolField label="Title (optional)" value={title} maxLength={140} onChangeText={v=>{setTitle(v);setRequestId(randomUUID());}}/>
     {admin?<Pressable accessibilityRole="checkbox" accessibilityState={{checked:urgent}} onPress={()=>{setUrgent(v=>!v);setRequestId(randomUUID());}} style={{minHeight:44,flexDirection:'row',alignItems:'center',gap:10}}><Ionicons name={urgent?'checkbox':'square-outline'} size={22} color={theme.deepBrand}/><Text style={text}>Urgent update</Text></Pressable>:null}
     {urgent?<ToolField label="New venue (optional)" value={venue} maxLength={180} onChangeText={v=>{setVenue(v);setRequestId(randomUUID());}}/>:null}
     <ToolField label="Poll options (optional)" value={poll} multiline maxLength={650} onChangeText={v=>{setPoll(v);setRequestId(randomUUID());}} placeholder={'One option per line. Add 2 to 6 options.'}/>
    </>:null}
    <ToolButton disabled={busy||mediaUploading||(!body.trim()&&!postImage)} label={busy?'Publishing…':'Post'} onPress={()=>void act('/posts',{title:title.trim(),body,mediaId:postImage?.id??null,urgent,venue:venue.trim()||undefined,pollOptions:poll.split('\n').map(v=>v.trim()).filter(Boolean),requestId}).then(ok=>{if(ok){setComposer(false);setTitle('');setBody('');setPostImage(null);setPoll('');setVenue('');setUrgent(false);setDetails(false);setRequestId(randomUUID());}})}/>
   </View>:null}
   {posts.length?posts.map(post=><View key={post.id} style={{padding:18,borderRadius:20,borderWidth:1,borderColor:post.urgent?theme.deepBrand:theme.border,backgroundColor:post.urgent?theme.surfaceTint:theme.surface,gap:12,marginBottom:14}}>
    {profile(post.display_name,post.username,post.avatar_url,post.author_role)}<Text style={muted}>{feedTime(post.created_at).text}{post.urgent?' · Urgent':''}</Text>
    {post.title&&post.title!=='Photo'&&post.title!==post.body.trim().split('\n')[0]?.slice(0,140)?<Text style={{fontFamily:theme.font.displayStrong,fontSize:19,color:theme.text}}>{post.title}</Text>:null}{post.body?<Text style={text}>{post.body}</Text>:null}{post.media_url?<Image accessibilityLabel="Community post image" source={{uri:post.media_url}} resizeMode="cover" style={{width:'100%',aspectRatio:1.35,borderRadius:16,backgroundColor:theme.surfaceMuted}}/>:null}{post.venue?<Text style={[text,{fontFamily:theme.font.semibold}]}>New venue · {post.venue}</Text>:null}
    {post.poll_options.map((option,index)=>{const votes=post.votes.find(v=>v.index===index)?.count??0;return <Pressable key={index} accessibilityRole="button" accessibilityState={{selected:post.my_vote===index,disabled:busy}} disabled={busy} onPress={()=>void act('/posts/'+post.id+'/vote',{optionIndex:index})} style={{minHeight:48,padding:12,borderRadius:12,borderWidth:1,borderColor:post.my_vote===index?theme.deepBrand:theme.border,backgroundColor:post.my_vote===index?theme.surfaceTint:theme.surface}}><Text style={text}>{option} · {votes} {votes===1?'vote':'votes'}{post.my_vote===index?' · Your vote':''}</Text></Pressable>;})}
    <View style={{flexDirection:'row',alignItems:'center',gap:18,borderTopWidth:1,borderColor:theme.border,paddingTop:8}}>
     <Pressable accessibilityRole="button" accessibilityLabel={post.liked_by_me?'Unlike update':'Like update'} disabled={busy} onPress={()=>void act('/posts/'+post.id+'/like',{},post.liked_by_me?'DELETE':'PUT')} style={{minHeight:44,flexDirection:'row',alignItems:'center',gap:6}}><Ionicons name={post.liked_by_me?'heart':'heart-outline'} size={20} color={post.liked_by_me?theme.deepBrand:theme.textMuted}/><Text style={[muted,{fontFamily:theme.font.semibold}]}>{post.like_count||'Like'}</Text></Pressable>
     <Pressable accessibilityRole="button" accessibilityLabel="Open comments" onPress={()=>{if(openComments===post.id){commentGeneration.current++;setOpenComments(null);setCommentImage(null);}else void showComments(post.id);}} style={{minHeight:44,flexDirection:'row',alignItems:'center',gap:6}}><Ionicons name="chatbubble-outline" size={19} color={theme.textMuted}/><Text style={[muted,{fontFamily:theme.font.semibold}]}>{post.comment_count||'Comment'}</Text></Pressable>
     <Pressable accessibilityRole="button" accessibilityLabel="Share update" onPress={()=>void shareItem('community',id,post.title||data.group.name,post.body||'View this community update on KampusOne').catch(()=>setError('Could not share this update.'))} style={{minHeight:44,flexDirection:'row',alignItems:'center',gap:6}}><Ionicons name="share-outline" size={20} color={theme.textMuted}/><Text style={[muted,{fontFamily:theme.font.semibold}]}>Share</Text></Pressable>
     {post.author_user_id===user?.id||admin?<Pressable accessibilityRole="button" accessibilityLabel="Delete update" disabled={busy} onPress={()=>deletePost(post)} style={{minHeight:44,minWidth:44,alignItems:'center',justifyContent:'center',marginLeft:'auto'}}><Ionicons name="trash-outline" size={19} color={theme.error}/></Pressable>:null}
    </View>
    {openComments===post.id?<View style={{gap:12,padding:14,borderRadius:14,backgroundColor:theme.surfaceMuted}}>{comments.map(c=><View key={c.id} style={{gap:6}}>{profile(c.display_name,c.username,c.avatar_url)}{c.body?<Text style={text}>{c.body}</Text>:null}{c.media_url?<Image accessibilityLabel="Community reply image" source={{uri:c.media_url}} resizeMode="cover" style={{width:'100%',aspectRatio:1.45,borderRadius:14,backgroundColor:theme.surface}}/>:null}{c.author_user_id===user?.id||admin?<Pressable accessibilityRole="button" onPress={()=>void act('/posts/'+post.id+'/comments/'+c.id,{},'DELETE').then(ok=>{if(ok)void showComments(post.id);})} disabled={busy} style={{minHeight:44,justifyContent:'center'}}><Text style={[muted,{color:theme.error}]}>Delete comment</Text></Pressable>:null}</View>)}<ToolField label="Your comment" value={comment} maxLength={2000} onChangeText={setComment} multiline/>{commentImage?<View style={{gap:6}}><Image accessibilityLabel="Selected reply image" source={{uri:commentImage.url}} resizeMode="cover" style={{width:'100%',aspectRatio:1.5,borderRadius:14,backgroundColor:theme.surface}}/><Pressable accessibilityRole="button" onPress={()=>setCommentImage(null)} style={{minHeight:40,justifyContent:'center'}}><Text style={[muted,{color:theme.error}]}>Remove image</Text></Pressable></View>:null}<Pressable accessibilityRole="button" disabled={mediaUploading} onPress={()=>void attachCommentImage()} style={{minHeight:44,flexDirection:'row',alignItems:'center',gap:7}}><Ionicons name="image-outline" size={19} color={theme.deepBrand}/><Text style={[text,{color:theme.deepBrand}]}>{mediaUploading?'Adding image…':commentImage?'Replace reply image':'Add image to reply'}</Text></Pressable><ToolButton label="Send comment" disabled={busy||mediaUploading||(!comment.trim()&&!commentImage)} onPress={()=>void act('/posts/'+post.id+'/comments',{body:comment,mediaId:commentImage?.id??null}).then(ok=>{if(ok){setComment('');setCommentImage(null);void showComments(post.id);}})}/></View>:null}
   </View>):<View style={{paddingVertical:36,gap:8}}><Text style={[text,{fontFamily:theme.font.semibold}]}>Start the conversation</Text><Text style={[text,{color:theme.textMuted}]}>{data.canPost?'Share the first post with your community.':'Posts from your community admins will appear here.'}</Text></View>}
  </>}
 </>}
 <Modal visible={notificationPrompt} transparent animationType="fade" onRequestClose={()=>setNotificationPrompt(false)}><View style={{flex:1,backgroundColor:'rgba(0,0,0,.35)',justifyContent:'center',padding:24}}><View style={{padding:24,borderRadius:22,backgroundColor:theme.canvas,gap:16}}><Ionicons name="notifications-outline" size={32} color={theme.deepBrand}/><Text style={[text,{fontFamily:theme.font.displayStrong,fontSize:23}]}>Keep up with {data?.group.name??'your community'}</Text><Text style={[text,{color:theme.textMuted}]}>Get a notification when a new post is shared. You can change this with the bell at any time.</Text><ToolButton label="Turn on notifications" onPress={()=>void notifications(true)}/><ToolButton secondary label="Not now" onPress={()=>setNotificationPrompt(false)}/></View></View></Modal>
 <Modal visible={membersOpen} animationType="slide" presentationStyle="pageSheet" onRequestClose={()=>setMembersOpen(false)}><SafeAreaView style={{flex:1,backgroundColor:theme.canvas,padding:20}}><View style={{flexDirection:'row',alignItems:'center',marginBottom:20}}><Text style={[text,{fontFamily:theme.font.displayStrong,fontSize:24,flex:1}]}>Members</Text><Pressable accessibilityRole="button" accessibilityLabel="Close members" onPress={()=>setMembersOpen(false)} style={{minHeight:44,minWidth:44,alignItems:'center',justifyContent:'center'}}><Ionicons name="close" size={24} color={theme.text}/></Pressable></View><ScrollView>{errorMessage}{admin?<><ToolButton secondary label={addMember?'Cancel adding member':'Add a member'} onPress={()=>setAddMember(v=>!v)}/>{addMember?<View style={{marginBottom:20}}><ToolField label="Student username" value={username} onChangeText={setUsername} placeholder="@username" autoCapitalize="none"/><ToolButton label="Add member" disabled={busy||username.replace('@','').trim().length<3} onPress={()=>void act('/members',{username}).then(ok=>{if(ok){setUsername('');setAddMember(false);void showMembers();}})}/></View>:null}</>:null}{membersLoading?<ScreenSkeleton/>:members.map(member=><View key={member.user_id} style={{paddingVertical:14,borderBottomWidth:1,borderColor:theme.border}}>{profile(member.display_name,member.username,member.avatar_url,member.role)}</View>)}</ScrollView></SafeAreaView></Modal>
 <Modal visible={editing} animationType="slide" presentationStyle="pageSheet" onRequestClose={()=>{if(!busy&&!uploading)setEditing(false);}}><SafeAreaView style={{flex:1,backgroundColor:theme.canvas}}><ScrollView contentContainerStyle={{padding:20,gap:16}} keyboardShouldPersistTaps="handled"><View style={{flexDirection:'row',alignItems:'center'}}><Text style={[text,{fontFamily:theme.font.displayStrong,fontSize:24,flex:1}]}>Edit community</Text><Pressable accessibilityRole="button" accessibilityLabel="Close community editor" disabled={busy||uploading} onPress={()=>setEditing(false)} style={{minHeight:44,minWidth:44,alignItems:'center',justifyContent:'center'}}><Ionicons name="close" size={24} color={theme.text}/></Pressable></View>{errorMessage}<GroupAvatar name={editName} uri={editAvatar} size={84}/><ToolButton secondary label={uploading?'Uploading photo…':'Change community picture'} disabled={uploading||busy} onPress={()=>void photo()}/>{editAvatar?<ToolButton secondary label="Remove picture" disabled={uploading||busy} onPress={()=>{setEditAvatar(null);setEditAvatarId(null);}}/>:null}<ToolField label="Community name" value={editName} maxLength={100} editable={!busy} onChangeText={setEditName}/><ToolField label="Description" value={editDescription} multiline maxLength={1000} editable={!busy} onChangeText={setEditDescription}/><ToolField label="Community guidelines" value={editGuidelines} multiline maxLength={5000} editable={!busy} onChangeText={setEditGuidelines} placeholder="The rules members agree to before subscribing."/><View style={{flexDirection:'row',gap:12,alignItems:'center',paddingVertical:14}}><View style={{flex:1}}><Text style={[text,{fontFamily:theme.font.semibold}]}>Members can post</Text><Text style={muted}>{membersCanPost?'Everyone in the community can share posts.':'Only community admins can share posts.'}</Text></View><Switch accessibilityLabel="Allow community members to post" value={membersCanPost} disabled={busy} onValueChange={setMembersCanPost} trackColor={{false:theme.border,true:theme.deepBrand}}/></View><ToolButton label={busy?'Saving…':'Save changes'} disabled={busy||uploading||editName.trim().length<3} onPress={()=>void act('',{name:editName,description:editDescription,guidelines:editGuidelines,membersCanPost,avatarMediaId:editAvatarId},'PATCH').then(ok=>{if(ok)setEditing(false);})}/></ScrollView></SafeAreaView></Modal>
 {data?<><CommunitySubscriptionSheet visible={subscribeOpen} base={base} group={data.group} onClose={()=>setSubscribeOpen(false)} onSaved={load}/><CommunityRequestInbox visible={requestsOpen} base={base} onClose={()=>setRequestsOpen(false)} onSaved={load}/></>:null}
 </ToolPage>;
}
