import {useCallback,useEffect,useMemo,useState} from 'react';
import {Image,Pressable,StyleSheet,Text,View} from 'react-native';
import {useSafeAreaInsets} from 'react-native-safe-area-context';
import AsyncStorage from '@react-native-async-storage/async-storage';
import {Ionicons} from '@expo/vector-icons';
import {useAuth} from '@/src/auth/auth-context';
import {api} from '@/src/lib/api';
import {useThemeStyles,type Theme} from '@/src/lib/appearance';
import {UNIBEN_UGBOWO_FALLBACK,type CampusPlace} from '@/src/lib/campus-data';
import {useCampusLocation} from '@/src/lib/campus-location';
import {CampusMapSurface,type MapPayload} from '@/src/components/campus-map-surface';
import {CampusMapDrawer} from '@/src/components/campus-map-drawer';
type Campus={id:string;name:string;slug:string;latitude:string;longitude:string};
type Route={distanceMetres:number;durationSeconds:number;geometry:unknown;notice:string|null;instructions:string[]};
type Detail={media:{id:string;url:string;attribution:string;captured_at:string|null}[];entrances:unknown[]};
const unibenCampuses:Campus[]=[{id:'1d60dcae-760d-4de7-8443-6a870d9bbe1a',name:'Ugbowo',slug:'ugbowo',latitude:'6.398255',longitude:'5.618838'},{id:'111aadbe-d71e-4062-9daa-26374d8e5d9d',name:'Ekehuan',slug:'ekehuan',latitude:'6.3337',longitude:'5.60015'}];
const emptyFeatures={type:'FeatureCollection',features:[]};
function distance(a:[number,number],b:[number,number]){const rad=Math.PI/180,h=Math.sin((a[1]-b[1])*rad/2)**2+Math.cos(a[1]*rad)*Math.cos(b[1]*rad)*Math.sin((a[0]-b[0])*rad/2)**2;return 12742000*Math.atan2(Math.sqrt(h),Math.sqrt(1-h));}
export default function CampusMap(){
 const {profile}=useAuth(),{theme,styles}=useThemeStyles(makeStyles),insets=useSafeAreaInsets(),location=useCampusLocation();const isUniben=profile?.university_name?.toLowerCase()==='university of benin';
 const [campuses,setCampuses]=useState<Campus[]>(isUniben?unibenCampuses:[]),[campusId,setCampusId]=useState(isUniben?unibenCampuses[0]!.id:''),[places,setPlaces]=useState<CampusPlace[]>([]),[features,setFeatures]=useState<unknown>(emptyFeatures),[selectedId,setSelectedId]=useState<string|null>(null),[originId,setOriginId]=useState<string|null>(null),[choosingOrigin,setChoosingOrigin]=useState(false),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[route,setRoute]=useState<Route|null>(null),[routeBusy,setRouteBusy]=useState(false),[detail,setDetail]=useState<Detail|null>(null),[layer,setLayer]=useState('osm'),[focus,setFocus]=useState<MapPayload['focus']>(null),[offCampusDismissed,setOffCampusDismissed]=useState(false);
 const campus=campuses.find(c=>c.id===campusId),selected=places.find(p=>p.id===selectedId),origin=places.find(p=>p.id===originId);
 const centre=useMemo<[number,number]>(()=>campus?[Number(campus.longitude),Number(campus.latitude)]:[5.618838,6.398255],[campus]);
 const current=location.position,useCurrent=!originId;const live=useMemo<[number,number]|null>(()=>current?[current.longitude,current.latitude]:null,[current]);const from=origin&&origin.latitude&&origin.longitude?[Number(origin.longitude),Number(origin.latitude)] as [number,number]:live;
 const campusDistance=live?distance(live,centre):0,outside=campusDistance>1800;
 useEffect(()=>{let active=true;void api<{campuses:Campus[]}>('/v1/maps/campuses').then(r=>{if(!active)return;setCampuses(r.campuses);setCampusId(id=>r.campuses.some(c=>c.id===id)?id:r.campuses[0]?.id??'');}).catch(e=>{if(active){setError(e.message);if(isUniben){setCampuses(unibenCampuses);setCampusId(id=>id||unibenCampuses[0]!.id);}else setLoading(false);}});return()=>{active=false;};},[isUniben,profile?.university_id]);
 useEffect(()=>{if(!campusId)return;let active=true;const cacheKey=`k1.map.v2.${profile?.university_id}.${campusId}`;setLoading(true);setPlaces([]);setFeatures(emptyFeatures);setSelectedId(null);setOriginId(null);setQuery('');setRoute(null);setOffCampusDismissed(false);setError('');
  void AsyncStorage.getItem(cacheKey).then(text=>{if(active&&text){try{const saved=JSON.parse(text);if(Array.isArray(saved.places))setPlaces(saved.places);}catch{}}});
  void api<{places:CampusPlace[]}>(`/v1/maps/campuses/${campusId}/places`).then(r=>{if(active){setPlaces(r.places);void AsyncStorage.setItem(cacheKey,JSON.stringify(r)).catch(()=>{});}}).catch(e=>{if(active){setError(e.message);if(isUniben&&campusId===unibenCampuses[0]!.id)setPlaces(p=>p.length?p:UNIBEN_UGBOWO_FALLBACK);}}).finally(()=>{if(active)setLoading(false);});
  void api<unknown>(`/v1/maps/campuses/${campusId}/features`).then(r=>{if(active)setFeatures(r);}).catch(()=>{});return()=>{active=false;};
 },[campusId,profile?.university_id,isUniben]);
 useEffect(()=>{let active=true;setDetail(null);if(selectedId)void api<Detail>(`/v1/maps/places/${selectedId}`).then(r=>{if(active)setDetail(r);}).catch(()=>{});return()=>{active=false;};},[selectedId]);
 // Stable location buckets prevent expensive requests for every GPS observation.
 const originBucket=from?`${from[0].toFixed(4)},${from[1].toFixed(4)}`:'';
 useEffect(()=>{let active=true;setRoute(null);if(!selectedId||!from)return;if(useCurrent&&current&&(Date.now()-current.timestamp>60000||(current.accuracy??999)>100)){setError('A more accurate current location is needed for directions. Tap the location button to refresh.');return;}
  setRouteBusy(true);void api<Route>('/v1/maps/route',{method:'POST',body:JSON.stringify({campusId,origin:from,destinationId:selectedId})}).then(r=>{if(active){setRoute(r);setError('');}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setRouteBusy(false);});return()=>{active=false;};
 },[campusId,selectedId,originBucket,useCurrent]);
 const pick=useCallback((id:string)=>{const place=places.find(p=>p.id===id);if(!place)return;setSelectedId(id);setQuery(place.name);if(place.latitude!==null&&place.longitude!==null)setFocus({coordinate:[Number(place.longitude),Number(place.latitude)],nonce:Date.now()});},[places]);
 const mapError=useCallback((message:string)=>setError(message),[]);
 const payload=useMemo<MapPayload>(()=>({campusId,centre,places,features,selectedId,location:live,route:route?.geometry??null,layer,focus}),[campusId,centre,places,features,selectedId,live,route,layer,focus]);
 const locate=async()=>{setOriginId(null);setChoosingOrigin(false);const position=await location.requestLocation();if(position)setFocus({coordinate:[position.longitude,position.latitude],nonce:Date.now()});};
 const clear=()=>{setRoute(null);setSelectedId(null);setOriginId(null);setQuery('');setError('');setChoosingOrigin(false);};
 return <View style={styles.page}><CampusMapSurface payload={payload} onPick={pick} onError={mapError}/><View style={[styles.top,{top:insets.top+12}]}><View style={styles.campuses}>{campuses.map(c=><Pressable accessibilityRole="button" accessibilityState={{selected:c.id===campusId}} key={c.id} style={[styles.campus,c.id===campusId&&styles.campusSelected]} onPress={()=>setCampusId(c.id)}><Text style={[styles.campusText,c.id===campusId&&styles.campusTextSelected]}>{c.name.replace(/ campus/i,'')}</Text></Pressable>)}</View><View style={styles.layers}>{[['osm','map-outline'],['satellite','planet-outline'],['3d','cube-outline']].map(([id,icon])=><Pressable key={id} accessibilityRole="button" accessibilityLabel={id==='osm'?'Street map':id==='satellite'?'Satellite imagery':'3D mapped buildings'} accessibilityState={{selected:layer===id}} onPress={()=>setLayer(id!)} style={[styles.icon,layer===id&&styles.iconSelected]}><Ionicons name={icon as keyof typeof Ionicons.glyphMap} size={19} color={layer===id?'#fff':theme.deepBrand}/></Pressable>)}</View></View>
 {outside&&!offCampusDismissed?<View style={[styles.notice,{top:insets.top+70}]}><View style={{flex:1}}><Text style={styles.noticeTitle}>Outside {campus?.name.replace(/ campus/i,'')} campus</Text><Text style={styles.noticeText}>{(campusDistance/1000).toFixed(1)} km to the campus centre. Your location stays on the city map.</Text><Pressable onPress={()=>setFocus({coordinate:centre,nonce:Date.now()})}><Text style={styles.link}>View campus</Text></Pressable></View><Pressable accessibilityLabel="Dismiss campus notice" onPress={()=>setOffCampusDismissed(true)}><Ionicons name="close" size={22} color={theme.text}/></Pressable></View>:null}
 <View style={[styles.controls,{bottom:insets.bottom+196}]}><Pressable accessibilityLabel="View campus" style={styles.icon} onPress={()=>setFocus({coordinate:centre,nonce:Date.now()})}><Ionicons name="school-outline" size={22} color={theme.deepBrand}/></Pressable><Pressable accessibilityLabel="Use current location" style={styles.icon} onPress={()=>void locate()}><Ionicons name="locate-outline" size={22} color={theme.deepBrand}/></Pressable></View>
 {selected?<View style={[styles.placeCard,{bottom:insets.bottom+194}]}>{detail?.media[0]?<Image source={{uri:detail.media[0].url}} style={styles.placePhoto}/>:null}<View style={{flex:1,minWidth:0}}><Text numberOfLines={2} style={styles.placeName}>{selected.name}</Text><Text numberOfLines={2} style={styles.noticeText}>{routeBusy?'Finding a walking route…':route?.notice??selected.description??'Campus place'}</Text>{detail?.media[0]?<Text style={styles.credit}>{detail.media[0].attribution}</Text>:null}<Pressable onPress={()=>setChoosingOrigin(v=>!v)}><Text style={styles.link}>{choosingOrigin?'Choose a start below':'Choose a different start'}</Text></Pressable></View><Pressable accessibilityLabel="Close place" onPress={clear}><Ionicons name="close" size={21} color={theme.text}/></Pressable></View>:null}
 <CampusMapDrawer campusId={campusId} bottomInset={insets.bottom+88} choosingOrigin={choosingOrigin} destinationName={selected?.name} error={error} loading={loading} places={places} query={query} route={route?{distanceMetres:route.distanceMetres,originName:origin?.name??'Current location',destinationName:selected?.name??''}:null} locationAccuracy={current?.accuracy??null} locationError={location.error} locationLoading={location.loading} locationPermission={location.permission} onClearRoute={clear} onPickDestination={pick} onPickOrigin={id=>{setOriginId(id);setChoosingOrigin(false);}} onQueryChange={setQuery} onUseCurrentLocation={()=>void locate()}/>
 </View>;
}
const makeStyles=(theme:Theme)=>StyleSheet.create({page:{flex:1,backgroundColor:theme.surfaceMuted},top:{position:'absolute',left:12,right:12,flexDirection:'row',gap:8,justifyContent:'space-between'},campuses:{flexDirection:'row',gap:3,padding:4,borderRadius:24,backgroundColor:theme.surface,elevation:3,flexShrink:1},campus:{paddingVertical:10,paddingHorizontal:13,borderRadius:20},campusSelected:{backgroundColor:theme.deepBrand},campusText:{fontFamily:theme.font.semibold,color:theme.text,fontSize:13},campusTextSelected:{color:'#fff'},layers:{flexDirection:'row',gap:5},icon:{width:42,height:42,borderRadius:21,backgroundColor:theme.surface,alignItems:'center',justifyContent:'center',elevation:3},iconSelected:{backgroundColor:theme.deepBrand},controls:{position:'absolute',right:12,gap:9},notice:{position:'absolute',left:12,right:12,backgroundColor:theme.surface,borderRadius:15,padding:12,flexDirection:'row',gap:12,elevation:3},noticeTitle:{fontFamily:theme.font.semibold,fontSize:13,color:theme.text},noticeText:{fontFamily:theme.font.body,fontSize:12,lineHeight:18,color:theme.textMuted},link:{fontFamily:theme.font.semibold,fontSize:12,color:theme.deepBrand,paddingTop:7},placeCard:{position:'absolute',left:12,right:65,borderRadius:18,backgroundColor:theme.surface,padding:12,flexDirection:'row',gap:9,elevation:4},placePhoto:{width:62,height:72,borderRadius:10},placeName:{fontFamily:theme.font.semibold,fontSize:14,color:theme.text},credit:{fontFamily:theme.font.body,fontSize:9,color:theme.textMuted}});
