import {Hono} from 'hono';
import {sql} from 'drizzle-orm';
import {z} from '@kampusone/contracts';
import {currentUser,requireAuth} from '../middleware/auth';
import {database,firstRow} from '../lib/database';
import {resolveAdminScope} from '../lib/admin-access';
import {recordAudit} from '../lib/audit';
import {id,input} from '../lib/input';
import {AppError} from '../lib/errors';
import type {Bindings,Variables} from '../types';
export const mapCaptureRoutes=new Hono<{Bindings:Bindings;Variables:Variables}>();
mapCaptureRoutes.use('/*',requireAuth);
async function reviewer(campusId:string,env:Bindings,user:ReturnType<typeof currentUser>){const row=firstRow(await database(env).execute<{id:string;institution_id:string}>(sql`select id,institution_id from public.institution_campuses where id=${campusId}::uuid`));if(!row)throw new AppError(404,'NOT_FOUND','Campus not found.');await resolveAdminScope(env,user,row.institution_id,'universities.manage');return row;}
async function agent(env:Bindings,user:ReturnType<typeof currentUser>){if(!firstRow(await database(env).execute(sql`select id from public.agent_profiles where user_id=${user.id}::uuid and university_id=${user.universityId}::uuid and status='ACTIVE' limit 1`)))throw new AppError(403,'FORBIDDEN','Campus capture requires an approved campus agent account.');}
mapCaptureRoutes.get('/missions',async c=>{const user=currentUser(c);await agent(c.env,user);const result=await database(c.env).execute(sql`select m.id,m.title,m.kind,m.status,m.place_id,p.name place_name,c.name campus_name,m.campus_id from app_private.map_capture_missions m join public.institution_campuses c on c.id=m.campus_id left join public.campus_places p on p.id=m.place_id left join app_private.campus_map_controls ctrl on ctrl.campus_id=c.id where m.institution_id=${user.universityId}::uuid and m.assigned_user_id=${user.id}::uuid and m.status='OPEN' and coalesce(ctrl.capture_enabled,true) order by m.created_at limit 100`);return c.json({missions:result.rows});});
mapCaptureRoutes.post('/missions/:id/submissions',async c=>{
 const user=currentUser(c);await agent(c.env,user);const missionId=id(c.req.param('id')),data=await input(c,z.object({id:z.string().uuid(),mediaId:z.string().uuid(),latitude:z.number().min(-90).max(90),longitude:z.number().min(-180).max(180),accuracyMetres:z.number().min(0).max(50),heading:z.number().min(0).max(360).nullable(),capturedAt:z.iso.datetime(),notes:z.string().trim().max(1000)}).strict());
 if(Math.abs(Date.now()-new Date(data.capturedAt).getTime())>15*60*1000)throw new AppError(422,'BAD_REQUEST','Capture a new photo with a fresh location before submitting.');
 const saved=firstRow(await database(c.env).execute(sql`insert into app_private.map_capture_submissions(id,mission_id,institution_id,user_id,media_id,latitude,longitude,accuracy_metres,heading,captured_at,notes)
 select ${data.id}::uuid,m.id,m.institution_id,${user.id}::uuid,media.id,${data.latitude},${data.longitude},${data.accuracyMetres},${data.heading},${data.capturedAt}::timestamptz,${data.notes} from app_private.map_capture_missions m join public.media_objects media on media.id=${data.mediaId}::uuid and media.owner_user_id=${user.id}::uuid and media.kind='map-capture' and media.institution_id=m.institution_id left join app_private.campus_map_controls ctrl on ctrl.campus_id=m.campus_id where m.id=${missionId}::uuid and m.assigned_user_id=${user.id}::uuid and m.institution_id=${user.universityId}::uuid and m.status='OPEN' and coalesce(ctrl.capture_enabled,true) on conflict(id) do nothing returning id,status`));
 if(saved)return c.json(saved,201);const previous=firstRow(await database(c.env).execute(sql`select id,status from app_private.map_capture_submissions where id=${data.id}::uuid and mission_id=${missionId}::uuid and user_id=${user.id}::uuid and media_id=${data.mediaId}::uuid`));if(previous)return c.json(previous);throw new AppError(409,'CONFLICT','This mission is unavailable or the photo does not belong to you.');
});
mapCaptureRoutes.post('/admin/missions',async c=>{const data=await input(c,z.object({id:z.string().uuid(),campusId:z.string().uuid(),placeId:z.string().uuid(),assignedUserId:z.string().uuid(),title:z.string().trim().min(3).max(180),kind:z.enum(['PHOTO','ENTRANCE','PATH_CHECK','ACCESSIBILITY'])}).strict()),user=currentUser(c),row=await reviewer(data.campusId,c.env,user);
 const result=firstRow(await database(c.env).execute(sql`insert into app_private.map_capture_missions(id,institution_id,campus_id,place_id,title,kind,assigned_user_id,created_by) select ${data.id}::uuid,${row.institution_id}::uuid,${row.id}::uuid,p.id,${data.title},${data.kind},a.user_id,${user.id}::uuid from public.campus_places p join public.agent_profiles a on a.user_id=${data.assignedUserId}::uuid and a.university_id=p.university_id and a.status='ACTIVE' where p.id=${data.placeId}::uuid and p.campus_id=${row.id}::uuid and p.university_id=${row.institution_id}::uuid limit 1 on conflict(id) do nothing returning id`));if(!result)throw new AppError(422,'BAD_REQUEST','Choose a place and an approved agent from this campus university.');await recordAudit(c.env,{actorUserId:user.id,universityId:row.institution_id,action:'maps.mission.created',targetType:'map_mission',targetId:data.id,requestId:c.get('requestId')});return c.json(result,201);
});
mapCaptureRoutes.get('/admin/campuses/:id',async c=>{const row=await reviewer(id(c.req.param('id')),c.env,currentUser(c));const[agents,submissions,controls]=await Promise.all([database(c.env).execute(sql`select distinct a.user_id,p.display_name from public.agent_profiles a join public.profiles p on p.user_id=a.user_id where a.university_id=${row.institution_id}::uuid and a.status='ACTIVE' and p.deleted_at is null order by p.display_name limit 200`),database(c.env).execute(sql`select s.id,s.media_id,s.accuracy_metres,s.latitude,s.longitude,s.heading,s.notes,s.captured_at,s.status,m.title,m.kind,p.name place_name from app_private.map_capture_submissions s join app_private.map_capture_missions m on m.id=s.mission_id left join public.campus_places p on p.id=m.place_id where m.campus_id=${row.id}::uuid and s.institution_id=${row.institution_id}::uuid and s.status='PENDING' order by s.created_at limit 100`),database(c.env).execute(sql`select three_d_enabled,satellite_enabled,capture_enabled from app_private.campus_map_controls where campus_id=${row.id}::uuid`)]);return c.json({agents:agents.rows,submissions:submissions.rows,controls:controls.rows[0]??{three_d_enabled:true,satellite_enabled:false,capture_enabled:true},satelliteConfigured:Boolean(c.env.MAP_SATELLITE_TILE_URL&&c.env.MAP_SATELLITE_ATTRIBUTION)});});
mapCaptureRoutes.put('/admin/campuses/:id/controls',async c=>{const row=await reviewer(id(c.req.param('id')),c.env,currentUser(c)),data=await input(c,z.object({threeD:z.boolean(),satellite:z.boolean(),capture:z.boolean()}).strict());if(data.satellite&&(!c.env.MAP_SATELLITE_TILE_URL||!c.env.MAP_SATELLITE_ATTRIBUTION))throw new AppError(422,'BAD_REQUEST','Configure an approved imagery tile URL and attribution before enabling satellite.');await database(c.env).execute(sql`insert into app_private.campus_map_controls(campus_id,three_d_enabled,satellite_enabled,capture_enabled,updated_by) values(${row.id}::uuid,${data.threeD},${data.satellite},${data.capture},${currentUser(c).id}::uuid) on conflict(campus_id) do update set three_d_enabled=excluded.three_d_enabled,satellite_enabled=excluded.satellite_enabled,capture_enabled=excluded.capture_enabled,updated_by=excluded.updated_by,updated_at=now()`);await recordAudit(c.env,{actorUserId:currentUser(c).id,universityId:row.institution_id,action:'maps.controls.changed',targetType:'campus',targetId:row.id,metadata:data,requestId:c.get('requestId')});return c.json({status:'saved'});});
mapCaptureRoutes.post('/admin/submissions/:id/decision',async c=>{const submissionId=id(c.req.param('id')),data=await input(c,z.object({approve:z.boolean(),note:z.string().trim().min(3).max(1000)}).strict()),row=firstRow(await database(c.env).execute<{campus_id:string}>(sql`select m.campus_id from app_private.map_capture_submissions s join app_private.map_capture_missions m on m.id=s.mission_id where s.id=${submissionId}::uuid`));if(!row)throw new AppError(404,'NOT_FOUND','Capture not found.');await reviewer(row.campus_id,c.env,currentUser(c));try{await database(c.env).execute(sql`select app_private.review_map_capture(${submissionId}::uuid,${currentUser(c).id}::uuid,${data.approve},${data.note})`);}catch(e){if(e instanceof Error&&e.message.includes('MAP_'))throw new AppError(409,'CONFLICT','This capture or mission has already been reviewed. Refresh the queue.');throw e;}return c.json({status:'saved'});});
