import {Hono,type Context} from 'hono';
import {sql} from 'drizzle-orm';
import {z} from '@kampusone/contracts';
import {currentUser,requireAuth} from '../middleware/auth';
import {database,firstRow} from '../lib/database';
import {AppError} from '../lib/errors';
import {id,input} from '../lib/input';
import {resolveAdminScope} from '../lib/admin-access';
import {recordAudit} from '../lib/audit';
import {walkingRoute,type WalkPath} from '../lib/campus-routing';
import {discoverCampus,osmGeometry} from '../lib/map-provider';
import type {Bindings,Variables} from '../types';
function buildingHeight(tags:Record<string,unknown>){const height=Number(String(tags.height??'').replace(/\s*m$/,''));if(Number.isFinite(height)&&height>0&&height<300)return height;const levels=Number(tags['building:levels']);return Number.isFinite(levels)&&levels>0&&levels<80?levels*3:0;}
export const mapRoutes=new Hono<{Bindings:Bindings;Variables:Variables}>();
mapRoutes.use('/*',requireAuth);
type Campus={id:string;institution_id:string;name:string;slug:string;latitude:string|null;longitude:string|null;status:string;boundary:unknown;map_revision:number};
async function campus(env:Bindings,campusId:string,universityId:string|null,admin=false){
 const row=firstRow(await database(env).execute<Campus>(sql`select id,institution_id,name,slug,latitude,longitude,status,ST_AsGeoJSON(boundary)::jsonb as boundary,map_revision from public.institution_campuses where id=${campusId}::uuid and (${admin} or status='PUBLISHED') and (${admin} or institution_id=${universityId}::uuid)`));
 if(!row)throw new AppError(404,'NOT_FOUND','Campus not found.');return row;
}
mapRoutes.get('/campuses',async c=>{const user=currentUser(c);const rows=await database(c.env).execute(sql`select id,name,slug,latitude,longitude,status,map_revision from public.institution_campuses where institution_id=${user.universityId}::uuid and status='PUBLISHED' order by case when slug='ugbowo' then 0 else 1 end,name`);return c.json({campuses:rows.rows});});
mapRoutes.get('/campuses/:id',async c=>{
 const row=await campus(c.env,id(c.req.param('id')),currentUser(c).universityId);
 const counts=firstRow(await database(c.env).execute<{paths:number;photos:number;heights:number;three_d_enabled:boolean;satellite_enabled:boolean}>(sql`select (select count(*)::int from public.campus_paths where campus_id=${row.id}::uuid and not closed) paths,(select count(*)::int from public.campus_place_media where campus_id=${row.id}::uuid and moderation_state='APPROVED') photos,(select count(*)::int from public.campus_map_features where campus_id=${row.id}::uuid and (tags ? 'height' or tags ? 'building:levels')) heights,coalesce(mc.three_d_enabled,true) three_d_enabled,coalesce(mc.satellite_enabled,false) satellite_enabled from public.institution_campuses c left join app_private.campus_map_controls mc on mc.campus_id=c.id where c.id=${row.id}::uuid`));
 const satellite=counts?.satellite_enabled&&c.env.MAP_SATELLITE_TILE_URL?.startsWith('https://')&&c.env.MAP_SATELLITE_ATTRIBUTION?{url:c.env.MAP_SATELLITE_TILE_URL,attribution:c.env.MAP_SATELLITE_ATTRIBUTION}:null;
 return c.json({...row,capabilities:{walkingRoutes:Boolean(counts?.paths),placePhotos:Boolean(counts?.photos),satellite:Boolean(satellite),threeD:Boolean(counts?.three_d_enabled&&counts?.heights)},satellite,attribution:'© OpenStreetMap contributors'});
});
mapRoutes.get('/campuses/:id/places',async c=>{const row=await campus(c.env,id(c.req.param('id')),currentUser(c).universityId);const query=(c.req.query('q')??'').trim().toLowerCase().slice(0,120);const result=await database(c.env).execute(sql`select id,name,category,description,latitude,longitude,accessibility_notes,image_url,verified_at,search_aliases,parent_place_id,floor_label,room_label,source_provider,source_url,confidence,ST_AsGeoJSON(geom)::jsonb geometry from public.campus_places where campus_id=${row.id}::uuid and university_id=${row.institution_id}::uuid and status='PUBLISHED' and (${query}='' or concat_ws(' ',name,description,array_to_string(search_aliases,' ')) ilike ${'%'+query+'%'}) order by name limit 1000`);return c.json({campus:row,places:result.rows});});
mapRoutes.get('/campuses/:id/features',async c=>{const row=await campus(c.env,id(c.req.param('id')),currentUser(c).universityId);const features=await database(c.env).execute(sql`select id,kind,tags,ST_AsGeoJSON(geom)::jsonb geometry from public.campus_map_features where campus_id=${row.id}::uuid and institution_id=${row.institution_id}::uuid limit 5000`);return c.json({type:'FeatureCollection',features:features.rows.map(r=>({type:'Feature',id:r.id,geometry:r.geometry,properties:{kind:r.kind,...r.tags as Record<string,unknown>,heightMetres:buildingHeight(r.tags as Record<string,unknown>)}}))});});
mapRoutes.get('/places/:id',async c=>{const user=currentUser(c),placeId=id(c.req.param('id'));const place=firstRow(await database(c.env).execute(sql`select p.*,ST_AsGeoJSON(p.geom)::jsonb geometry from public.campus_places p join public.institution_campuses c on c.id=p.campus_id where p.id=${placeId}::uuid and p.university_id=${user.universityId}::uuid and p.status='PUBLISHED' and c.status='PUBLISHED'`));if(!place)throw new AppError(404,'NOT_FOUND','Place not found.');const [entrances,media]=await Promise.all([database(c.env).execute(sql`select id,label,wheelchair,preferred,verified_at,ST_AsGeoJSON(geom)::jsonb geometry from public.campus_entrances where place_id=${placeId}::uuid and institution_id=${user.universityId}::uuid order by preferred desc`),database(c.env).execute(sql`select id,url,media_id,source_provider,source_url,attribution,captured_at,verified_at from public.campus_place_media where place_id=${placeId}::uuid and institution_id=${user.universityId}::uuid and moderation_state='APPROVED' order by captured_at desc nulls last`)]);return c.json({place,entrances:entrances.rows,media:media.rows.map(r=>({...r,url:r.media_id?`${c.env.PUBLIC_API_ORIGIN??new URL(c.req.url).origin}/v1/media/${r.media_id}`:r.url}))});});
const coordinate=z.tuple([z.number().min(-180).max(180),z.number().min(-90).max(90)]);
mapRoutes.post('/route',async c=>{const user=currentUser(c),data=await input(c,z.object({campusId:z.string().uuid(),origin:coordinate,destinationId:z.string().uuid(),accessible:z.boolean().default(false)}).strict()),row=await campus(c.env,data.campusId,user.universityId);const destination=firstRow(await database(c.env).execute<{longitude:number;latitude:number;name:string;endpoint_name:string;depth:number;verified:boolean}>(sql`
 with recursive ancestry as(
  select p.id,p.parent_place_id,p.name,p.longitude,p.latitude,0 depth from public.campus_places p where p.id=${data.destinationId}::uuid and p.campus_id=${row.id}::uuid and p.university_id=${row.institution_id}::uuid and p.status='PUBLISHED'
  union all select p.id,p.parent_place_id,p.name,p.longitude,p.latitude,a.depth+1 from public.campus_places p join ancestry a on p.id=a.parent_place_id where p.campus_id=${row.id}::uuid and p.university_id=${row.institution_id}::uuid and p.status='PUBLISHED'and a.depth<8
 ) select coalesce(ST_X(e.geom),p.longitude)::float8 longitude,coalesce(ST_Y(e.geom),p.latitude)::float8 latitude,(select name from ancestry where depth=0)name,p.name endpoint_name,p.depth,(e.verified_at is not null)verified from ancestry p
 left join lateral(select geom,verified_at from public.campus_entrances where place_id=p.id and institution_id=${row.institution_id}::uuid and preferred and verified_at is not null order by verified_at desc limit 1)e on true
 where e.geom is not null or(p.longitude is not null and p.latitude is not null) order by(e.verified_at is not null)desc,p.depth desc limit 1`));if(!destination||destination.latitude===null||destination.longitude===null)throw new AppError(422,'BAD_REQUEST','This place needs its entrance mapped before directions can be shown.');const paths=(await database(c.env).execute<WalkPath>(sql`select node_ids,ST_AsGeoJSON(geom)::jsonb geometry,name,access,steps,wheelchair,closed from public.campus_paths where campus_id=${row.id}::uuid and institution_id=${row.institution_id}::uuid limit 5000`)).rows;const route=walkingRoute(paths,data.origin,[destination.longitude,destination.latitude],data.accessible);if(!route)throw new AppError(422,'BAD_REQUEST','No mapped walking route connects these points yet. Choose a nearby mapped entrance, or view the place on the map.');return c.json({...route,destinationName:destination.name,endpointVerified:destination.verified,notice:destination.depth>0?`Directions end at ${destination.endpoint_name}. Follow the building’s signs to ${destination.name}.`:destination.verified?null:'Directions end near the mapped place. The entrance still needs verification.'});});

async function adminCampus(campusId:string,c:Context<{Bindings:Bindings;Variables:Variables}>){const row=await campus(c.env,campusId,null,true);await resolveAdminScope(c.env,currentUser(c),row.institution_id,'universities.manage');return row;}
mapRoutes.post('/admin/imports',async c=>{const data=await input(c,z.object({campusId:z.string().uuid(),requestKey:z.string().min(8).max(120)}).strict()),row=await adminCampus(data.campusId,c),user=currentUser(c);if(!row.latitude||!row.longitude)throw new AppError(422,'BAD_REQUEST','Set a sourced campus centre before discovering features.');const db=database(c.env);const job=firstRow(await db.execute<{id:string;status:string}>(sql`insert into app_private.map_imports(institution_id,campus_id,actor_user_id,request_key) values(${row.institution_id}::uuid,${row.id}::uuid,${user.id}::uuid,${data.requestKey}) on conflict(campus_id,request_key) do nothing returning id,status`));if(!job){return c.json(firstRow(await db.execute(sql`select id,status,diagnostics from app_private.map_imports where campus_id=${row.id}::uuid and request_key=${data.requestKey}`)));}
 c.executionCtx.waitUntil((async()=>{try{const result=await discoverCampus(Number(row.latitude),Number(row.longitude));const records=result.elements.flatMap(element=>{const tags=element.tags??{},geometry=osmGeometry(element);if(!geometry)return [];const kind=tags.highway?'PATH':tags.entrance?'ENTRANCE':tags.landuse==='education'?'BOUNDARY':'PLACE';if(kind==='PATH'&&geometry.type==='Polygon'){geometry.type='LineString';geometry.coordinates=geometry.coordinates[0] as number[][];}if(kind==='PATH'&&geometry.type!=='LineString')return [];return [{source_feature_id:element.type+'/'+element.id,feature_kind:kind,name:tags.name??null,geometry,tags:{...tags,node_ids:element.nodes?.map(String)??[]}}];}).slice(0,5000);
 for(let start=0;start<records.length;start+=500){await db.execute(sql`insert into app_private.map_candidates(institution_id,campus_id,import_id,source_provider,source_feature_id,feature_kind,name,geometry,tags,matched_place_id)
 select ${row.institution_id}::uuid,${row.id}::uuid,${job.id}::uuid,'OSM',v.source_feature_id,v.feature_kind,v.name,v.geometry,v.tags,p.id from jsonb_to_recordset(${JSON.stringify(records.slice(start,start+500))}::jsonb) v(source_feature_id text,feature_kind text,name text,geometry jsonb,tags jsonb)
 left join lateral(select id from public.campus_places where campus_id=${row.id}::uuid and (lower(name)=lower(v.name) or lower(v.name)=any(select lower(a) from unnest(search_aliases)a)) limit 1)p on true
 on conflict(campus_id,source_provider,source_feature_id,feature_kind) do update set import_id=excluded.import_id,geometry=excluded.geometry,tags=excluded.tags where map_candidates.status='PENDING'`);}
 const candidates=records.length;
 await db.execute(sql`update app_private.map_imports set status='REVIEW',source_url=${result.sourceUrl},diagnostics=${JSON.stringify({fetched:result.elements.length,candidates})}::jsonb,completed_at=now() where id=${job.id}::uuid`);
 }catch(error){await db.execute(sql`update app_private.map_imports set status='FAILED',diagnostics=${JSON.stringify({error:error instanceof Error?error.message:'Discovery failed'})}::jsonb,completed_at=now() where id=${job.id}::uuid`);}})());
 await recordAudit(c.env,{actorUserId:user.id,universityId:row.institution_id,action:'maps.import.started',targetType:'campus',targetId:row.id,requestId:c.get('requestId')});return c.json(job,202);
});
mapRoutes.get('/admin/campuses/:id/review',async c=>{const row=await adminCampus(id(c.req.param('id')),c);const[jobs,candidates,missions]=await Promise.all([database(c.env).execute(sql`select id,status,diagnostics,created_at from app_private.map_imports where campus_id=${row.id}::uuid order by created_at desc limit 20`),database(c.env).execute(sql`select id,feature_kind,name,source_feature_id,geometry,tags,matched_place_id,status from app_private.map_candidates where campus_id=${row.id}::uuid and status='PENDING' order by feature_kind,name nulls last limit 500`),database(c.env).execute(sql`select id,title,kind,status,assigned_user_id,place_id from app_private.map_capture_missions where campus_id=${row.id}::uuid order by created_at desc limit 100`)]);return c.json({campus:row,imports:jobs.rows,candidates:candidates.rows,missions:missions.rows});});
mapRoutes.post('/admin/candidates/:id/decision',async c=>{const candidateId=id(c.req.param('id')),data=await input(c,z.object({decision:z.enum(['APPROVE','MERGE','REJECT']),placeId:z.string().uuid().optional(),name:z.string().trim().min(2).max(180).optional(),note:z.string().trim().min(3).max(1000)}).strict());const db=database(c.env),candidate=firstRow(await db.execute<{campus_id:string;institution_id:string;source_feature_id:string;feature_kind:string;geometry:{type:string;coordinates:unknown};tags:Record<string,unknown>;name:string|null;matched_place_id:string|null;status:string}>(sql`select * from app_private.map_candidates where id=${candidateId}::uuid`));if(!candidate)throw new AppError(404,'NOT_FOUND','Candidate not found.');await adminCampus(candidate.campus_id,c);if(candidate.status!=='PENDING')throw new AppError(409,'CONFLICT','This candidate has already been reviewed.');try{await db.execute(sql`select app_private.review_map_candidate(${candidateId}::uuid,${currentUser(c).id}::uuid,${data.decision},${data.placeId??null}::uuid,${data.name??null},${data.note})`);}catch(error){if(error instanceof Error&&error.message.includes('MAP_'))throw new AppError(409,'CONFLICT',error.message.includes('ALREADY_REVIEWED')?'This candidate has already been reviewed. Refresh the list.':'Check the geometry, campus and place match before approving this candidate.');throw error;}
 await recordAudit(c.env,{actorUserId:currentUser(c).id,universityId:candidate.institution_id,action:'maps.candidate.'+data.decision.toLowerCase(),targetType:'map_candidate',targetId:candidateId,requestId:c.get('requestId')});return c.json({status:'saved'});
});
