import {Hono,type Context} from 'hono';
import {sql} from 'drizzle-orm';
import {z} from '@kampusone/contracts';
import {currentUser,requireAuth} from '../middleware/auth';
import {database,firstRow} from '../lib/database';
import {AppError} from '../lib/errors';
import {id,input} from '../lib/input';
import {resolveAdminScope} from '../lib/admin-access';
import {recordAudit} from '../lib/audit';
import {walkingRoute,type WalkPath} from '../lib/campus-routing';
import {discoverCampus,osmGeometry} from '../lib/map-provider';
import type {Bindings,Variables} from '../types';
export const mapRoutes=new Hono<{Bindings:Bindings;Variables:Variables}>();
mapRoutes.use('/*',requireAuth);
type Campus={id:string;institution_id:string;name:string;slug:string;latitude:string|null;longitude:string|null;status:string;boundary:unknown;map_revision:number};
async function campus(env:Bindings,campusId:string,universityId:string|null,admin=false){
 const row=firstRow(await database(env).execute<Campus>(sql`select id,institution_id,name,slug,latitude,longitude,status,ST_AsGeoJSON(boundary)::jsonb as boundary,map_revision from public.institution_campuses where id=${campusId}::uuid and (${admin} or status='PUBLISHED') and (${admin} or institution_id=${universityId}::uuid)`));
 if(!row)throw new AppError(404,'NOT_FOUND','Campus not found.');return row;
}
mapRoutes.get('/campuses',async c=>{const user=currentUser(c);const rows=await database(c.env).execute(sql`select id,name,slug,latitude,longitude,status,map_revision from public.institution_campuses where institution_id=${user.universityId}::uuid and status='PUBLISHED' order by case when slug='ugbowo' then 0 else 1 end,name`);return c.json({campuses:rows.rows});});
mapRoutes.get('/campuses/:id',async c=>{const row=await campus(c.env,id(c.req.param('id')),currentUser(c).universityId);const counts=firstRow(await database(c.env).execute<{paths:number;photos:number}>(sql`select (select count(*)::int from public.campus_paths where campus_id=${row.id}::uuid and not closed) paths,(select count(*)::int from public.campus_place_media where campus_id=${row.id}::uuid and moderation_state='APPROVED') photos`));return c.json({...row,capabilities:{walkingRoutes:Boolean(counts?.paths),placePhotos:Boolean(counts?.photos),satellite:true,threeD:false},attribution:'© OpenStreetMap contributors'});});
mapRoutes.get('/campuses/:id/places',async c=>{const row=await campus(c.env,id(c.req.param('id')),currentUser(c).universityId);const query=(c.req.query('q')??'').trim().toLowerCase().slice(0,120);const result=await database(c.env).execute(sql`select id,name,category,description,latitude,longitude,accessibility_notes,image_url,verified_at,search_aliases,parent_place_id,floor_label,room_label,source_provider,source_url,confidence,ST_AsGeoJSON(geom)::jsonb geometry from public.campus_places where campus_id=${row.id}::uuid and university_id=${row.institution_id}::uuid and status='PUBLISHED' and (${query}='' or concat_ws(' ',name,description,array_to_string(search_aliases,' ')) ilike ${'%'+query+'%'}) order by name limit 1000`);return c.json({campus:row,places:result.rows});});
mapRoutes.get('/campuses/:id/features',async c=>{const row=await campus(c.env,id(c.req.param('id')),currentUser(c).universityId);const features=await database(c.env).execute(sql`select id,kind,tags,ST_AsGeoJSON(geom)::jsonb geometry from public.campus_map_features where campus_id=${row.id}::uuid and institution_id=${row.institution_id}::uuid limit 5000`);return c.json({type:'FeatureCollection',features:features.rows.map(r=>({type:'Feature',id:r.id,geometry:r.geometry,properties:{kind:r.kind,...r.tags as Record<string,unknown>}}))});});
mapRoutes.get('/places/:id',async c=>{const user=currentUser(c),placeId=id(c.req.param('id'));const place=firstRow(await database(c.env).execute(sql`select p.*,ST_AsGeoJSON(p.geom)::jsonb geometry from public.campus_places p join public.institution_campuses c on c.id=p.campus_id where p.id=${placeId}::uuid and p.university_id=${user.universityId}::uuid and p.status='PUBLISHED' and c.status='PUBLISHED'`));if(!place)throw new AppError(404,'NOT_FOUND','Place not found.');const [entrances,media]=await Promise.all([database(c.env).execute(sql`select id,label,wheelchair,preferred,verified_at,ST_AsGeoJSON(geom)::jsonb geometry from public.campus_entrances where place_id=${placeId}::uuid and institution_id=${user.universityId}::uuid order by preferred desc`),database(c.env).execute(sql`select id,url,source_provider,source_url,attribution,captured_at,verified_at from public.campus_place_media where place_id=${placeId}::uuid and institution_id=${user.universityId}::uuid and moderation_state='APPROVED' order by captured_at desc nulls last`)]);return c.json({place,entrances:entrances.rows,media:media.rows});});
const coordinate=z.tuple([z.number().min(-180).max(180),z.number().min(-90).max(90)]);
mapRoutes.post('/route',async c=>{const user=currentUser(c),data=await input(c,z.object({campusId:z.string().uuid(),origin:coordinate,destinationId:z.string().uuid(),accessible:z.boolean().default(false)}).strict()),row=await campus(c.env,data.campusId,user.universityId);const destination=firstRow(await database(c.env).execute<{longitude:number;latitude:number;name:string;verified:boolean}>(sql`select coalesce(ST_X(e.geom),p.longitude)::float8 longitude,coalesce(ST_Y(e.geom),p.latitude)::float8 latitude,p.name,(e.verified_at is not null) verified from public.campus_places p left join lateral(select geom,verified_at from public.campus_entrances where place_id=p.id and preferred=true and verified_at is not null limit 1)e on true where p.id=${data.destinationId}::uuid and p.campus_id=${row.id}::uuid and p.status='PUBLISHED'`));if(!destination||destination.latitude===null||destination.longitude===null)throw new AppError(422,'BAD_REQUEST','This place needs its entrance mapped before directions can be shown.');const paths=(await database(c.env).execute<WalkPath>(sql`select node_ids,ST_AsGeoJSON(geom)::jsonb geometry,name,access,steps,wheelchair,closed from public.campus_paths where campus_id=${row.id}::uuid and institution_id=${row.institution_id}::uuid limit 5000`)).rows;const route=walkingRoute(paths,data.origin,[destination.longitude,destination.latitude],data.accessible);if(!route)throw new AppError(422,'BAD_REQUEST','No verified walking route connects these points yet. Choose a nearby mapped entrance, or view the place on the map.');return c.json({...route,destinationName:destination.name,endpointVerified:destination.verified,notice:destination.verified?null:'Directions end near the mapped place. The entrance still needs verification.'});});

async function adminCampus(campusId:string,c:Context<{Bindings:Bindings;Variables:Variables}>){const row=await campus(c.env,campusId,null,true);await resolveAdminScope(c.env,currentUser(c),row.institution_id,'universities.manage');return row;}
mapRoutes.post('/admin/imports',async c=>{const data=await input(c,z.object({campusId:z.string().uuid(),requestKey:z.string().min(8).max(120)}).strict()),row=await adminCampus(data.campusId,c),user=currentUser(c);if(!row.latitude||!row.longitude)throw new AppError(422,'BAD_REQUEST','Set a sourced campus centre before discovering features.');const db=database(c.env);const job=firstRow(await db.execute<{id:string;status:string}>(sql`insert into app_private.map_imports(institution_id,campus_id,actor_user_id,request_key) values(${row.institution_id}::uuid,${row.id}::uuid,${user.id}::uuid,${data.requestKey}) on conflict(campus_id,request_key) do nothing returning id,status`));if(!job){return c.json(firstRow(await db.execute(sql`select id,status,diagnostics from app_private.map_imports where campus_id=${row.id}::uuid and request_key=${data.requestKey}`)));}
 c.executionCtx.waitUntil((async()=>{try{const result=await discoverCampus(Number(row.latitude),Number(row.longitude));let candidates=0;for(const element of result.elements){const tags=element.tags??{},geometry=osmGeometry(element);if(!geometry)continue;const featureKind=tags.highway?'PATH':tags.entrance?'ENTRANCE':tags.landuse==='education'?'BOUNDARY':'PLACE';if(featureKind==='PATH'&&geometry.type!=='LineString') {if(geometry.type==='Polygon'){geometry.type='LineString';geometry.coordinates=geometry.coordinates[0] as number[][];}else continue;}
 const match=tags.name?firstRow(await db.execute<{id:string}>(sql`select id from public.campus_places where campus_id=${row.id}::uuid and (lower(name)=lower(${tags.name}) or lower(${tags.name})=any(select lower(a) from unnest(search_aliases)a)) limit 1`)):null;
 await db.execute(sql`insert into app_private.map_candidates(institution_id,campus_id,import_id,source_provider,source_feature_id,feature_kind,name,geometry,tags,matched_place_id) values(${row.institution_id}::uuid,${row.id}::uuid,${job.id}::uuid,'OSM',${element.type+'/'+element.id},${featureKind},${tags.name??null},${JSON.stringify(geometry)}::jsonb,${JSON.stringify({...tags,node_ids:element.nodes?.map(String)??[]})}::jsonb,${match?.id??null}::uuid) on conflict(campus_id,source_provider,source_feature_id,feature_kind) do update set import_id=excluded.import_id,geometry=excluded.geometry,tags=excluded.tags where map_candidates.status='PENDING'`);candidates++;}
 await db.execute(sql`update app_private.map_imports set status='REVIEW',source_url=${result.sourceUrl},diagnostics=${JSON.stringify({fetched:result.elements.length,candidates})}::jsonb,completed_at=now() where id=${job.id}::uuid`);
 }catch(error){await db.execute(sql`update app_private.map_imports set status='FAILED',diagnostics=${JSON.stringify({error:error instanceof Error?error.message:'Discovery failed'})}::jsonb,completed_at=now() where id=${job.id}::uuid`);}})());
 await recordAudit(c.env,{actorUserId:user.id,universityId:row.institution_id,action:'maps.import.started',targetType:'campus',targetId:row.id,requestId:c.get('requestId')});return c.json(job,202);
});
mapRoutes.get('/admin/campuses/:id/review',async c=>{const row=await adminCampus(id(c.req.param('id')),c);const[jobs,candidates,missions]=await Promise.all([database(c.env).execute(sql`select id,status,diagnostics,created_at from app_private.map_imports where campus_id=${row.id}::uuid order by created_at desc limit 20`),database(c.env).execute(sql`select id,feature_kind,name,source_feature_id,geometry,tags,matched_place_id,status from app_private.map_candidates where campus_id=${row.id}::uuid and status='PENDING' order by feature_kind,name nulls last limit 500`),database(c.env).execute(sql`select id,title,kind,status from app_private.map_capture_missions where campus_id=${row.id}::uuid order by created_at desc limit 100`)]);return c.json({campus:row,imports:jobs.rows,candidates:candidates.rows,missions:missions.rows});});
mapRoutes.post('/admin/candidates/:id/decision',async c=>{const candidateId=id(c.req.param('id')),data=await input(c,z.object({decision:z.enum(['APPROVE','MERGE','REJECT']),placeId:z.string().uuid().optional(),name:z.string().trim().min(2).max(180).optional(),note:z.string().trim().min(3).max(1000)}).strict());const db=database(c.env),candidate=firstRow(await db.execute<{campus_id:string;institution_id:string;source_feature_id:string;feature_kind:string;geometry:{type:string;coordinates:unknown};tags:Record<string,unknown>;name:string|null;matched_place_id:string|null;status:string}>(sql`select * from app_private.map_candidates where id=${candidateId}::uuid`));if(!candidate)throw new AppError(404,'NOT_FOUND','Candidate not found.');await adminCampus(candidate.campus_id,c);if(candidate.status!=='PENDING')throw new AppError(409,'CONFLICT','This candidate has already been reviewed.');const geom=JSON.stringify(candidate.geometry),tags=JSON.stringify(candidate.tags);let placeId=data.placeId??candidate.matched_place_id;
 if(data.decision!=='REJECT'){
  if(candidate.feature_kind==='PATH'){const nodeIds=candidate.tags.node_ids;if(!Array.isArray(nodeIds)||nodeIds.length<2||candidate.geometry.type!=='LineString')throw new AppError(422,'BAD_REQUEST','This path has no connected geometry.');await db.execute(sql`insert into public.campus_paths(institution_id,campus_id,source_feature_id,node_ids,geom,name,access,surface,steps,wheelchair) values(${candidate.institution_id}::uuid,${candidate.campus_id}::uuid,${candidate.source_feature_id},${nodeIds.map(String)}::text[],ST_SetSRID(ST_GeomFromGeoJSON(${geom}),4326),${candidate.name},${String(candidate.tags.foot??candidate.tags.access??'yes')},${String(candidate.tags.surface??'')},${candidate.tags.highway==='steps'},${String(candidate.tags.wheelchair??'')}) on conflict(campus_id,source_feature_id) do update set geom=excluded.geom,node_ids=excluded.node_ids,access=excluded.access,surface=excluded.surface,steps=excluded.steps,wheelchair=excluded.wheelchair,verified_at=now()`);}
  else if(candidate.feature_kind==='BOUNDARY'){if(candidate.geometry.type!=='Polygon'&&candidate.geometry.type!=='MultiPolygon')throw new AppError(422,'BAD_REQUEST','Campus boundaries must be polygons.');await db.execute(sql`update public.institution_campuses set boundary=ST_Multi(ST_SetSRID(ST_GeomFromGeoJSON(${geom}),4326)),boundary_verified_at=now() where id=${candidate.campus_id}::uuid`);}
  else if(candidate.feature_kind==='ENTRANCE'){if(candidate.geometry.type!=='Point'||!placeId)throw new AppError(422,'BAD_REQUEST','Choose the place served by this entrance.');await db.execute(sql`insert into public.campus_entrances(institution_id,campus_id,place_id,geom,label,preferred,verified_at) select ${candidate.institution_id}::uuid,${candidate.campus_id}::uuid,p.id,ST_SetSRID(ST_GeomFromGeoJSON(${geom}),4326),${data.name??'Entrance'},true,now() from public.campus_places p where p.id=${placeId}::uuid and p.campus_id=${candidate.campus_id}::uuid`);}
  else{if(!placeId){const name=data.name??candidate.name;if(!name)throw new AppError(422,'BAD_REQUEST','Name this building before publishing it.');placeId=crypto.randomUUID();await db.execute(sql`insert into public.campus_places(id,university_id,campus_id,name,category,description,status) values(${placeId}::uuid,${candidate.institution_id}::uuid,${candidate.campus_id}::uuid,${name},'SERVICE','OpenStreetMap feature reviewed by KampusOne.','PUBLISHED')`);}const updated=firstRow(await db.execute(sql`update public.campus_places set geom=ST_SetSRID(ST_GeomFromGeoJSON(${geom}),4326),longitude=ST_X(ST_Centroid(ST_SetSRID(ST_GeomFromGeoJSON(${geom}),4326))),latitude=ST_Y(ST_Centroid(ST_SetSRID(ST_GeomFromGeoJSON(${geom}),4326))),source_provider='OSM',source_feature_id=${candidate.source_feature_id},source_url=${'https://www.openstreetmap.org/'+candidate.source_feature_id},verified_at=now(),confidence=1 where id=${placeId}::uuid and campus_id=${candidate.campus_id}::uuid returning id`));if(!updated)throw new AppError(422,'BAD_REQUEST','Choose a place in this campus.');}
  await db.execute(sql`insert into public.campus_map_features(institution_id,campus_id,source_provider,source_feature_id,kind,geom,tags) values(${candidate.institution_id}::uuid,${candidate.campus_id}::uuid,'OSM',${candidate.source_feature_id},${candidate.feature_kind},ST_SetSRID(ST_GeomFromGeoJSON(${geom}),4326),${tags}::jsonb) on conflict(campus_id,source_provider,source_feature_id) do update set geom=excluded.geom,tags=excluded.tags,verified_at=now()`);
 }
 await db.execute(sql`update app_private.map_candidates set status=${data.decision==='APPROVE'?'APPROVED':data.decision==='MERGE'?'MERGED':'REJECTED'},reviewer_user_id=${currentUser(c).id}::uuid,decision_note=${data.note},reviewed_at=now() where id=${candidateId}::uuid and status='PENDING'`);await db.execute(sql`update public.institution_campuses set map_revision=map_revision+1 where id=${candidate.campus_id}::uuid`);await recordAudit(c.env,{actorUserId:currentUser(c).id,universityId:candidate.institution_id,action:'maps.candidate.'+data.decision.toLowerCase(),targetType:'map_candidate',targetId:candidateId,requestId:c.get('requestId')});return c.json({status:'saved'});
});
