export type AdminModule = {
  id: string;
  label: string;
  permission: string;
  href?: string;
  dataset?: string;
  columns?: string[];
  type?: string;
  status?: string;
  dependency?: string;
  requirements?: number[];
};
export type AdminGroup = { id: string; label: string; items: AdminModule[] };

const live = (id: string, label: string, permission: string, href: string): AdminModule => ({ id, label, permission, href });
const table = (id: string, label: string, permission: string, dataset: string, columns: string[], filters: Partial<AdminModule> = {}): AdminModule => ({ id, label, permission, dataset, columns, href: `/admin/workspaces/${id}`, ...filters });
const planned = (id: string, label: string, permission: string, dependency: string, requirements: number[]): AdminModule => ({ id, label, permission, dependency, requirements });
const agentColumns = ["name", "type", "institution_id", "status", "created_at"];
const financeColumns = ["name", "total_kobo", "institution_id", "status", "created_at"];
const analyticsColumns = ["name", "screen", "feature", "error_code", "institution_id", "created_at"];

// Only implemented routes receive links. The full proposal stays visible as explicitly
// planned capability text for super administrators, and in the delivery catalogue.
export const adminGroups: AdminGroup[] = [
  { id: "overview", label: "Overview", items: [live("overview", "Operational overview", "overview.view", "/admin"), live("pending", "Pending work", "agents.view", "/admin/applications"), table("recent-activity", "Recent activity", "audit.view", "audit", ["created_at", "name", "type", "status"])] },
  { id: "universities", label: "Universities & campuses", items: [table("universities", "University directory", "universities.view", "universities", ["name", "slug", "state", "status"]), live("campuses", "Campuses, buildings & offices", "universities.view", "/admin/campuses"), live("campus-availability", "Campus availability", "universities.manage", "/admin/universities"), live("communities", "Communities & cohorts", "universities.view", "/admin/communities"), table("academic-submissions", "Missing-data submissions", "academic.view", "academic-submissions", ["institution_id", "faculty_name", "name", "programme_name", "status", "created_at"]), live("academic-structure", "Faculties · departments · programmes", "academic.view", "/admin/academics"), live("source-batches", "Source batches & corrections", "academic.view", "/admin/sources")] },
  { id: "users", label: "Students & users", items: [table("users", "All users & academic profiles", "users.view", "users", ["name", "email", "institution_id", "type", "status", "created_at"]), table("active-users", "Active accounts", "users.view", "users", ["name", "email", "institution_id", "status", "created_at"], { status: "ACTIVE" }), planned("privacy-requests", "Transfers & privacy requests", "users.view", "Reviewed transfer and privacy-request workflows", [21, 169])] },
  { id: "staff", label: "Staff & access", items: [live("staff", "Staff accounts & permissions", "staff.manage", "/admin/staff"), table("access-history", "Staff & administrative audit", "audit.view", "audit", ["created_at", "name", "type", "target_id", "status"]), planned("staff-invitations", "Staff invitations", "staff.manage", "Single-use invitation delivery and acceptance", [14, 19])] },
  { id: "agents", label: "Agents & applications", items: [table("agents", "All agent applications", "agents.view", "agents", agentColumns), live("application-review", "Application & document review", "agents.view", "/admin/applications"), table("pending-applications", "Pending review", "agents.view", "agents", agentColumns, { status: "SUBMITTED" }), table("corrections", "Corrections & resubmissions", "agents.view", "agents", agentColumns, { status: "NEEDS_CORRECTION" }), table("approved-agents", "Approval history", "agents.view", "agents", agentColumns, { status: "APPROVED" }), live("automated-checks", "Metadata checks & review flags", "agents.verify", "/admin/applications"), live("bulk-decisions", "Reviewed bulk decisions", "agents.review", "/admin/applications")] },
  { id: "vendors", label: "Vendors & stores", items: [table("vendor-applications", "Vendor applications", "agents.view", "agents", agentColumns, { type: "VENDOR" }), live("vendor-directory", "Approved vendor directory", "agents.view", "/admin/vendors"), live("stores", "Store verification & products", "marketplace.view", "/admin/operations"), live("trial-claims", "Trial claims & expiry", "agents.view", "/admin/trials")] },
  { id: "tutors", label: "Tutors & learning services", items: [table("tutor-applications", "Tutor applications", "agents.view", "agents", agentColumns, { type: "TUTOR" }), live("tutor-offers", "Teaching offers & materials", "content.view", "/admin/tutorials"), planned("tutor-subjects", "Subjects & levels taught", "agents.view", "Structured tutor-profile catalogue", [27, 192, 193])] },
  { id: "riders", label: "Riders & delivery", items: [table("rider-applications", "Rider applications", "agents.view", "agents", agentColumns, { type: "RIDER" }), live("rider-directory", "Approved rider directory", "agents.view", "/admin/riders"), planned("rider-activity", "Service campuses & delivery activity", "agents.view", "Scoped delivery activity workspace", [28, 190, 191])] },
  { id: "marketplace", label: "Marketplace", items: [live("marketplace", "Products, stores & disputes", "marketplace.view", "/admin/operations"), planned("order-management", "Orders · cancellations · refunds", "marketplace.view", "Dedicated order/refund review workspaces", [29, 225, 226, 227])] },
  { id: "feeds", label: "Feeds & publishing", items: [table("posts", "All posts", "content.view", "content", ["name", "author_user_id", "institution_id", "status", "created_at"]), table("published-posts", "Published posts", "content.view", "content", ["name", "author_user_id", "institution_id", "status", "created_at"], { status: "PUBLISHED" }), live("publishing", "Campus publishing & sources", "content.manage", "/admin/content"), planned("qa-moderation", "Polls · Q&A · reports · appeals", "content.view", "Publisher capabilities and private answer moderation", [30, 79, 80, 81, 82, 83, 84, 85, 86]), planned("personas", "Managed publishing personas", "content.manage", "Disclosed platform persona model", [65, 66, 67, 69])] },
  { id: "academics", label: "Academic tools", items: [table("academic-review", "Academic correction queue", "academic.view", "academic-submissions", ["institution_id", "name", "programme_name", "status", "created_at"]), planned("academic-tools", "Timetables · import jobs · GPA rules", "academic.view", "Private academic-tool inspection permissions and reviewed rules", [32, 138, 141, 157])] },
  { id: "knowledge", label: "Campus guidelines & knowledge", items: [live("guidelines", "University · faculty · department rules", "academic.view", "/admin/sources"), live("source-library", "Sources · versions · effective dates", "academic.view", "/admin/sources")] },
  { id: "ai", label: "AI operations", items: [table("ai-jobs", "AI requests & job states", "ai.view", "ai", ["name", "status", "institution_id", "created_at"]), live("ai-usage", "Usage & configuration", "ai.view", "/admin/ai")] },
  { id: "verification", label: "Verification & trust", items: [table("verification-accounts", "Account verification", "users.view", "users", ["name", "email", "institution_id", "verification_status", "type"]), live("identity-review", "Agent identity review", "agents.review", "/admin/applications"), planned("verification-categories", "Verification categories & overrides", "users.verify", "Badge policy editor and reasoned override workflow", [38, 39, 40, 41])] },
  { id: "finance", label: "Revenue & finance", items: [table("transactions", "Store order activity", "finance.view", "finance", financeColumns), planned("finance-reconciliation", "Reconciliation · fees · exports", "finance.view", "Ledger reconciliation and purpose-limited export", [34])] },
  { id: "payouts", label: "Payouts", items: [live("payout-eligibility", "Bank review & eligible agents", "finance.review", "/admin/payouts"), planned("payout-batches", "Requests · approvals · batches · history", "finance.view", "Dedicated payout permission and approval workspace", [34, 224])] },
  { id: "email", label: "Email & broadcasts", items: [live("campaigns", "Campaigns · audiences · test sends", "broadcasts.view", "/admin/broadcasts"), planned("email-events", "Templates · delivery events · preferences", "broadcasts.view", "Delivery webhooks and recipient preference controls", [51, 52, 53])] },
  { id: "notifications", label: "Notifications", items: [live("notification-tests", "Devices · test notification · receipts", "notifications.test", "/admin/notifications")] },
  { id: "analytics", label: "Analytics", items: [table("analytics", "Recorded product events", "analytics.view", "analytics", analyticsColumns), live("analytics-reports", "Activity · return rates · university comparisons", "analytics.view", "/admin/reports")] },
  { id: "support", label: "Support & moderation", items: [live("support-inbox", "Support inbox & case replies", "support.view", "/admin/support"), planned("support-escalations", "Reports · escalations · appeals", "support.view", "Assignment, escalation and case-history model", [30, 36])] },
  { id: "security", label: "Security & privacy", items: [table("audit", "Protected audit trail", "audit.view", "audit", ["created_at", "name", "type", "status", "target_id"]), planned("security-events", "Authentication · sensitive access · retention", "audit.view", "Dedicated security-event and retention controls", [20, 37, 169])] },
  { id: "system", label: "System & integrations", items: [planned("system-health", "API · database · providers · deployments", "system.view", "Engineering diagnostics isolated by operator permissions", [35, 139, 165])] },
  { id: "controls", label: "Product controls", items: [live("university-rollout", "University rollout", "universities.manage", "/admin/universities"), live("trial-controls", "Trial oversight", "agents.view", "/admin/trials"), planned("feature-controls", "Flags · entitlements · limits · maintenance", "product.manage", "Audited configuration editor", [33, 228, 229, 230, 237])] },
  { id: "tracker", label: "Implementation tracker", items: [live("delivery-catalogue", "Module dependencies & delivery status", "system.view", "/admin/catalogue"), live("requirements-tracker", "All 241 requirements & test evidence", "system.view", "/admin/requirements")] },
];

export const adminModules = adminGroups.flatMap((group) => group.items);
export const getAdminModule = (id: string) => adminModules.find((module) => module.id === id);
