begin;

-- Onboarding institution catalogue only.
-- Source inventory: 328 Nigerian universities staged on 2026-09-21 and count-reconciled
-- against the NUC Nigerian University System directory on 2026-09-27
-- (77 federal, 69 state, 182 private).
--
-- This migration deliberately publishes institution identity only. It does not create or
-- infer faculties, departments, programmes, grading scales, campus places, or academic
-- rules. Universities without reviewed academic structure remain PREPARING and use the
-- existing onboarding "details for review" fallback.
--
-- Existing institutions (especially University of Benin) keep their current UUIDs and
-- slugs. No profile or existing academic relationship is rewritten.

create temporary table onboarding_university_catalogue (
  report_ref text primary key,
  name text not null unique,
  proposed_slug text not null unique,
  website_url text
) on commit drop;

insert into onboarding_university_catalogue (report_ref, name, proposed_slug, website_url)
values
  ('F001', 'Abubakar Tafawa Balewa University, Bauchi', 'abubakar-tafawa-balewa-university-bauchi', 'https://atbu.edu.ng'),
  ('F002', 'Ahmadu Bello University, Zaria', 'ahmadu-bello-university-zaria', 'https://abu.edu.ng'),
  ('F003', 'Bayero University, Kano', 'bayero-university-kano', 'https://buk.edu.ng'),
  ('F004', 'Federal University Gashua, Yobe', 'federal-university-gashua-yobe', 'https://fugashua.edu.ng'),
  ('F005', 'Federal University of Petroleum Resources, Effurun', 'federal-university-of-petroleum-resources-effurun', 'https://fupre.edu.ng'),
  ('F006', 'Federal University of Technology, Akure', 'federal-university-of-technology-akure', 'https://futa.edu.ng'),
  ('F007', 'Federal University of Technology, Minna', 'federal-university-of-technology-minna', 'https://futminna.edu.ng'),
  ('F008', 'Federal University of Technology, Owerri', 'federal-university-of-technology-owerri', 'https://futo.edu.ng'),
  ('F009', 'Federal University, Dutse, Jigawa State', 'federal-university-dutse-jigawa-state', 'https://fud.edu.ng'),
  ('F010', 'Federal University, Dutsin-Ma, Katsina', 'federal-university-dutsin-ma-katsina', 'https://fudutsinma.edu.ng'),
  ('F011', 'Federal University, Kashere, Gombe State', 'federal-university-kashere-gombe-state', 'https://fukashere.edu.ng'),
  ('F012', 'Federal University, Lafia, Nasarawa State', 'federal-university-lafia-nasarawa-state', 'https://fulafia.edu.ng'),
  ('F013', 'Federal University, Lokoja, Kogi State', 'federal-university-lokoja-kogi-state', 'https://fulokoja.edu.ng'),
  ('F014', 'Alex Ekwueme University, Ndufu-Alike, Ebonyi State', 'alex-ekwueme-university-ndufu-alike-ebonyi-state', 'https://funai.edu.ng'),
  ('F015', 'Federal University, Otuoke, Bayelsa', 'federal-university-otuoke-bayelsa', 'https://fuotuoke.edu.ng'),
  ('F016', 'Federal University, Oye-Ekiti, Ekiti State', 'federal-university-oye-ekiti-ekiti-state', 'https://fuoye.edu.ng'),
  ('F017', 'Federal University, Wukari, Taraba State', 'federal-university-wukari-taraba-state', 'https://fuwukari.edu.ng'),
  ('F018', 'Federal University, Birnin Kebbi', 'federal-university-birnin-kebbi', 'https://fubk.edu.ng'),
  ('F019', 'Federal University, Gusau, Zamfara', 'federal-university-gusau-zamfara', 'https://fugusau.edu.ng'),
  ('F020', 'Michael Okpara University of Agriculture, Umudike', 'michael-okpara-university-of-agriculture-umudike', 'https://mouau.edu.ng'),
  ('F021', 'Modibbo Adama University of Technology, Yola', 'modibbo-adama-university-of-technology-yola', 'https://mautech.edu.ng'),
  ('F022', 'National Open University of Nigeria, Abuja', 'national-open-university-of-nigeria-abuja', 'https://nou.edu.ng'),
  ('F023', 'Nigeria Police Academy, Wudil', 'nigeria-police-academy-wudil', 'https://polac.edu.ng'),
  ('F024', 'Nigerian Defence Academy, Kaduna', 'nigerian-defence-academy-kaduna', 'https://nda.edu.ng'),
  ('F025', 'Nnamdi Azikiwe University, Awka', 'nnamdi-azikiwe-university-awka', 'https://unizik.edu.ng'),
  ('F026', 'Obafemi Awolowo University, Ile-Ife', 'obafemi-awolowo-university-ile-ife', 'https://oauife.edu.ng'),
  ('F027', 'University of Abuja, Gwagwalada', 'university-of-abuja-gwagwalada', 'https://uniabuja.edu.ng'),
  ('F028', 'Federal University of Agriculture, Abeokuta', 'federal-university-of-agriculture-abeokuta', 'https://unaab.edu.ng'),
  ('F029', 'Joseph Sarwuan Tarka University, Makurdi', 'joseph-sarwuan-tarka-university-makurdi', 'https://uam.edu.ng'),
  ('F030', 'University of Benin', 'university-of-benin', 'https://uniben.edu.ng'),
  ('F031', 'University of Calabar', 'university-of-calabar', 'https://unical.edu.ng'),
  ('F032', 'University of Ibadan', 'university-of-ibadan', 'https://ui.edu.ng'),
  ('F033', 'University of Ilorin', 'university-of-ilorin', 'https://unilorin.edu.ng'),
  ('F034', 'University of Jos', 'university-of-jos', 'https://unijos.edu.ng'),
  ('F035', 'University of Lagos', 'university-of-lagos', 'https://unilag.edu.ng'),
  ('F036', 'University of Maiduguri', 'university-of-maiduguri', 'https://unimaid.edu.ng'),
  ('F037', 'University of Nigeria, Nsukka', 'university-of-nigeria-nsukka', 'https://unn.edu.ng'),
  ('F038', 'University of Port Harcourt', 'university-of-port-harcourt', 'https://uniport.edu.ng'),
  ('F039', 'University of Uyo', 'university-of-uyo', 'https://uniuyo.edu.ng'),
  ('F040', 'Usumanu Danfodiyo University', 'usumanu-danfodiyo-university', 'https://udusok.edu.ng'),
  ('F041', 'Nigerian Maritime University, Okerenkoko, Delta State', 'nigerian-maritime-university-okerenkoko-delta-state', 'https://nmu.edu.ng'),
  ('F042', 'Air Force Institute of Technology, Kaduna', 'air-force-institute-of-technology-kaduna', 'https://afit.edu.ng'),
  ('F043', 'Nigerian Army University, Biu', 'nigerian-army-university-biu', 'https://naub.edu.ng'),
  ('F044', 'Federal University of Health Sciences, Otukpo, Benue State', 'federal-university-of-health-sciences-otukpo-benue-state', null),
  ('F045', 'Federal University of Agriculture, Zuru, Kebbi State', 'federal-university-of-agriculture-zuru-kebbi-state', null),
  ('F046', 'Federal University of Technology, Babura, Jigawa State', 'federal-university-of-technology-babura-jigawa-state', null),
  ('F047', 'Federal University of Technology, Ikot Abasi, Akwa Ibom State', 'federal-university-of-technology-ikot-abasi-akwa-ibom-state', null),
  ('F048', 'Federal University of Health Sciences, Azare, Bauchi State', 'federal-university-of-health-sciences-azare-bauchi-state', null),
  ('F049', 'Federal University of Health Sciences, Ila Orangun, Osun State', 'federal-university-of-health-sciences-ila-orangun-osun-state', null),
  ('F050', 'David Nweze Umahi Federal University of Medical Sciences, Uburu', 'david-nweze-umahi-federal-university-of-medical-sciences-uburu', 'https://kdums.edu.ng'),
  ('F051', 'Admiralty University, Ibusa, Delta State', 'admiralty-university-ibusa-delta-state', 'https://adun.edu.ng'),
  ('F052', 'Federal University of Transportation, Daura, Katsina', 'federal-university-of-transportation-daura-katsina', 'https://futd.edu.ng'),
  ('F053', 'African Aviation and Aerospace University', 'african-aviation-and-aerospace-university', 'https://aaau.edu.ng'),
  ('F054', 'National University of Science and Technology, Abuja', 'national-university-of-science-and-technology-abuja', null),
  ('F055', 'Federal University of Agriculture, Bassam-Biri, Bayelsa', 'federal-university-of-agriculture-bassam-biri-bayelsa', null),
  ('F056', 'Federal University of Health Sciences, Kwale, Delta State', 'federal-university-of-health-sciences-kwale-delta-state', null),
  ('F057', 'Federal University of Health Sciences, Katsina', 'federal-university-of-health-sciences-katsina', null),
  ('F058', 'Federal University of Agriculture, Mubi', 'federal-university-of-agriculture-mubi', null),
  ('F059', 'Federal University of Education, Zaria, Kaduna State', 'federal-university-of-education-zaria-kaduna-state', null),
  ('F060', 'Alvan Ikoku Federal University of Education, Owerri, Imo State', 'alvan-ikoku-federal-university-of-education-owerri-imo-state', null),
  ('F061', 'Yusuf Maitama Sule Federal University of Education, Kano', 'yusuf-maitama-sule-federal-university-of-education-kano', null),
  ('F062', 'Adeyemi Federal University of Education, Ondo', 'adeyemi-federal-university-of-education-ondo', null),
  ('F063', 'Federal University of Allied Health Sciences, Enugu', 'federal-university-of-allied-health-sciences-enugu', 'https://fuahse.edu.ng'),
  ('F064', 'Federal University of Medicine and Medical Sciences, Abeokuta', 'federal-university-of-medicine-and-medical-sciences-abeokuta', 'https://fummsa.net'),
  ('F065', 'Federal University of Education, Pankshin, Plateau State', 'federal-university-of-education-pankshin-plateau-state', null),
  ('F066', 'Federal University of Education, Kontagora, Niger State', 'federal-university-of-education-kontagora-niger-state', null),
  ('F067', 'University of Maritime Studies, Oron, Akwa Ibom State', 'university-of-maritime-studies-oron-akwa-ibom-state', null),
  ('F068', 'Federal University of Environment and Technology, Tai Town, Ogoniland, Rivers State', 'federal-university-of-environment-and-technology-tai-town-ogoniland-rivers-state', null),
  ('F069', 'Federal University of Applied Sciences, Kachia, Kaduna State', 'federal-university-of-applied-sciences-kachia-kaduna-state', null),
  ('F070', 'Tai Solarin Federal University of Education, Ijagun, Ijebu Ode', 'tai-solarin-federal-university-of-education-ijagun-ijebu-ode', null),
  ('F071', 'Federal University of Agriculture and Developmental Studies, Iragbuji, Osun State', 'federal-university-of-agriculture-and-developmental-studies-iragbuji-osun-state', null),
  ('F072', 'Federal University of Technology and Environmental Studies, Iyin-Ekiti, Ekiti State', 'federal-university-of-technology-and-environmental-studies-iyin-ekiti-ekiti-state', null),
  ('F073', 'Federal University of Agriculture and Technology, Okeho, Oyo State', 'federal-university-of-agriculture-and-technology-okeho-oyo-state', null),
  ('F074', 'Federal University of Health Science and Technology, Tsafe', 'federal-university-of-health-science-and-technology-tsafe', null),
  ('F075', 'Federal University of Agriculture and Technology, Obio-Akpa, Akwa Ibom State', 'federal-university-of-agriculture-and-technology-obio-akpa-akwa-ibom-state', null),
  ('F076', 'Federal University of Science and Technology, Epe', 'federal-university-of-science-and-technology-epe', null),
  ('F077', 'Federal University of Science and Technology, Kabo, Kano', 'federal-university-of-science-and-technology-kabo-kano', 'https://fustkabo.edu.ng'),
  ('S001', 'Rivers State University', 'rivers-state-university', 'https://rsu.edu.ng'),
  ('S002', 'Ambrose Alli University, Ekpoma', 'ambrose-alli-university-ekpoma', 'https://aauekpoma.edu.ng'),
  ('S003', 'Abia State University, Uturu', 'abia-state-university-uturu', 'https://abiastateuniversity.edu.ng'),
  ('S004', 'Ekiti State University', 'ekiti-state-university', 'https://eksu.edu.ng'),
  ('S005', 'Enugu State University of Science and Technology, Enugu', 'enugu-state-university-of-science-and-technology-enugu', 'https://esut.edu.ng'),
  ('S006', 'Olabisi Onabanjo University, Ago Iwoye', 'olabisi-onabanjo-university-ago-iwoye', 'https://oouagoiwoye.edu.ng'),
  ('S007', 'Lagos State University, Ojo', 'lagos-state-university-ojo', 'https://lasu.edu.ng'),
  ('S008', 'Ladoke Akintola University of Technology, Ogbomoso', 'ladoke-akintola-university-of-technology-ogbomoso', 'https://lautech.edu.ng'),
  ('S009', 'Rev. Fr. Moses Orshio Adasu (formerly Benue State University), Makurdi', 'rev-fr-moses-orshio-adasu-formerly-benue-state-university-makurdi', 'https://bsum.edu.ng'),
  ('S010', 'Delta State University, Abraka', 'delta-state-university-abraka', 'https://delsu.edu.ng'),
  ('S011', 'Imo State University, Owerri', 'imo-state-university-owerri', 'https://imsu.edu.ng'),
  ('S012', 'Adekunle Ajasin University, Akungba', 'adekunle-ajasin-university-akungba', 'https://aaua.edu.ng'),
  ('S013', 'Prince Abubakar Audu University, Anyigba', 'prince-abubakar-audu-university-anyigba', 'https://ksu.edu.ng'),
  ('S014', 'Chukwuemeka Odumegwu Ojukwu University, Uli', 'chukwuemeka-odumegwu-ojukwu-university-uli', 'https://coou.edu.ng'),
  ('S015', 'Ebonyi State University, Abakaliki', 'ebonyi-state-university-abakaliki', 'https://ebsu.edu.ng'),
  ('S016', 'Aliko Dangote University of Science and Technology, Wudil', 'aliko-dangote-university-of-science-and-technology-wudil', 'https://kust.edu.ng'),
  ('S017', 'Niger Delta University, Yenagoa', 'niger-delta-university-yenagoa', 'https://ndu.edu.ng'),
  ('S018', 'Adamawa State University, Mubi', 'adamawa-state-university-mubi', 'https://adsu.edu.ng'),
  ('S019', 'Nasarawa State University, Keffi', 'nasarawa-state-university-keffi', 'https://nsuk.edu.ng'),
  ('S020', 'University of Cross River State, Calabar', 'university-of-cross-river-state-calabar', 'https://crutech.edu.ng'),
  ('S021', 'Gombe State University, Gombe', 'gombe-state-university-gombe', 'https://gsu.edu.ng'),
  ('S022', 'Kaduna State University, Kaduna', 'kaduna-state-university-kaduna', 'https://kasu.edu.ng'),
  ('S023', 'Ibrahim Badamasi Babangida University, Lapai', 'ibrahim-badamasi-babangida-university-lapai', 'https://ibbu.edu.ng'),
  ('S024', 'Plateau State University, Bokkos', 'plateau-state-university-bokkos', 'https://plasu.edu.ng'),
  ('S025', 'Yobe State University, Damaturu', 'yobe-state-university-damaturu', 'https://ysu.edu.ng'),
  ('S026', 'Kebbi State University of Science and Technology, Aliero', 'kebbi-state-university-of-science-and-technology-aliero', 'https://ksusta.edu.ng'),
  ('S027', 'Umar Musa Yar'' Adua University, Katsina', 'umar-musa-yar-adua-university-katsina', 'https://umyu.edu.ng'),
  ('S028', 'Osun State University, Osogbo', 'osun-state-university-osogbo', 'https://uniosun.edu.ng'),
  ('S029', 'Olusegun Agagu University of Science and Technology, Okitipupa, Ondo', 'olusegun-agagu-university-of-science-and-technology-okitipupa-ondo', 'https://osustech.edu.ng'),
  ('S030', 'Taraba State University, Jalingo', 'taraba-state-university-jalingo', 'https://tsuniversity.edu.ng'),
  ('S031', 'Kwara State University, Ilorin', 'kwara-state-university-ilorin', 'https://kwasu.edu.ng'),
  ('S032', 'Sokoto State University', 'sokoto-state-university', 'https://ssu.edu.ng'),
  ('S033', 'Akwa Ibom State University, Ikot Akpaden', 'akwa-ibom-state-university-ikot-akpaden', 'https://aksu.edu.ng'),
  ('S034', 'Ignatius Ajuru University of Education, Rumuolumeni', 'ignatius-ajuru-university-of-education-rumuolumeni', 'https://iaue.edu.ng'),
  ('S035', 'Bauchi State University, Gadau', 'bauchi-state-university-gadau', 'https://basug.edu.ng'),
  ('S036', 'Northwest University, Kano', 'northwest-university-kano', 'https://nwu.edu.ng'),
  ('S037', 'First Technical University, Ibadan', 'first-technical-university-ibadan', 'https://tech-u.edu.ng'),
  ('S038', 'Sule Lamido University, Kafin Hausa, Jigawa', 'sule-lamido-university-kafin-hausa-jigawa', 'https://slu.edu.ng'),
  ('S039', 'University of Medical Sciences, Ondo City,', 'university-of-medical-sciences-ondo-city', 'https://unimed.edu.ng'),
  ('S040', 'Edo State University, Iyamho', 'edo-state-university-iyamho', 'https://edouniversity.edu.ng'),
  ('S041', 'Kingsley Ozumba Mbadiwe University, Ogboko, Imo State', 'kingsley-ozumba-mbadiwe-university-ogboko-imo-state', 'https://komu.edu.ng'),
  ('S042', 'University of Africa, Toru Orua, Bayelsa State', 'university-of-africa-toru-orua-bayelsa-state', 'https://uat.edu.ng'),
  ('S043', 'Kashim Ibrahim (formerly Bornu State) University, Maiduguri', 'kashim-ibrahim-formerly-bornu-state-university-maiduguri', null),
  ('S044', 'Moshood Abiola University of Science and Technology, Abeokuta', 'moshood-abiola-university-of-science-and-technology-abeokuta', null),
  ('S045', 'Zamfara State University', 'zamfara-state-university', null),
  ('S046', 'Bayelsa Medical University', 'bayelsa-medical-university', 'https://bmu.edu.ng'),
  ('S047', 'University of Agriculture and Environmental Sciences, Umuagwo, Imo State', 'university-of-agriculture-and-environmental-sciences-umuagwo-imo-state', 'https://uaes.edu.ng'),
  ('S048', 'Confluence University of Science and Technology, Osara, Kogi', 'confluence-university-of-science-and-technology-osara-kogi', 'https://custech.edu.ng'),
  ('S049', 'Bamidele Olumilua University of Science and Technology, Ikere, Ekiti State', 'bamidele-olumilua-university-of-science-and-technology-ikere-ekiti-state', 'https://bouesti.edu.ng'),
  ('S050', 'University of Delta, Agbor', 'university-of-delta-agbor', 'https://unidel.edu.ng'),
  ('S051', 'Delta University of Science and Technology, Ozoro', 'delta-university-of-science-and-technology-ozoro', 'https://dsust.edu.ng'),
  ('S052', 'Dennis Osadebe University, Asaba', 'dennis-osadebe-university-asaba', 'https://dou.edu.ng'),
  ('S053', 'Lagos State University of Education, Ijanikin', 'lagos-state-university-of-education-ijanikin', null),
  ('S054', 'Lagos State University of Science and Technology, Ikorodu', 'lagos-state-university-of-science-and-technology-ikorodu', null),
  ('S055', 'Shehu Shagari University of Education, Sokoto', 'shehu-shagari-university-of-education-sokoto', null),
  ('S056', 'State University of Medical and Applied Sciences, Igbo-Eno, Enugu', 'state-university-of-medical-and-applied-sciences-igbo-eno-enugu', null),
  ('S057', 'University of Ilesa, Osun State', 'university-of-ilesa-osun-state', null),
  ('S058', 'Emanuel Alayande University of Education, Oyo', 'emanuel-alayande-university-of-education-oyo', null),
  ('S059', 'Kogi State University, Kabba', 'kogi-state-university-kabba', null),
  ('S060', 'AbdulKadir Kure University, Minna, Niger State', 'abdulkadir-kure-university-minna-niger-state', null),
  ('S061', 'Kwara State University of Education, Ilorin, Kwara State', 'kwara-state-university-of-education-ilorin-kwara-state', null),
  ('S062', 'Abdulsalam Abubakar University of Agriculture and Climate Action, Mokwa, Niger State', 'abdulsalam-abubakar-university-of-agriculture-and-climate-action-mokwa-niger-state', null),
  ('S063', 'Ebonyi State University of ICT, Science and Technology, Oferekpe, Ebonyi State', 'ebonyi-state-university-of-ict-science-and-technology-oferekpe-ebonyi-state', null),
  ('S064', 'Cross River University of Education and Entrepeneurship, Akampa, Cross River State', 'cross-river-university-of-education-and-entrepeneurship-akampa-cross-river-state', null),
  ('S065', 'Benue State University of Agriculture, Science and Technology, Ihugh', 'benue-state-university-of-agriculture-science-and-technology-ihugh', null),
  ('S066', 'University of Aeronautics and Aerospace Engineering, Ezza, Ebonyi State', 'university-of-aeronautics-and-aerospace-engineering-ezza-ebonyi-state', null),
  ('S067', 'University of Innovation, Science and Technology, Omuma, Imo State', 'university-of-innovation-science-and-technology-omuma-imo-state', null),
  ('S068', 'Taraba State University of Tropical Agriculture, Science, Technology and Climate Action, Gembu', 'taraba-state-university-of-tropical-agriculture-science-technology-and-climate-action-gembu', null),
  ('S069', 'Jigawa State University of Medical and Allied Health Sciences, Majia', 'jigawa-state-university-of-medical-and-allied-health-sciences-majia', null),
  ('P001', 'Babcock University, Ilishan-Remo', 'babcock-university-ilishan-remo', 'https://babcock.edu.ng'),
  ('P002', 'Igbinedion University, Okada', 'igbinedion-university-okada', 'https://iuokada.edu.ng'),
  ('P003', 'Madonna University, Okija', 'madonna-university-okija', 'https://madonnauniversity.edu.ng'),
  ('P004', 'Bowen University, Iwo', 'bowen-university-iwo', 'https://bowen.edu.ng'),
  ('P005', 'Benson Idahosa University, Benin City', 'benson-idahosa-university-benin-city', 'https://biu.edu.ng'),
  ('P006', 'Covenant University, Ota', 'covenant-university-ota', 'https://covenantuniversity.edu.ng'),
  ('P007', 'Pan-Atlantic University, Lagos', 'pan-atlantic-university-lagos', 'https://pau.edu.ng'),
  ('P008', 'American University of Nigeria, Yola', 'american-university-of-nigeria-yola', 'https://aun.edu.ng'),
  ('P009', 'Ajayi Crowther University, Ibadan', 'ajayi-crowther-university-ibadan', 'https://acu.edu.ng'),
  ('P010', 'Al-Hikmah University, Ilorin', 'al-hikmah-university-ilorin', 'https://alhikmah.edu.ng'),
  ('P011', 'Al-Qalam University, Katsina', 'al-qalam-university-katsina', 'https://auk.edu.ng'),
  ('P012', 'Bells University of Technology, Otta', 'bells-university-of-technology-otta', 'https://bellsuniversity.edu.ng'),
  ('P013', 'Bingham University, New Karu', 'bingham-university-new-karu', 'https://binghamuni.edu.ng'),
  ('P014', 'Caritas University, Enugu', 'caritas-university-enugu', 'https://caritasuni.edu.ng'),
  ('P015', 'Crawford University, Igbesa', 'crawford-university-igbesa', 'https://crawforduniversity.edu.ng'),
  ('P016', 'Crescent University', 'crescent-university', 'https://crescent-university.edu.ng'),
  ('P017', 'Kwararafa University, Wukari', 'kwararafa-university-wukari', 'https://kwararafauniversity.edu.ng'),
  ('P018', 'Lead City University, Ibadan', 'lead-city-university-ibadan', 'https://lcu.edu.ng'),
  ('P019', 'Novena University, Ogume', 'novena-university-ogume', 'https://novenauniversity.edu.ng'),
  ('P020', 'Redeemer''s University, Ede', 'redeemer-s-university-ede', 'https://run.edu.ng'),
  ('P021', 'Renaissance University, Enugu', 'renaissance-university-enugu', 'https://rnu.edu.ng'),
  ('P022', 'University of Mkar, Mkar', 'university-of-mkar-mkar', 'https://unimkar.edu.ng'),
  ('P023', 'Joseph Ayo Babalola University, Ikeji-Arakeji', 'joseph-ayo-babalola-university-ikeji-arakeji', 'https://jabu.edu.ng'),
  ('P024', 'Achievers University, Owo', 'achievers-university-owo', 'https://achievers.edu.ng'),
  ('P025', 'Caleb University, Lagos', 'caleb-university-lagos', 'https://calebuniversity.edu.ng'),
  ('P026', 'Fountain University, Oshogbo', 'fountain-university-oshogbo', 'https://fuo.edu.ng'),
  ('P027', 'African University of Science and Technology, Abuja', 'african-university-of-science-and-technology-abuja', 'https://aust.edu.ng'),
  ('P028', 'Obong University, Obong Ntak', 'obong-university-obong-ntak', 'https://obonguniversity.net'),
  ('P029', 'Salem University, Lokoja', 'salem-university-lokoja', 'https://salemuniversity.edu.ng'),
  ('P030', 'Tansian University, Umunya', 'tansian-university-umunya', 'https://tansianuniversity.edu.ng'),
  ('P031', 'Veritas University, Abuja', 'veritas-university-abuja', 'https://veritas.edu.ng'),
  ('P032', 'Wesley University, Ondo', 'wesley-university-ondo', 'https://wesleyuni.edu.ng'),
  ('P033', 'Western Delta University, Oghara, Delta State', 'western-delta-university-oghara-delta-state', 'https://wdu.edu.ng'),
  ('P034', 'Afe Babalola University, Ado-Ekiti, Ekiti State', 'afe-babalola-university-ado-ekiti-ekiti-state', 'https://abuad.edu.ng'),
  ('P035', 'Godfrey Okoye University, Ugwuomu-Nike, Enugu State', 'godfrey-okoye-university-ugwuomu-nike-enugu-state', 'https://gouni.edu.ng'),
  ('P036', 'Nile University of Nigeria, Abuja', 'nile-university-of-nigeria-abuja', 'https://nileuniversity.edu.ng'),
  ('P037', 'Oduduwa University, Ipetumodu, Osun State', 'oduduwa-university-ipetumodu-osun-state', 'https://oduduwauniversity.edu.ng'),
  ('P038', 'Paul University, Awka, Anambra State', 'paul-university-awka-anambra-state', 'https://pauluniversity.edu.ng'),
  ('P039', 'Rhema University, Obeama-Asa, Rivers State', 'rhema-university-obeama-asa-rivers-state', 'https://rhemauniversity.edu.ng'),
  ('P040', 'Wellspring University, Evbuobanosa, Edo State', 'wellspring-university-evbuobanosa-edo-state', 'https://wellspringuniversity.net'),
  ('P041', 'Adeleke University, Ede', 'adeleke-university-ede', 'https://adelekeuniversity.edu.ng'),
  ('P042', 'Baze University', 'baze-university', 'https://bazeuniversity.edu.ng'),
  ('P043', 'Landmark University, Omu-Aran', 'landmark-university-omu-aran', 'https://lmu.edu.ng'),
  ('P044', 'Glorious Vision University, Ogwa, Edo State', 'glorious-vision-university-ogwa-edo-state', 'https://sau.edu.ng'),
  ('P045', 'Elizade University, Ilara-Mokin', 'elizade-university-ilara-mokin', 'https://elizadeuniversity.edu.ng'),
  ('P046', 'Evangel University, Akaeze', 'evangel-university-akaeze', 'https://evangeluniversity.edu.ng'),
  ('P047', 'Gregory University, Uturu', 'gregory-university-uturu', 'https://gregoryuniversity.com'),
  ('P048', 'Mcpherson University, Seriki Sotayo, Ajebo', 'mcpherson-university-seriki-sotayo-ajebo', 'https://mcu.edu.ng'),
  ('P049', 'Southwestern University, Oku Owa', 'southwestern-university-oku-owa', 'https://southwesternuniversity.edu.ng'),
  ('P050', 'Augustine University', 'augustine-university', 'https://augustineuniversity.edu.ng'),
  ('P051', 'Chrisland University', 'chrisland-university', 'https://chrislanduniversity.edu.ng'),
  ('P052', 'Edwin Clark University, Kaigbodo', 'edwin-clark-university-kaigbodo', 'https://edwinclarkuniversity.edu.ng'),
  ('P053', 'Hallmark University, Ijebi Itele, Ogun', 'hallmark-university-ijebi-itele-ogun', 'https://hallmark.edu.ng'),
  ('P054', 'Hezekiah University, Umudi', 'hezekiah-university-umudi', 'https://hezekiah.edu.ng'),
  ('P055', 'Kings University, Ode Omu', 'kings-university-ode-omu', 'https://kingsuniversity.edu.ng'),
  ('P056', 'Micheal and Cecilia Ibru University', 'micheal-and-cecilia-ibru-university', 'https://mciu.edu.ng'),
  ('P057', 'Mountain Top University', 'mountain-top-university', 'https://mtu.edu.ng'),
  ('P058', 'Ritman University, Ikot Ekpene, Akwa Ibom', 'ritman-university-ikot-ekpene-akwa-ibom', 'https://ritmanuniversity.edu.ng'),
  ('P059', 'Summit University, Offa', 'summit-university-offa', 'https://summituniversity.edu.ng'),
  ('P060', 'Christopher University, Mowe', 'christopher-university-mowe', 'https://christopheruniversity.edu.ng'),
  ('P061', 'Kola Daisi University, Ibadan, Oyo State', 'kola-daisi-university-ibadan-oyo-state', 'https://koladaisiuniversity.edu.ng'),
  ('P062', 'Anchor University, Ayobo, Lagos State', 'anchor-university-ayobo-lagos-state', 'https://aul.edu.ng'),
  ('P063', 'Dominican University, Ibadan, Oyo State', 'dominican-university-ibadan-oyo-state', 'https://dui.edu.ng'),
  ('P064', 'Legacy University, Okija, Anambra State', 'legacy-university-okija-anambra-state', 'https://legacyuniversity.edu.ng'),
  ('P065', 'Arthur Javis University, Akpoyubo, Cross River State', 'arthur-javis-university-akpoyubo-cross-river-state', 'https://arthurjarvisuniversity.edu.ng'),
  ('P066', 'Ojaja University, Eiyenkorin, Kwara State', 'ojaja-university-eiyenkorin-kwara-state', 'https://crownhilluniversity.edu.ng'),
  ('P067', 'Coal City University, Enugu State', 'coal-city-university-enugu-state', 'https://ccu.edu.ng'),
  ('P068', 'Clifford University, Owerrinta, Abia State', 'clifford-university-owerrinta-abia-state', 'https://clifforduni.edu.ng'),
  ('P069', 'Spiritan University, Nneochi, Abia State', 'spiritan-university-nneochi-abia-state', 'https://spiritanuniversity.edu.ng'),
  ('P070', 'Precious Cornerstone University, Oyo', 'precious-cornerstone-university-oyo', 'https://pcu.edu.ng'),
  ('P071', 'PAMO University of Medical Sciences, Port Harcourt', 'pamo-university-of-medical-sciences-port-harcourt', 'https://pums.edu.ng'),
  ('P072', 'Atiba University, Oyo', 'atiba-university-oyo', null),
  ('P073', 'Eko University of Medical and Health Sciences, Ijanikin, Lagos', 'eko-university-of-medical-and-health-sciences-ijanikin-lagos', 'https://ekounivmed.edu.ng'),
  ('P074', 'Skyline University, Kano', 'skyline-university-kano', 'https://sun.edu.ng'),
  ('P075', 'Greenfield University, Kaduna', 'greenfield-university-kaduna', 'https://gfu.edu.ng'),
  ('P076', 'Dominion University, Ibadan, Oyo State', 'dominion-university-ibadan-oyo-state', 'https://dominionuniversity.edu.ng'),
  ('P077', 'Trinity University, Ogun State', 'trinity-university-ogun-state', 'https://trinityuniversity.edu.ng'),
  ('P078', 'Westland University, Iwo, Osun State', 'westland-university-iwo-osun-state', null),
  ('P079', 'Topfaith University, Mkpatak, Akwa Ibom State', 'topfaith-university-mkpatak-akwa-ibom-state', null),
  ('P080', 'Thomas Adewumi University, Oko-Irese, Kwara State', 'thomas-adewumi-university-oko-irese-kwara-state', 'https://tau.edu.ng'),
  ('P081', 'Maranatha University, Lagos', 'maranatha-university-lagos', null),
  ('P082', 'Ave Maria University, Piyanko, Nasarawa State', 'ave-maria-university-piyanko-nasarawa-state', null),
  ('P083', 'Al-Istiqama University, Sumaila, Kano State', 'al-istiqama-university-sumaila-kano-state', null),
  ('P084', 'Mudiame University, Irrua, Edo State', 'mudiame-university-irrua-edo-state', null),
  ('P085', 'Havilla University, Nde-Ikom, Cross River State', 'havilla-university-nde-ikom-cross-river-state', 'https://havillauniversity.edu.ng'),
  ('P086', 'Claretian University of Nigeria, Nekede, Imo State', 'claretian-university-of-nigeria-nekede-imo-state', null),
  ('P087', 'Karl-Kumm University, Vom, Plateau State', 'karl-kumm-university-vom-plateau-state', null),
  ('P088', 'James Hope University, Lagos, Lagos State', 'james-hope-university-lagos-lagos-state', 'https://jhu.edu.ng'),
  ('P089', 'Maryam Abacha American University of Nigeria, Kano State', 'maryam-abacha-american-university-of-nigeria-kano-state', 'https://maaun.edu.ng'),
  ('P090', 'Capital City University, Kano State', 'capital-city-university-kano-state', 'https://ccuk.edu.ng'),
  ('P091', 'Ahman Pategi University, Kwara State', 'ahman-pategi-university-kwara-state', null),
  ('P092', 'University of Offa, Kwara State', 'university-of-offa-kwara-state', null),
  ('P093', 'Mewar International University, Masaka, Nasarawa State', 'mewar-international-university-masaka-nasarawa-state', 'https://miu.edu.ng'),
  ('P094', 'Edusoko University, Bida, Niger State', 'edusoko-university-bida-niger-state', null),
  ('P095', 'Philomath University, Kuje, Abuja', 'philomath-university-kuje-abuja', null),
  ('P096', 'Anan University, Kwall, Plateau State', 'anan-university-kwall-plateau-state', null),
  ('P097', 'North Eastern University, Gombe', 'north-eastern-university-gombe', 'https://pru.edu.ng'),
  ('P098', 'Al-Ansar University, Maiduguri, Borno', 'al-ansar-university-maiduguri-borno', null),
  ('P099', 'Margaret Lawrence University, Umunede, Delta State', 'margaret-lawrence-university-umunede-delta-state', null),
  ('P100', 'Khalifa Isiyaku Rabiu University, Kano', 'khalifa-isiyaku-rabiu-university-kano', null),
  ('P101', 'Sports University, Idumuje, Ugboko, Delta State', 'sports-university-idumuje-ugboko-delta-state', null),
  ('P102', 'Baba Ahmed University, Kano State', 'baba-ahmed-university-kano-state', null),
  ('P103', 'Saisa University of Medical Sciences and Technology, Sokoto State', 'saisa-university-of-medical-sciences-and-technology-sokoto-state', null),
  ('P104', 'Nigerian British University, Asa, Abia State', 'nigerian-british-university-asa-abia-state', 'https://nbu.edu.ng'),
  ('P105', 'Peter University, Achina-Onneh, Anambra State', 'peter-university-achina-onneh-anambra-state', null),
  ('P106', 'Newgate University, Minna, Niger State', 'newgate-university-minna-niger-state', null),
  ('P107', 'European University of Nigeria, Duboyi, FCT', 'european-university-of-nigeria-duboyi-fct', null),
  ('P108', 'NorthWest University, Sokoto State', 'northwest-university-sokoto-state', 'https://nwus.edu.ng'),
  ('P109', 'Rayhaan University, Kebbi', 'rayhaan-university-kebbi', null),
  ('P110', 'Muhammad Kamalud University, Kwara', 'muhammad-kamalud-university-kwara', null),
  ('P111', 'Sam Maris University, Ondo', 'sam-maris-university-ondo', null),
  ('P112', 'Aletheia University, Ago-Iwoye, Ogun State', 'aletheia-university-ago-iwoye-ogun-state', null),
  ('P113', 'Lux Mundi University, Umuahia, Abia State', 'lux-mundi-university-umuahia-abia-state', null),
  ('P114', 'Maduka University, Ekwegbe, Enugu State', 'maduka-university-ekwegbe-enugu-state', null),
  ('P115', 'PeaceLand University, Enugu State', 'peaceland-university-enugu-state', null),
  ('P116', 'Amadeus University, Amizi, Abia State', 'amadeus-university-amizi-abia-state', null),
  ('P117', 'Vision University, Ikogbo, Ogun State', 'vision-university-ikogbo-ogun-state', null),
  ('P118', 'Azman University, Kano State', 'azman-university-kano-state', null),
  ('P119', 'Huda University, Gusau, Zamfara State', 'huda-university-gusau-zamfara-state', null),
  ('P120', 'Franco British International University, Kaduna State', 'franco-british-international-university-kaduna-state', 'https://fbiu.edu.ng'),
  ('P121', 'Canadian University of Nigeria, Abuja', 'canadian-university-of-nigeria-abuja', null),
  ('P122', 'Gerar University of Medical Science, Imope Ijebu, Ogun State', 'gerar-university-of-medical-science-imope-ijebu-ogun-state', null),
  ('P123', 'British Canadian University, Obufu, Cross River State', 'british-canadian-university-obufu-cross-river-state', null),
  ('P124', 'Hensard University, Toru-Orua, Sagbama, Bayelsa State', 'hensard-university-toru-orua-sagbama-bayelsa-state', null),
  ('P125', 'Amaj University, Kwali, Abuja', 'amaj-university-kwali-abuja', null),
  ('P126', 'Phoenix University, Agwada, Nasarawa State', 'phoenix-university-agwada-nasarawa-state', null),
  ('P127', 'Wigwe University, Isiokpo, Rivers State', 'wigwe-university-isiokpo-rivers-state', null),
  ('P128', 'Hillside University of Science and Technology, Okemisi, Ekiti State', 'hillside-university-of-science-and-technology-okemisi-ekiti-state', 'https://hust.edu.ng'),
  ('P129', 'University on the Niger, Umunya, Anambra State', 'university-on-the-niger-umunya-anambra-state', null),
  ('P130', 'Elrazi Medical University Yargaya University, Kano State', 'elrazi-medical-university-yargaya-university-kano-state', null),
  ('P131', 'Venite University, Iloro-Ekiti, Ekiti State', 'venite-university-iloro-ekiti-ekiti-state', null),
  ('P132', 'Shanahan University, Onitsha, Anambra State', 'shanahan-university-onitsha-anambra-state', null),
  ('P133', 'The Duke Medical University, Calabar, Cross River State', 'the-duke-medical-university-calabar-cross-river-state', null),
  ('P134', 'Mercy Medical University, Iwo, Ogun State', 'mercy-medical-university-iwo-ogun-state', null),
  ('P135', 'Cosmopolitan University, Abuja', 'cosmopolitan-university-abuja', null),
  ('P136', 'Miva Open University, Abuja FCT', 'miva-open-university-abuja-fct', 'https://miva.university'),
  ('P137', 'Iconic Open University, Sokoto State', 'iconic-open-university-sokoto-state', null),
  ('P138', 'West Midlands Open University, Ibadan, Oyo State', 'west-midlands-open-university-ibadan-oyo-state', null),
  ('P139', 'Al-Muhibbah Open University, Abuja', 'al-muhibbah-open-university-abuja', null),
  ('P140', 'El-Amin University, Minna, Niger State', 'el-amin-university-minna-niger-state', null),
  ('P141', 'College of Petroleum and Energy Studies, Kaduna State', 'college-of-petroleum-and-energy-studies-kaduna-state', null),
  ('P142', 'Jewel University, Gombe State', 'jewel-university-gombe-state', null),
  ('P143', 'Prime University, Kuje, FCT Abuja', 'prime-university-kuje-fct-abuja', null),
  ('P144', 'Nigerian University of Technology and Management, Apapa, Lagos State', 'nigerian-university-of-technology-and-management-apapa-lagos-state', null),
  ('P145', 'Al-Bayan University, Ankpa, Kogi State', 'al-bayan-university-ankpa-kogi-state', null),
  ('P146', 'Lighthouse University, Evbobanosa, Edo State', 'lighthouse-university-evbobanosa-edo-state', null),
  ('P147', 'African University of Economics, FCT Abuja', 'african-university-of-economics-fct-abuja', null),
  ('P148', 'New City University, Ayetoro, Ogun State', 'new-city-university-ayetoro-ogun-state', null),
  ('P149', 'University of Fortune, Igbotako, Ondo State', 'university-of-fortune-igbotako-ondo-state', null),
  ('P150', 'Eranova University, Abuja', 'eranova-university-abuja', 'https://eranova.edu.ng'),
  ('P151', 'Minaret University, Ikirun, Osun State', 'minaret-university-ikirun-osun-state', null),
  ('P152', 'Abdulrasaq Abubakar Toyin University, Oke-Ogba, Ganmo, Ilorin, Kwara State', 'abdulrasaq-abubakar-toyin-university-oke-ogba-ganmo-ilorin-kwara-state', null),
  ('P153', 'Southern Atlantic University, Uyo, Akwa Ibom State', 'southern-atlantic-university-uyo-akwa-ibom-state', null),
  ('P154', 'Lens University, Ilemona, Kwara State', 'lens-university-ilemona-kwara-state', null),
  ('P155', 'Monarch University, Iyesi-Ota, Ogun State', 'monarch-university-iyesi-ota-ogun-state', null),
  ('P156', 'Tonine Iredia University of Communication, Benin City, Edo State', 'tonine-iredia-university-of-communication-benin-city-edo-state', null),
  ('P157', 'Isaac Balami University of Aeronautics and Management, Lagos State', 'isaac-balami-university-of-aeronautics-and-management-lagos-state', null),
  ('P158', 'Kevin Eze University, Mgbowo, Enugu State', 'kevin-eze-university-mgbowo-enugu-state', null),
  ('P159', 'Tazkiyah University, Kaduna, Kaduna State', 'tazkiyah-university-kaduna-kaduna-state', null),
  ('P160', 'Leadership University, Abuja FCT', 'leadership-university-abuja-fct', null),
  ('P161', 'Jimoh Babalola University, Ilorin, Kwara State', 'jimoh-babalola-university-ilorin-kwara-state', null),
  ('P162', 'Bridget University, Mbaise, Okirika-Nweke, Imo State', 'bridget-university-mbaise-okirika-nweke-imo-state', null),
  ('P163', 'Greenland University, Jalingo, Taraba State', 'greenland-university-jalingo-taraba-state', null),
  ('P164', 'JEFAP University, Suleja, Niger State', 'jefap-university-suleja-niger-state', null),
  ('P165', 'Azione Verde University, Amaigbo, Imo State', 'azione-verde-university-amaigbo-imo-state', null),
  ('P166', 'Unique Open University, Ojo, Lagos State', 'unique-open-university-ojo-lagos-state', null),
  ('P167', 'American Open University, Abeokuta, Ogun State', 'american-open-university-abeokuta-ogun-state', null),
  ('P168', 'Millenium Crest University, Ikare Akoko, Ondo State', 'millenium-crest-university-ikare-akoko-ondo-state', null),
  ('P169', 'Abdulfattah Durojaiye University, Abeokuta, Ogun State', 'abdulfattah-durojaiye-university-abeokuta-ogun-state', null),
  ('P170', 'Euston University, Abakaliki, Ebonyi State', 'euston-university-abakaliki-ebonyi-state', null),
  ('P171', 'Adeche Momoh University, Igarra, Edo State', 'adeche-momoh-university-igarra-edo-state', null),
  ('P172', 'Sani Bello University, Kontagora, Niger State', 'sani-bello-university-kontagora-niger-state', null),
  ('P173', 'Godday Erewa University, Sapele, Delta State', 'godday-erewa-university-sapele-delta-state', null),
  ('P174', 'Owolabi University, Oke Ila Orangun', 'owolabi-university-oke-ila-orangun', null),
  ('P175', 'Regnum Medical University, Anthony, Lagos State', 'regnum-medical-university-anthony-lagos-state', null),
  ('P176', 'City University, Abuja', 'city-university-abuja', 'https://cityuniversity.edu.ng'),
  ('P177', 'Transatlantic University of Medine and Health Sciences, Umuchukwu, Anambra State', 'transatlantic-university-of-medine-and-health-sciences-umuchukwu-anambra-state', null),
  ('P178', 'Maria Assumpta University, Owerri, Imo State', 'maria-assumpta-university-owerri-imo-state', null),
  ('P179', 'High Flyers University, Ikere-Ekiti, Ekiti State', 'high-flyers-university-ikere-ekiti-ekiti-state', null),
  ('P180', 'Ummah University of Nigeria, Abuja', 'ummah-university-of-nigeria-abuja', null),
  ('P181', 'Pearl University, Calabar, Cross River', 'pearl-university-calabar-cross-river', null),
  ('P182', 'Omega University, Kaduna', 'omega-university-kaduna', null);

do $$
declare
  catalogue_count integer;
begin
  select count(*) into catalogue_count from onboarding_university_catalogue;
  if catalogue_count <> 328 then
    raise exception 'Expected 328 onboarding universities, found %', catalogue_count;
  end if;
end;
$$;

insert into public.universities (
  id,
  name,
  slug,
  country,
  website_url,
  updated_at
)
select
  gen_random_uuid(),
  catalogue.name,
  catalogue.proposed_slug,
  'Nigeria',
  catalogue.website_url,
  now()
from onboarding_university_catalogue catalogue
on conflict do nothing;

-- Every selectable institution gets a non-live configuration until its institution-specific
-- academic structure is reviewed. Preserve any existing LIVE/PREPARING configuration.
insert into public.institution_config (
  institution_id,
  status,
  source_url
)
select
  universities.id,
  'PREPARING',
  'https://enuc.nuc.edu.ng/nus'
from public.universities universities
join onboarding_university_catalogue catalogue
  on catalogue.name = universities.name
where universities.deleted_at is null
on conflict (institution_id) do nothing;

-- Fail the migration instead of silently shipping a partial selector if a uniqueness
-- conflict prevented any catalogue identity from being materialised.
do $$
declare
  materialised_count integer;
begin
  select count(*)
  into materialised_count
  from public.universities universities
  join onboarding_university_catalogue catalogue
    on catalogue.name = universities.name
  where universities.deleted_at is null;

  if materialised_count <> 328 then
    raise exception 'Expected 328 active onboarding universities, found %', materialised_count;
  end if;
end;
$$;

commit;
