begin;

-- Publish the 328 institution identities from the reviewed research manifest so
-- students can select their university during onboarding.
--
-- IMPORTANT: this migration publishes institution identity ONLY. It does not
-- publish unverified faculties, departments, programmes, rules, grading scales,
-- maps, or service availability. Newly added institutions remain PREPARING.
-- Existing institution configuration (including UNIBEN's LIVE status) is kept.
with registry(report_ref, name, slug) as (
values
  ('F001', 'Abubakar Tafawa Balewa University, Bauchi', 'ng-registry-f001'),
  ('F002', 'Ahmadu Bello University, Zaria', 'ng-registry-f002'),
  ('F003', 'Bayero University, Kano', 'ng-registry-f003'),
  ('F004', 'Federal University Gashua, Yobe', 'ng-registry-f004'),
  ('F005', 'Federal University of Petroleum Resources, Effurun', 'ng-registry-f005'),
  ('F006', 'Federal University of Technology, Akure', 'ng-registry-f006'),
  ('F007', 'Federal University of Technology, Minna', 'ng-registry-f007'),
  ('F008', 'Federal University of Technology, Owerri', 'ng-registry-f008'),
  ('F009', 'Federal University, Dutse, Jigawa State', 'ng-registry-f009'),
  ('F010', 'Federal University, Dutsin-Ma, Katsina', 'ng-registry-f010'),
  ('F011', 'Federal University, Kashere, Gombe State', 'ng-registry-f011'),
  ('F012', 'Federal University, Lafia, Nasarawa State', 'ng-registry-f012'),
  ('F013', 'Federal University, Lokoja, Kogi State', 'ng-registry-f013'),
  ('F014', 'Alex Ekwueme University, Ndufu-Alike, Ebonyi State', 'ng-registry-f014'),
  ('F015', 'Federal University, Otuoke, Bayelsa', 'ng-registry-f015'),
  ('F016', 'Federal University, Oye-Ekiti, Ekiti State', 'ng-registry-f016'),
  ('F017', 'Federal University, Wukari, Taraba State', 'ng-registry-f017'),
  ('F018', 'Federal University, Birnin Kebbi', 'ng-registry-f018'),
  ('F019', 'Federal University, Gusau, Zamfara', 'ng-registry-f019'),
  ('F020', 'Michael Okpara University of Agriculture, Umudike', 'ng-registry-f020'),
  ('F021', 'Modibbo Adama University of Technology, Yola', 'ng-registry-f021'),
  ('F022', 'National Open University of Nigeria, Abuja', 'ng-registry-f022'),
  ('F023', 'Nigeria Police Academy, Wudil', 'ng-registry-f023'),
  ('F024', 'Nigerian Defence Academy, Kaduna', 'ng-registry-f024'),
  ('F025', 'Nnamdi Azikiwe University, Awka', 'ng-registry-f025'),
  ('F026', 'Obafemi Awolowo University, Ile-Ife', 'ng-registry-f026'),
  ('F027', 'University of Abuja, Gwagwalada', 'ng-registry-f027'),
  ('F028', 'Federal University of Agriculture, Abeokuta', 'ng-registry-f028'),
  ('F029', 'Joseph Sarwuan Tarka University, Makurdi', 'ng-registry-f029'),
  ('F030', 'University of Benin', 'ng-registry-f030'),
  ('F031', 'University of Calabar', 'ng-registry-f031'),
  ('F032', 'University of Ibadan', 'ng-registry-f032'),
  ('F033', 'University of Ilorin', 'ng-registry-f033'),
  ('F034', 'University of Jos', 'ng-registry-f034'),
  ('F035', 'University of Lagos', 'ng-registry-f035'),
  ('F036', 'University of Maiduguri', 'ng-registry-f036'),
  ('F037', 'University of Nigeria, Nsukka', 'ng-registry-f037'),
  ('F038', 'University of Port Harcourt', 'ng-registry-f038'),
  ('F039', 'University of Uyo', 'ng-registry-f039'),
  ('F040', 'Usumanu Danfodiyo University', 'ng-registry-f040'),
  ('F041', 'Nigerian Maritime University, Okerenkoko, Delta State', 'ng-registry-f041'),
  ('F042', 'Air Force Institute of Technology, Kaduna', 'ng-registry-f042'),
  ('F043', 'Nigerian Army University, Biu', 'ng-registry-f043'),
  ('F044', 'Federal University of Health Sciences, Otukpo, Benue State', 'ng-registry-f044'),
  ('F045', 'Federal University of Agriculture, Zuru, Kebbi State', 'ng-registry-f045'),
  ('F046', 'Federal University of Technology, Babura, Jigawa State', 'ng-registry-f046'),
  ('F047', 'Federal University of Technology, Ikot Abasi, Akwa Ibom State', 'ng-registry-f047'),
  ('F048', 'Federal University of Health Sciences, Azare, Bauchi State', 'ng-registry-f048'),
  ('F049', 'Federal University of Health Sciences, Ila Orangun, Osun State', 'ng-registry-f049'),
  ('F050', 'David Nweze Umahi Federal University of Medical Sciences, Uburu', 'ng-registry-f050'),
  ('F051', 'Admiralty University, Ibusa, Delta State', 'ng-registry-f051'),
  ('F052', 'Federal University of Transportation, Daura, Katsina', 'ng-registry-f052'),
  ('F053', 'African Aviation and Aerospace University', 'ng-registry-f053'),
  ('F054', 'National University of Science and Technology, Abuja', 'ng-registry-f054'),
  ('F055', 'Federal University of Agriculture, Bassam-Biri, Bayelsa', 'ng-registry-f055'),
  ('F056', 'Federal University of Health Sciences, Kwale, Delta State', 'ng-registry-f056'),
  ('F057', 'Federal University of Health Sciences, Katsina', 'ng-registry-f057'),
  ('F058', 'Federal University of Agriculture, Mubi', 'ng-registry-f058'),
  ('F059', 'Federal University of Education, Zaria, Kaduna State', 'ng-registry-f059'),
  ('F060', 'Alvan Ikoku Federal University of Education, Owerri, Imo State', 'ng-registry-f060'),
  ('F061', 'Yusuf Maitama Sule Federal University of Education, Kano', 'ng-registry-f061'),
  ('F062', 'Adeyemi Federal University of Education, Ondo', 'ng-registry-f062'),
  ('F063', 'Federal University of Allied Health Sciences, Enugu', 'ng-registry-f063'),
  ('F064', 'Federal University of Medicine and Medical Sciences, Abeokuta', 'ng-registry-f064'),
  ('F065', 'Federal University of Education, Pankshin, Plateau State', 'ng-registry-f065'),
  ('F066', 'Federal University of Education, Kontagora, Niger State', 'ng-registry-f066'),
  ('F067', 'University of Maritime Studies, Oron, Akwa Ibom State', 'ng-registry-f067'),
  ('F068', 'Federal University of Environment and Technology, Tai Town, Ogoniland, Rivers State', 'ng-registry-f068'),
  ('F069', 'Federal University of Applied Sciences, Kachia, Kaduna State', 'ng-registry-f069'),
  ('F070', 'Tai Solarin Federal University of Education, Ijagun, Ijebu Ode', 'ng-registry-f070'),
  ('F071', 'Federal University of Agriculture and Developmental Studies, Iragbuji, Osun State', 'ng-registry-f071'),
  ('F072', 'Federal University of Technology and Environmental Studies, Iyin-Ekiti, Ekiti State', 'ng-registry-f072'),
  ('F073', 'Federal University of Agriculture and Technology, Okeho, Oyo State', 'ng-registry-f073'),
  ('F074', 'Federal University of Health Science and Technology, Tsafe', 'ng-registry-f074'),
  ('F075', 'Federal University of Agriculture and Technology, Obio-Akpa, Akwa Ibom State', 'ng-registry-f075'),
  ('F076', 'Federal University of Science and Technology, Epe', 'ng-registry-f076'),
  ('F077', 'Federal University of Science and Technology, Kabo, Kano', 'ng-registry-f077'),
  ('S001', 'Rivers State University', 'ng-registry-s001'),
  ('S002', 'Ambrose Alli University, Ekpoma', 'ng-registry-s002'),
  ('S003', 'Abia State University, Uturu', 'ng-registry-s003'),
  ('S004', 'Ekiti State University', 'ng-registry-s004'),
  ('S005', 'Enugu State University of Science and Technology, Enugu', 'ng-registry-s005'),
  ('S006', 'Olabisi Onabanjo University, Ago Iwoye', 'ng-registry-s006'),
  ('S007', 'Lagos State University, Ojo', 'ng-registry-s007'),
  ('S008', 'Ladoke Akintola University of Technology, Ogbomoso', 'ng-registry-s008'),
  ('S009', 'Rev. Fr. Moses Orshio Adasu (formerly Benue State University), Makurdi', 'ng-registry-s009'),
  ('S010', 'Delta State University, Abraka', 'ng-registry-s010'),
  ('S011', 'Imo State University, Owerri', 'ng-registry-s011'),
  ('S012', 'Adekunle Ajasin University, Akungba', 'ng-registry-s012'),
  ('S013', 'Prince Abubakar Audu University, Anyigba', 'ng-registry-s013'),
  ('S014', 'Chukwuemeka Odumegwu Ojukwu University, Uli', 'ng-registry-s014'),
  ('S015', 'Ebonyi State University, Abakaliki', 'ng-registry-s015'),
  ('S016', 'Aliko Dangote University of Science and Technology, Wudil', 'ng-registry-s016'),
  ('S017', 'Niger Delta University, Yenagoa', 'ng-registry-s017'),
  ('S018', 'Adamawa State University, Mubi', 'ng-registry-s018'),
  ('S019', 'Nasarawa State University, Keffi', 'ng-registry-s019'),
  ('S020', 'University of Cross River State, Calabar', 'ng-registry-s020'),
  ('S021', 'Gombe State University, Gombe', 'ng-registry-s021'),
  ('S022', 'Kaduna State University, Kaduna', 'ng-registry-s022'),
  ('S023', 'Ibrahim Badamasi Babangida University, Lapai', 'ng-registry-s023'),
  ('S024', 'Plateau State University, Bokkos', 'ng-registry-s024'),
  ('S025', 'Yobe State University, Damaturu', 'ng-registry-s025'),
  ('S026', 'Kebbi State University of Science and Technology, Aliero', 'ng-registry-s026'),
  ('S027', 'Umar Musa Yar'' Adua University, Katsina', 'ng-registry-s027'),
  ('S028', 'Osun State University, Osogbo', 'ng-registry-s028'),
  ('S029', 'Olusegun Agagu University of Science and Technology, Okitipupa, Ondo', 'ng-registry-s029'),
  ('S030', 'Taraba State University, Jalingo', 'ng-registry-s030'),
  ('S031', 'Kwara State University, Ilorin', 'ng-registry-s031'),
  ('S032', 'Sokoto State University', 'ng-registry-s032'),
  ('S033', 'Akwa Ibom State University, Ikot Akpaden', 'ng-registry-s033'),
  ('S034', 'Ignatius Ajuru University of Education, Rumuolumeni', 'ng-registry-s034'),
  ('S035', 'Bauchi State University, Gadau', 'ng-registry-s035'),
  ('S036', 'Northwest University, Kano', 'ng-registry-s036'),
  ('S037', 'First Technical University, Ibadan', 'ng-registry-s037'),
  ('S038', 'Sule Lamido University, Kafin Hausa, Jigawa', 'ng-registry-s038'),
  ('S039', 'University of Medical Sciences, Ondo City,', 'ng-registry-s039'),
  ('S040', 'Edo State University, Iyamho', 'ng-registry-s040'),
  ('S041', 'Kingsley Ozumba Mbadiwe University, Ogboko, Imo State', 'ng-registry-s041'),
  ('S042', 'University of Africa, Toru Orua, Bayelsa State', 'ng-registry-s042'),
  ('S043', 'Kashim Ibrahim (formerly Bornu State) University, Maiduguri', 'ng-registry-s043'),
  ('S044', 'Moshood Abiola University of Science and Technology, Abeokuta', 'ng-registry-s044'),
  ('S045', 'Zamfara State University', 'ng-registry-s045'),
  ('S046', 'Bayelsa Medical University', 'ng-registry-s046'),
  ('S047', 'University of Agriculture and Environmental Sciences, Umuagwo, Imo State', 'ng-registry-s047'),
  ('S048', 'Confluence University of Science and Technology, Osara, Kogi', 'ng-registry-s048'),
  ('S049', 'Bamidele Olumilua University of Science and Technology, Ikere, Ekiti State', 'ng-registry-s049'),
  ('S050', 'University of Delta, Agbor', 'ng-registry-s050'),
  ('S051', 'Delta University of Science and Technology, Ozoro', 'ng-registry-s051'),
  ('S052', 'Dennis Osadebe University, Asaba', 'ng-registry-s052'),
  ('S053', 'Lagos State University of Education, Ijanikin', 'ng-registry-s053'),
  ('S054', 'Lagos State University of Science and Technology, Ikorodu', 'ng-registry-s054'),
  ('S055', 'Shehu Shagari University of Education, Sokoto', 'ng-registry-s055'),
  ('S056', 'State University of Medical and Applied Sciences, Igbo-Eno, Enugu', 'ng-registry-s056'),
  ('S057', 'University of Ilesa, Osun State', 'ng-registry-s057'),
  ('S058', 'Emanuel Alayande University of Education, Oyo', 'ng-registry-s058'),
  ('S059', 'Kogi State University, Kabba', 'ng-registry-s059'),
  ('S060', 'AbdulKadir Kure University, Minna, Niger State', 'ng-registry-s060'),
  ('S061', 'Kwara State University of Education, Ilorin, Kwara State', 'ng-registry-s061'),
  ('S062', 'Abdulsalam Abubakar University of Agriculture and Climate Action, Mokwa, Niger State', 'ng-registry-s062'),
  ('S063', 'Ebonyi State University of ICT, Science and Technology, Oferekpe, Ebonyi State', 'ng-registry-s063'),
  ('S064', 'Cross River University of Education and Entrepeneurship, Akampa, Cross River State', 'ng-registry-s064'),
  ('S065', 'Benue State University of Agriculture, Science and Technology, Ihugh', 'ng-registry-s065'),
  ('S066', 'University of Aeronautics and Aerospace Engineering, Ezza, Ebonyi State', 'ng-registry-s066'),
  ('S067', 'University of Innovation, Science and Technology, Omuma, Imo State', 'ng-registry-s067'),
  ('S068', 'Taraba State University of Tropical Agriculture, Science, Technology and Climate Action, Gembu', 'ng-registry-s068'),
  ('S069', 'Jigawa State University of Medical and Allied Health Sciences, Majia', 'ng-registry-s069'),
  ('P001', 'Babcock University, Ilishan-Remo', 'ng-registry-p001'),
  ('P002', 'Igbinedion University, Okada', 'ng-registry-p002'),
  ('P003', 'Madonna University, Okija', 'ng-registry-p003'),
  ('P004', 'Bowen University, Iwo', 'ng-registry-p004'),
  ('P005', 'Benson Idahosa University, Benin City', 'ng-registry-p005'),
  ('P006', 'Covenant University, Ota', 'ng-registry-p006'),
  ('P007', 'Pan-Atlantic University, Lagos', 'ng-registry-p007'),
  ('P008', 'American University of Nigeria, Yola', 'ng-registry-p008'),
  ('P009', 'Ajayi Crowther University, Ibadan', 'ng-registry-p009'),
  ('P010', 'Al-Hikmah University, Ilorin', 'ng-registry-p010'),
  ('P011', 'Al-Qalam University, Katsina', 'ng-registry-p011'),
  ('P012', 'Bells University of Technology, Otta', 'ng-registry-p012'),
  ('P013', 'Bingham University, New Karu', 'ng-registry-p013'),
  ('P014', 'Caritas University, Enugu', 'ng-registry-p014'),
  ('P015', 'Crawford University, Igbesa', 'ng-registry-p015'),
  ('P016', 'Crescent University', 'ng-registry-p016'),
  ('P017', 'Kwararafa University, Wukari', 'ng-registry-p017'),
  ('P018', 'Lead City University, Ibadan', 'ng-registry-p018'),
  ('P019', 'Novena University, Ogume', 'ng-registry-p019'),
  ('P020', 'Redeemer''s University, Ede', 'ng-registry-p020'),
  ('P021', 'Renaissance University, Enugu', 'ng-registry-p021'),
  ('P022', 'University of Mkar, Mkar', 'ng-registry-p022'),
  ('P023', 'Joseph Ayo Babalola University, Ikeji-Arakeji', 'ng-registry-p023'),
  ('P024', 'Achievers University, Owo', 'ng-registry-p024'),
  ('P025', 'Caleb University, Lagos', 'ng-registry-p025'),
  ('P026', 'Fountain University, Oshogbo', 'ng-registry-p026'),
  ('P027', 'African University of Science and Technology, Abuja', 'ng-registry-p027'),
  ('P028', 'Obong University, Obong Ntak', 'ng-registry-p028'),
  ('P029', 'Salem University, Lokoja', 'ng-registry-p029'),
  ('P030', 'Tansian University, Umunya', 'ng-registry-p030'),
  ('P031', 'Veritas University, Abuja', 'ng-registry-p031'),
  ('P032', 'Wesley University, Ondo', 'ng-registry-p032'),
  ('P033', 'Western Delta University, Oghara, Delta State', 'ng-registry-p033'),
  ('P034', 'Afe Babalola University, Ado-Ekiti, Ekiti State', 'ng-registry-p034'),
  ('P035', 'Godfrey Okoye University, Ugwuomu-Nike, Enugu State', 'ng-registry-p035'),
  ('P036', 'Nile University of Nigeria, Abuja', 'ng-registry-p036'),
  ('P037', 'Oduduwa University, Ipetumodu, Osun State', 'ng-registry-p037'),
  ('P038', 'Paul University, Awka, Anambra State', 'ng-registry-p038'),
  ('P039', 'Rhema University, Obeama-Asa, Rivers State', 'ng-registry-p039'),
  ('P040', 'Wellspring University, Evbuobanosa, Edo State', 'ng-registry-p040'),
  ('P041', 'Adeleke University, Ede', 'ng-registry-p041'),
  ('P042', 'Baze University', 'ng-registry-p042'),
  ('P043', 'Landmark University, Omu-Aran', 'ng-registry-p043'),
  ('P044', 'Glorious Vision University, Ogwa, Edo State', 'ng-registry-p044'),
  ('P045', 'Elizade University, Ilara-Mokin', 'ng-registry-p045'),
  ('P046', 'Evangel University, Akaeze', 'ng-registry-p046'),
  ('P047', 'Gregory University, Uturu', 'ng-registry-p047'),
  ('P048', 'Mcpherson University, Seriki Sotayo, Ajebo', 'ng-registry-p048'),
  ('P049', 'Southwestern University, Oku Owa', 'ng-registry-p049'),
  ('P050', 'Augustine University', 'ng-registry-p050'),
  ('P051', 'Chrisland University', 'ng-registry-p051'),
  ('P052', 'Edwin Clark University, Kaigbodo', 'ng-registry-p052'),
  ('P053', 'Hallmark University, Ijebi Itele, Ogun', 'ng-registry-p053'),
  ('P054', 'Hezekiah University, Umudi', 'ng-registry-p054'),
  ('P055', 'Kings University, Ode Omu', 'ng-registry-p055'),
  ('P056', 'Micheal and Cecilia Ibru University', 'ng-registry-p056'),
  ('P057', 'Mountain Top University', 'ng-registry-p057'),
  ('P058', 'Ritman University, Ikot Ekpene, Akwa Ibom', 'ng-registry-p058'),
  ('P059', 'Summit University, Offa', 'ng-registry-p059'),
  ('P060', 'Christopher University, Mowe', 'ng-registry-p060'),
  ('P061', 'Kola Daisi University, Ibadan, Oyo State', 'ng-registry-p061'),
  ('P062', 'Anchor University, Ayobo, Lagos State', 'ng-registry-p062'),
  ('P063', 'Dominican University, Ibadan, Oyo State', 'ng-registry-p063'),
  ('P064', 'Legacy University, Okija, Anambra State', 'ng-registry-p064'),
  ('P065', 'Arthur Javis University, Akpoyubo, Cross River State', 'ng-registry-p065'),
  ('P066', 'Ojaja University, Eiyenkorin, Kwara State', 'ng-registry-p066'),
  ('P067', 'Coal City University, Enugu State', 'ng-registry-p067'),
  ('P068', 'Clifford University, Owerrinta, Abia State', 'ng-registry-p068'),
  ('P069', 'Spiritan University, Nneochi, Abia State', 'ng-registry-p069'),
  ('P070', 'Precious Cornerstone University, Oyo', 'ng-registry-p070'),
  ('P071', 'PAMO University of Medical Sciences, Port Harcourt', 'ng-registry-p071'),
  ('P072', 'Atiba University, Oyo', 'ng-registry-p072'),
  ('P073', 'Eko University of Medical and Health Sciences, Ijanikin, Lagos', 'ng-registry-p073'),
  ('P074', 'Skyline University, Kano', 'ng-registry-p074'),
  ('P075', 'Greenfield University, Kaduna', 'ng-registry-p075'),
  ('P076', 'Dominion University, Ibadan, Oyo State', 'ng-registry-p076'),
  ('P077', 'Trinity University, Ogun State', 'ng-registry-p077'),
  ('P078', 'Westland University, Iwo, Osun State', 'ng-registry-p078'),
  ('P079', 'Topfaith University, Mkpatak, Akwa Ibom State', 'ng-registry-p079'),
  ('P080', 'Thomas Adewumi University, Oko-Irese, Kwara State', 'ng-registry-p080'),
  ('P081', 'Maranatha University, Lagos', 'ng-registry-p081'),
  ('P082', 'Ave Maria University, Piyanko, Nasarawa State', 'ng-registry-p082'),
  ('P083', 'Al-Istiqama University, Sumaila, Kano State', 'ng-registry-p083'),
  ('P084', 'Mudiame University, Irrua, Edo State', 'ng-registry-p084'),
  ('P085', 'Havilla University, Nde-Ikom, Cross River State', 'ng-registry-p085'),
  ('P086', 'Claretian University of Nigeria, Nekede, Imo State', 'ng-registry-p086'),
  ('P087', 'Karl-Kumm University, Vom, Plateau State', 'ng-registry-p087'),
  ('P088', 'James Hope University, Lagos, Lagos State', 'ng-registry-p088'),
  ('P089', 'Maryam Abacha American University of Nigeria, Kano State', 'ng-registry-p089'),
  ('P090', 'Capital City University, Kano State', 'ng-registry-p090'),
  ('P091', 'Ahman Pategi University, Kwara State', 'ng-registry-p091'),
  ('P092', 'University of Offa, Kwara State', 'ng-registry-p092'),
  ('P093', 'Mewar International University, Masaka, Nasarawa State', 'ng-registry-p093'),
  ('P094', 'Edusoko University, Bida, Niger State', 'ng-registry-p094'),
  ('P095', 'Philomath University, Kuje, Abuja', 'ng-registry-p095'),
  ('P096', 'Anan University, Kwall, Plateau State', 'ng-registry-p096'),
  ('P097', 'North Eastern University, Gombe', 'ng-registry-p097'),
  ('P098', 'Al-Ansar University, Maiduguri, Borno', 'ng-registry-p098'),
  ('P099', 'Margaret Lawrence University, Umunede, Delta State', 'ng-registry-p099'),
  ('P100', 'Khalifa Isiyaku Rabiu University, Kano', 'ng-registry-p100'),
  ('P101', 'Sports University, Idumuje, Ugboko, Delta State', 'ng-registry-p101'),
  ('P102', 'Baba Ahmed University, Kano State', 'ng-registry-p102'),
  ('P103', 'Saisa University of Medical Sciences and Technology, Sokoto State', 'ng-registry-p103'),
  ('P104', 'Nigerian British University, Asa, Abia State', 'ng-registry-p104'),
  ('P105', 'Peter University, Achina-Onneh, Anambra State', 'ng-registry-p105'),
  ('P106', 'Newgate University, Minna, Niger State', 'ng-registry-p106'),
  ('P107', 'European University of Nigeria, Duboyi, FCT', 'ng-registry-p107'),
  ('P108', 'NorthWest University, Sokoto State', 'ng-registry-p108'),
  ('P109', 'Rayhaan University, Kebbi', 'ng-registry-p109'),
  ('P110', 'Muhammad Kamalud University, Kwara', 'ng-registry-p110'),
  ('P111', 'Sam Maris University, Ondo', 'ng-registry-p111'),
  ('P112', 'Aletheia University, Ago-Iwoye, Ogun State', 'ng-registry-p112'),
  ('P113', 'Lux Mundi University, Umuahia, Abia State', 'ng-registry-p113'),
  ('P114', 'Maduka University, Ekwegbe, Enugu State', 'ng-registry-p114'),
  ('P115', 'PeaceLand University, Enugu State', 'ng-registry-p115'),
  ('P116', 'Amadeus University, Amizi, Abia State', 'ng-registry-p116'),
  ('P117', 'Vision University, Ikogbo, Ogun State', 'ng-registry-p117'),
  ('P118', 'Azman University, Kano State', 'ng-registry-p118'),
  ('P119', 'Huda University, Gusau, Zamfara State', 'ng-registry-p119'),
  ('P120', 'Franco British International University, Kaduna State', 'ng-registry-p120'),
  ('P121', 'Canadian University of Nigeria, Abuja', 'ng-registry-p121'),
  ('P122', 'Gerar University of Medical Science, Imope Ijebu, Ogun State', 'ng-registry-p122'),
  ('P123', 'British Canadian University, Obufu, Cross River State', 'ng-registry-p123'),
  ('P124', 'Hensard University, Toru-Orua, Sagbama, Bayelsa State', 'ng-registry-p124'),
  ('P125', 'Amaj University, Kwali, Abuja', 'ng-registry-p125'),
  ('P126', 'Phoenix University, Agwada, Nasarawa State', 'ng-registry-p126'),
  ('P127', 'Wigwe University, Isiokpo, Rivers State', 'ng-registry-p127'),
  ('P128', 'Hillside University of Science and Technology, Okemisi, Ekiti State', 'ng-registry-p128'),
  ('P129', 'University on the Niger, Umunya, Anambra State', 'ng-registry-p129'),
  ('P130', 'Elrazi Medical University Yargaya University, Kano State', 'ng-registry-p130'),
  ('P131', 'Venite University, Iloro-Ekiti, Ekiti State', 'ng-registry-p131'),
  ('P132', 'Shanahan University, Onitsha, Anambra State', 'ng-registry-p132'),
  ('P133', 'The Duke Medical University, Calabar, Cross River State', 'ng-registry-p133'),
  ('P134', 'Mercy Medical University, Iwo, Ogun State', 'ng-registry-p134'),
  ('P135', 'Cosmopolitan University, Abuja', 'ng-registry-p135'),
  ('P136', 'Miva Open University, Abuja FCT', 'ng-registry-p136'),
  ('P137', 'Iconic Open University, Sokoto State', 'ng-registry-p137'),
  ('P138', 'West Midlands Open University, Ibadan, Oyo State', 'ng-registry-p138'),
  ('P139', 'Al-Muhibbah Open University, Abuja', 'ng-registry-p139'),
  ('P140', 'El-Amin University, Minna, Niger State', 'ng-registry-p140'),
  ('P141', 'College of Petroleum and Energy Studies, Kaduna State', 'ng-registry-p141'),
  ('P142', 'Jewel University, Gombe State', 'ng-registry-p142'),
  ('P143', 'Prime University, Kuje, FCT Abuja', 'ng-registry-p143'),
  ('P144', 'Nigerian University of Technology and Management, Apapa, Lagos State', 'ng-registry-p144'),
  ('P145', 'Al-Bayan University, Ankpa, Kogi State', 'ng-registry-p145'),
  ('P146', 'Lighthouse University, Evbobanosa, Edo State', 'ng-registry-p146'),
  ('P147', 'African University of Economics, FCT Abuja', 'ng-registry-p147'),
  ('P148', 'New City University, Ayetoro, Ogun State', 'ng-registry-p148'),
  ('P149', 'University of Fortune, Igbotako, Ondo State', 'ng-registry-p149'),
  ('P150', 'Eranova University, Abuja', 'ng-registry-p150'),
  ('P151', 'Minaret University, Ikirun, Osun State', 'ng-registry-p151'),
  ('P152', 'Abdulrasaq Abubakar Toyin University, Oke-Ogba, Ganmo, Ilorin, Kwara State', 'ng-registry-p152'),
  ('P153', 'Southern Atlantic University, Uyo, Akwa Ibom State', 'ng-registry-p153'),
  ('P154', 'Lens University, Ilemona, Kwara State', 'ng-registry-p154'),
  ('P155', 'Monarch University, Iyesi-Ota, Ogun State', 'ng-registry-p155'),
  ('P156', 'Tonine Iredia University of Communication, Benin City, Edo State', 'ng-registry-p156'),
  ('P157', 'Isaac Balami University of Aeronautics and Management, Lagos State', 'ng-registry-p157'),
  ('P158', 'Kevin Eze University, Mgbowo, Enugu State', 'ng-registry-p158'),
  ('P159', 'Tazkiyah University, Kaduna, Kaduna State', 'ng-registry-p159'),
  ('P160', 'Leadership University, Abuja FCT', 'ng-registry-p160'),
  ('P161', 'Jimoh Babalola University, Ilorin, Kwara State', 'ng-registry-p161'),
  ('P162', 'Bridget University, Mbaise, Okirika-Nweke, Imo State', 'ng-registry-p162'),
  ('P163', 'Greenland University, Jalingo, Taraba State', 'ng-registry-p163'),
  ('P164', 'JEFAP University, Suleja, Niger State', 'ng-registry-p164'),
  ('P165', 'Azione Verde University, Amaigbo, Imo State', 'ng-registry-p165'),
  ('P166', 'Unique Open University, Ojo, Lagos State', 'ng-registry-p166'),
  ('P167', 'American Open University, Abeokuta, Ogun State', 'ng-registry-p167'),
  ('P168', 'Millenium Crest University, Ikare Akoko, Ondo State', 'ng-registry-p168'),
  ('P169', 'Abdulfattah Durojaiye University, Abeokuta, Ogun State', 'ng-registry-p169'),
  ('P170', 'Euston University, Abakaliki, Ebonyi State', 'ng-registry-p170'),
  ('P171', 'Adeche Momoh University, Igarra, Edo State', 'ng-registry-p171'),
  ('P172', 'Sani Bello University, Kontagora, Niger State', 'ng-registry-p172'),
  ('P173', 'Godday Erewa University, Sapele, Delta State', 'ng-registry-p173'),
  ('P174', 'Owolabi University, Oke Ila Orangun', 'ng-registry-p174'),
  ('P175', 'Regnum Medical University, Anthony, Lagos State', 'ng-registry-p175'),
  ('P176', 'City University, Abuja', 'ng-registry-p176'),
  ('P177', 'Transatlantic University of Medine and Health Sciences, Umuchukwu, Anambra State', 'ng-registry-p177'),
  ('P178', 'Maria Assumpta University, Owerri, Imo State', 'ng-registry-p178'),
  ('P179', 'High Flyers University, Ikere-Ekiti, Ekiti State', 'ng-registry-p179'),
  ('P180', 'Ummah University of Nigeria, Abuja', 'ng-registry-p180'),
  ('P181', 'Pearl University, Calabar, Cross River', 'ng-registry-p181'),
  ('P182', 'Omega University, Kaduna', 'ng-registry-p182')
),
upserted as (
  insert into public.universities (
    id,
    name,
    slug,
    country,
    state,
    website_url,
    created_at,
    updated_at,
    deleted_at
  )
  select
    gen_random_uuid(),
    registry.name,
    registry.slug,
    'Nigeria',
    null,
    null,
    now(),
    now(),
    null
  from registry
  on conflict (name) do update
    set deleted_at = null,
        updated_at = now()
  returning id, name
)
insert into public.institution_config (institution_id, status, timezone)
select universities.id, 'PREPARING', 'Africa/Lagos'
from public.universities universities
join registry on registry.name = universities.name
on conflict (institution_id) do nothing;

commit;
