import { describe, expect, it, vi } from "vitest";
import { assertAIConfiguration, generateAI, completeAI, aiMessages, selectAIProvider, studentSafeText, type AIEnvironment, type AIMode } from "../src/lib/ai-provider";
const env:AIEnvironment={AI_ASSISTANT_ENABLED:"true",HF_TOKEN:"hf_SYNTHETIC",HF_CHAT_MODEL:"test/text:nscale",HF_VISION_MODEL:"test/vision:novita",HF_PRO_MODEL:"test/pro"};
const success=()=>Response.json({choices:[{finish_reason:"stop",message:{content:"A useful answer"}}]});
describe("Hugging Face-only adapter",()=>{
  it.each(["study","summary","notes","quiz","timetable"] as AIMode[])("always routes %s through HF",mode=>{for(const mime of [undefined,"application/pdf","image/png"])expect(selectAIProvider(mode,mime)).toBe("huggingface");});
  it.each(["image/jpeg","image/png","image/webp"])("uses vision model and image_url for %s",async mimeType=>{const fetcher=vi.fn<typeof fetch>().mockResolvedValue(success());await generateAI(env,{mode:"study",prompt:"Explain this",media:{mimeType,data:"SYNTHETIC"}},fetcher);const call=JSON.parse(String(fetcher.mock.calls[0]?.[1]?.body));expect(call.model).toBe("test/vision:novita");expect(call.messages.at(-1).content[1]).toEqual({type:"image_url",image_url:{url:`data:${mimeType};base64,SYNTHETIC`}});expect(fetcher).toHaveBeenCalledTimes(1);});
  it("requires PDF text extraction before provider I/O",async()=>{const fetcher=vi.fn<typeof fetch>();await expect(generateAI(env,{mode:"summary",prompt:"Read",media:{mimeType:"application/pdf",data:"PDF"}},fetcher)).rejects.toMatchObject({reason:"AI_UNSUPPORTED_MEDIA"});expect(fetcher).not.toHaveBeenCalled();});
  it("bounds context and output, and sets a timeout",async()=>{const fetcher=vi.fn<typeof fetch>().mockResolvedValue(success());const history=Array.from({length:10},(_,i)=>({prompt:`q${i}`,text:`a${i}`}));await generateAI(env,{mode:"study",prompt:"New",history},fetcher);const init=fetcher.mock.calls[0]?.[1];const body=JSON.parse(String(init?.body));expect(body.max_tokens).toBe(2048);expect(body.stream).toBe(false);expect(body.messages).toHaveLength(14);expect(body.messages[1].content).toBe("q4");expect(init?.signal).toBeDefined();});
  it.each([401,402,403,429,500])("redacts provider %i errors without a fallback",async status=>{const fetcher=vi.fn<typeof fetch>().mockResolvedValue(new Response("PRIVATE_INPUT hf_SECRET",{status}));const error=await generateAI(env,{mode:"study",prompt:"Question"},fetcher).catch(e=>e);expect(error.status).toBe(503);expect(String(error)).not.toContain("PRIVATE_INPUT");expect(fetcher).toHaveBeenCalledTimes(1);expect(fetcher.mock.calls[0]?.[0]).toBe("https://router.huggingface.co/v1/chat/completions");});
  it("does not return truncated output as success",async()=>{const fetcher=vi.fn<typeof fetch>().mockResolvedValue(Response.json({choices:[{finish_reason:"length",message:{content:"Incomplete"}}]}));await expect(generateAI(env,{mode:"study",prompt:"Q"},fetcher)).rejects.toMatchObject({reason:"AI_INCOMPLETE"});});
  it("keeps missing configuration generic and enforces the kill switch",()=>{expect(()=>assertAIConfiguration({...env,HF_TOKEN:""},"study")).toThrow("temporarily unavailable");expect(()=>assertAIConfiguration({...env,AI_ASSISTANT_ENABLED:"false"},"study")).toThrow("paused");});
  it("allows bounded structured calls but rejects excessive calls",async()=>{const input={mode:"study" as const,prompt:"My timetable"};const calls=[{id:"call1",type:"function",function:{name:"get_my_timetable",arguments:"{}"}}];const fetcher=vi.fn<typeof fetch>().mockResolvedValue(Response.json({choices:[{finish_reason:"tool_calls",message:{content:null,tool_calls:calls}}]}));expect((await completeAI(env,input,aiMessages(input),undefined,fetcher)).calls).toEqual(calls);fetcher.mockResolvedValue(Response.json({choices:[{message:{tool_calls:Array(4).fill(calls[0])}}]}));await expect(completeAI(env,input,aiMessages(input),undefined,fetcher)).rejects.toMatchObject({reason:"AI_TOO_MANY_ACTIONS"});});
  it("removes privileged links and token patterns from display text",()=>{expect(studentSafeText("Visit https://admin.example.com/panel and hf_12345678901234567")).toBe("Visit [restricted link] and [redacted]");});
});
