import {readFileSync} from 'node:fs';
import {afterAll,afterEach,beforeAll,describe,expect,it,vi} from 'vitest';
import {Hono,type Context,type Next} from 'hono';
import type {PGlite} from '@electric-sql/pglite';
import {createTestDatabase,testDatabaseAdapter,testSqlClient} from './helpers/database';
import {aiRoutes} from '../src/routes/ai';
import {financePolicyRoutes} from '../src/routes/finance-policies';
import {resolveKiraPlanPrice} from '../src/lib/kira-billing';
import {activePaidAITier} from '../src/lib/ai-quota';
import {studentAIPolicy} from '../src/lib/student-ai-policy';
import {AppError} from '../src/lib/errors';
import type {Bindings,AuthenticatedUser} from '../src/types';
let pg:PGlite;
vi.mock('../src/lib/database',()=>({database:()=>testDatabaseAdapter(pg),sqlClient:()=>testSqlClient(pg),firstRow:(r:{rows:unknown[]})=>r.rows[0]}));
vi.mock('../src/middleware/auth',()=>({currentUser:(c:Context)=>({id:c.req.header('x-user'),universityId:c.req.header('x-campus'),email:'synthetic@example.invalid',roles:['STUDENT']}),requireAuth:async(c:Context,n:Next)=>c.req.header('x-user')?n():c.json({error:'Unauthorized'},401)}));
const campus=crypto.randomUUID(),other=crypto.randomUUID(),admin=crypto.randomUUID();
const env={ENVIRONMENT:'local',PHASE_3_SCHEMA_READY:'true',UNIFIED_SCHEMA_READY:'true',KIRA_SUBSCRIPTIONS_ENABLED:'true',PAYMENTS_ENABLED:'true',AI_ASSISTANT_ENABLED:'true',HF_TOKEN:'synthetic',HF_CHAT_MODEL:'synthetic/standard',HF_PRO_MODEL:'synthetic/pro',PAYSTACK_SECRET_KEY:'sk_live_synthetic'} as Bindings;
const fees={basisPoints:150,flatKobo:10000,flatWaivedBelowKobo:250000,capKobo:200000};
const app=new Hono().route('/ai',aiRoutes).route('/finance',financePolicyRoutes);
app.onError((e,c)=>c.json({error:e.message,details:e instanceof AppError?e.details:undefined},e instanceof AppError?e.status:500));
const req=(path:string,user:string,body?:unknown,uni=campus)=>app.request(path,{method:body?'POST':'GET',headers:{'x-user':user,'x-campus':uni,'content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})},env);
async function person(uni=campus){const id=crypto.randomUUID();await pg.query("insert into users(id,email,password_hash,updated_at)values($1,$1::uuid::text||'@example.invalid','synthetic',now())",[id]);await pg.query("insert into profiles(id,user_id,university_id,username,display_name,updated_at)values($1,$1,$2,'fixture_'||substring(replace($1::uuid::text,'-',''),1,20),'Synthetic',now())",[id,uni]);return id;}
async function approve(tier='pro',extra:Record<string,unknown>={}) {const r=await req('/finance/kira-plans',admin,{universityId:campus,tier,version:'SYNTHETIC_'+crypto.randomUUID(),amountKobo:tier==='standard'?0:600000,discountPercent:0,collection:fees,sourceUrl:'https://paystack.com/pricing',approvalNote:'Synthetic isolated pricing approval only.',...extra});expect(r.status).toBe(201);return await r.json() as {id:string;price:{amountKobo:number}};}
async function quote(user:string,tier='pro',code=''){const r=await req('/ai/subscription-quote',user,{tier,discountCode:code});expect(r.status).toBe(200);return (await r.json() as {quote:{quoteId:string;amountKobo:number;expiresAt:string;discountAmountKobo:number;tier:string;paystackAmountKobo:number}}).quote;}
async function sqlQuote(user:string,tier='pro',code=''){return (await pg.query<any>('select * from app_private.quote_kira_subscription($1,$2,$3,$4,$5,$6)',[crypto.randomUUID(),user,campus,crypto.randomUUID(),tier,code])).rows[0];}
const authUser=(id:string)=>({id,universityId:campus,email:'synthetic@example.invalid',roles:['STUDENT']} as AuthenticatedUser);
beforeAll(async()=>{
  pg=await createTestDatabase();
  for(const f of ['20260912200000_phase_3_commerce_foundation.sql','20260930220000_store_fulfilment_modes.sql','20260930240000_rider_commission_ledger.sql','20260930250000_inclusive_store_quotes.sql','20260930260000_inclusive_tutorial_bookings.sql','20260930270000_verified_kira_subscription.sql','20260930280000_verified_learning_materials.sql','20260930290000_verified_agent_payouts.sql','20261001020000_admin_workspace_extensions.sql','20261001182000_discount_codes_and_newsletter_access.sql','20261003120000_configurable_kira_pricing.sql'])await pg.exec(readFileSync(new URL('../../database/neon/migrations/'+f,import.meta.url),'utf8'));
  for(const id of [campus,other])await pg.query("insert into universities(id,name,slug,updated_at)values($1,'Synthetic '||$1::uuid::text,$1::uuid::text,now())",[id]);
  await pg.query("insert into users(id,email,password_hash,updated_at)values($1,'catalogue-admin@example.invalid','synthetic',now())",[admin]);
  await pg.query("insert into profiles(id,user_id,university_id,username,display_name,updated_at)values($1,$1,$2,'catalogue_admin','Synthetic',now())",[admin,campus]);
  await pg.query("insert into operator_roles(user_id,university_id,role)values($1,$2,'FINANCE_REVIEWER')",[admin,campus]);
  await pg.query("insert into app_private.kira_price_plans(id,university_id,version,amount_kobo,listed_amount_kobo,discount_percent,collection,estimated_processing_kobo,approved_by,approval_note,source_url)values($1,$2,'LEGACY_PRO',600000,600000,0,$3,19000,$4,'Synthetic historical approval','https://paystack.com/pricing')",[crypto.randomUUID(),campus,JSON.stringify(fees),admin]);
  await pg.query("insert into app_private.active_kira_price_plans(university_id,plan_id)select university_id,id from app_private.kira_price_plans where version='LEGACY_PRO'");
  await pg.exec(readFileSync(new URL('../../database/neon/migrations/20261003122000_kira_plan_catalogue.sql',import.meta.url),'utf8'));
  await pg.exec(readFileSync(new URL('../../database/neon/migrations/20261003123000_payment_pricing_profiles.sql',import.meta.url),'utf8'));
},60000);
afterAll(async()=>{await pg?.close();});afterEach(()=>vi.unstubAllGlobals());
describe('server-owned Kira catalog and accepted quote protections',()=>{
  it('saves a monthly price and immediate percentage offer without manual version or evidence fields',async()=>{
    const response=await req('/finance/kira-plans',admin,{universityId:campus,tier:'pro',amountKobo:600000,discountPercent:25,offerActive:true,collection:fees});
    expect(response.status).toBe(201);const saved=await response.json() as {id:string;price:{amountKobo:number;discountPercent:number}};
    expect(saved.price).toMatchObject({amountKobo:450000,discountPercent:25});
    const rows=(await pg.query<any>('select version,approved_by,approval_note,source_url from app_private.kira_price_plans where id=$1',[saved.id])).rows;
    expect(rows[0]).toMatchObject({approved_by:admin,source_url:'https://paystack.com/pricing'});expect(rows[0].version).toMatch(/^KIRA_/);
    const u=await person(),q=await quote(u);expect(q.amountKobo).toBe(450000);
    await approve();
  });
  it('runs the self-cleaning PostgreSQL acceptance fixture and restores the current catalog',async()=>{await pg.exec(readFileSync(new URL('../../database/verification/kira_catalogue_acceptance.sql',import.meta.url),'utf8'));});
  it('migrates the old paid plan to Pro and seeds an independent free Standard record',async()=>{const u=await person();const s=(await (await req('/ai/subscription',u)).json() as any).subscription;expect(s.catalog.standard).toMatchObject({amountKobo:0,tier:'standard',checkoutEnabled:false});expect(s.catalog.pro).toMatchObject({amountKobo:600000,tier:'pro'});expect(s.catalog.standard.planId).not.toBe(s.catalog.pro.planId);expect((await req('/ai/subscription-quote',u,{tier:'standard'})).status).toBe(409);});
  it('resolves exact active percentage only inside its schedule and never fabricates expired savings',()=>{const offer={offerActive:true,discountPercent:20,offerStartsAt:'2026-10-03T12:00:00Z',offerEndsAt:'2026-10-04T12:00:00Z'};for(const at of ['2026-10-03T11:59:59Z','2026-10-04T12:00:00Z'])expect(resolveKiraPlanPrice(500000,offer,fees,new Date(at))).toMatchObject({amountKobo:500000,discountAmountKobo:0,discountPercent:0,offerActive:false});expect(resolveKiraPlanPrice(500000,offer,fees,new Date(offer.offerStartsAt))).toMatchObject({amountKobo:400000,discountAmountKobo:100000,discountPercent:20,offerActive:true});expect(resolveKiraPlanPrice(500000,{...offer,offerActive:false},fees,new Date(offer.offerStartsAt)).amountKobo).toBe(500000);});
  it('keeps an expired or future admin offer out of today’s catalogue and preview',async()=>{await approve('pro',{amountKobo:500000,discountPercent:20,offerStartsAt:'2020-01-01T00:00:00Z',offerEndsAt:'2020-01-02T00:00:00Z'});const u=await person(),s=(await (await req('/ai/subscription',u)).json() as any).subscription;expect(s.catalog.pro).toMatchObject({amountKobo:500000,discountPercent:0,discountAmountKobo:0});const p=await req('/finance/kira-plans/preview',admin,{universityId:campus,version:'PREVIEW',amountKobo:500000,discountPercent:20,offerActive:true,offerStartsAt:'2090-01-01T00:00:00Z',offerEndsAt:'2090-01-02T00:00:00Z',collection:fees,sourceUrl:'https://paystack.com/pricing',approvalNote:'Synthetic server preview.'});expect(p.status).toBe(200);expect((await p.json() as any).price).toMatchObject({amountKobo:500000,discountPercent:0,offerActive:false});});
  it('accepts a persisted coupon total before opening Paystack and initializes exactly once',async()=>{await approve();const u=await person();await pg.query("insert into app_private.discount_codes(institution_id,code,scope,percent,ends_at,max_uses,created_by)values($1,'CATALOG20','KIRA',20,now()+interval '1 day',100,$2)",[campus,admin]);const q=await quote(u,'pro','CATALOG20');expect(q).toMatchObject({amountKobo:480000,paystackAmountKobo:480000,discountAmountKobo:120000});let reference='';const fetcher=vi.fn(async(_url:string,init:RequestInit)=>{const body=JSON.parse(String(init.body));expect(body.amount).toBe(q.amountKobo);expect(body.bearer).toBe('account');reference=body.reference;return Response.json({status:true,data:{authorization_url:'https://checkout.paystack.com/fixture',access_code:'fixture',reference}});});vi.stubGlobal('fetch',fetcher);const body={quoteId:q.quoteId,tier:'pro',expectedAmountKobo:q.amountKobo,requestId:crypto.randomUUID(),consent:true};expect((await req('/ai/subscription-checkout',u,body)).status).toBe(200);expect((await req('/ai/subscription-checkout',u,body)).status).toBe(200);expect(fetcher).toHaveBeenCalledTimes(1);expect((await pg.query<any>('select amount_kobo,quote_id from app_private.kira_checkouts where provider_reference=$1',[reference])).rows[0]).toMatchObject({amount_kobo:480000,quote_id:q.quoteId});});
  it('rejects arbitrary totals, campus theft, changed plan and quote idempotency substitution before any payment call',async()=>{await approve();const u=await person(),v=await person(other),q=await quote(u);const fetcher=vi.fn();vi.stubGlobal('fetch',fetcher);const body={quoteId:q.quoteId,tier:'pro',expectedAmountKobo:q.amountKobo+1,requestId:crypto.randomUUID(),consent:true};expect((await req('/ai/subscription-checkout',u,body)).status).toBe(409);expect((await req('/ai/subscription-checkout',v,{...body,expectedAmountKobo:q.amountKobo},other)).status).toBe(409);await approve('pro',{amountKobo:700000});expect((await req('/ai/subscription-checkout',u,{...body,expectedAmountKobo:q.amountKobo})).status).toBe(409);expect(fetcher).not.toHaveBeenCalled();});
  it('caps a coupon quote at a future automatic-offer boundary and rejects stacking during an active offer',async()=>{const starts=new Date(Date.now()+300000).toISOString();await approve('pro',{discountPercent:10,offerStartsAt:starts,offerEndsAt:new Date(Date.now()+600000).toISOString()});const u=await person();const q=await sqlQuote(u,'pro','CATALOG20');expect(q.offer_discount_percent).toBe(0);expect(q.coupon_discount_percent).toBe(20);expect(Date.parse(q.expires_at)).toBeLessThanOrEqual(Date.parse(starts));await approve('pro',{discountPercent:10});await expect(sqlQuote(await person(),'pro','CATALOG20')).rejects.toThrow(/DISCOUNT_CANNOT_COMBINE/);});
  it('reserves coupon use at quote time and holds its exact expiration',async()=>{await approve();const code='END'+crypto.randomUUID().replaceAll('-','').slice(0,8).toUpperCase();const ending=new Date(Date.now()+300000).toISOString();await pg.query("insert into app_private.discount_codes(institution_id,code,scope,percent,ends_at,max_uses,created_by)values($1,$2,'KIRA',10,$3,1,$4)",[campus,code,ending,admin]);const u=await person(),q=await sqlQuote(u,'pro',code);expect(Math.floor(Date.parse(q.expires_at)/1000)).toBe(Math.floor(Date.parse(ending)/1000));await expect(sqlQuote(await person(),'pro',code)).rejects.toThrow(/DISCOUNT_EXHAUSTED/);await pg.query('update app_private.discount_codes set active=false where code=$1',[code]);await expect(pg.query('select * from app_private.create_quoted_kira_checkout($1,$2,$3,$4,$5,$6,$7)',[u,campus,crypto.randomUUID(),'SYNTHETIC_'+crypto.randomUUID(),q.id,'pro',q.amount_kobo])).rejects.toThrow(/KIRA_PRICE_CHANGED/);});
  it('rejects expired immutable quotes and protects quote, checkout, and plan snapshots',async()=>{await approve();const u=await person(),q=await sqlQuote(u);await expect(pg.query('update app_private.kira_subscription_quotes set amount_kobo=1 where id=$1',[q.id])).rejects.toThrow(/append-only/);const expired=crypto.randomUUID();await pg.query("insert into app_private.kira_subscription_quotes(id,user_id,university_id,request_id,plan_id,tier,plan_version,listed_amount_kobo,amount_kobo,offer_discount_percent,coupon_discount_percent,estimated_processing_kobo,collection,created_at,expires_at)select $1,user_id,university_id,$2,plan_id,tier,plan_version,listed_amount_kobo,amount_kobo,offer_discount_percent,coupon_discount_percent,estimated_processing_kobo,collection,now()-interval '2 hours',now()-interval '1 hour' from app_private.kira_subscription_quotes where id=$3",[expired,crypto.randomUUID(),q.id]);await expect(pg.query('select * from app_private.create_quoted_kira_checkout($1,$2,$3,$4,$5,$6,$7)',[u,campus,crypto.randomUUID(),'SYNTHETIC_'+crypto.randomUUID(),expired,'pro',q.amount_kobo])).rejects.toThrow(/KIRA_QUOTE_EXPIRED/);await pg.query('select * from app_private.create_quoted_kira_checkout($1,$2,$3,$4,$5,$6,$7)',[u,campus,crypto.randomUUID(),'SYNTHETIC_'+crypto.randomUUID(),q.id,'pro',q.amount_kobo]);await expect(pg.query("update app_private.kira_checkouts set tier='standard' where quote_id=$1",[q.id])).rejects.toThrow(/SNAPSHOT_IMMUTABLE/);await expect(pg.query('update app_private.kira_price_plans set available=false where id=$1',[q.plan_id])).rejects.toThrow(/append-only/);});
  it('grants paid Standard only Standard entitlement after one verified receipt and leaves free academic tools accessible',async()=>{await approve('standard',{amountKobo:200000});const u=await person(),q=await sqlQuote(u,'standard'),reference='SYNTHETIC_STANDARD_'+crypto.randomUUID();await pg.query('select * from app_private.create_quoted_kira_checkout($1,$2,$3,$4,$5,$6,$7)',[u,campus,crypto.randomUUID(),reference,q.id,'standard',q.amount_kobo]);expect(await activePaidAITier(env,authUser(u))).toBeNull();expect((await pg.query<any>('select app_private.record_kira_receipt($1,$2,3000,now()) as result',[reference,q.amount_kobo])).rows[0].result).toBe('PAID');expect((await pg.query<any>('select app_private.record_kira_receipt($1,$2,3000,now()) as result',[reference,q.amount_kobo])).rows[0].result).toBe('ALREADY_PAID');expect(await activePaidAITier(env,authUser(u))).toBe('standard');expect(await studentAIPolicy(env,authUser(u))).toMatchObject({pro:false,paidTier:'standard'});const status=(await (await req('/ai/status',u)).json() as any);expect(status.tier).toBe('standard');expect((await (await req('/ai/subscription',u)).json() as any).subscription.currentTier).toBe('standard');expect((await pg.query<any>('select tier from app_private.kira_billing_periods where user_id=$1',[u])).rows).toEqual([{tier:'standard'}]);});
  it('does not grant a future Pro renewal during the current Standard period or restore a cancelled entitlement',async()=>{
    await approve('standard',{amountKobo:200000});await approve('pro',{amountKobo:600000});
    const u=await person();
    for(const tier of ['standard','pro']){
      const q=await sqlQuote(u,tier),reference='SYNTHETIC_TIER_'+crypto.randomUUID();
      await pg.query('select * from app_private.create_quoted_kira_checkout($1,$2,$3,$4,$5,$6,$7)',[u,campus,crypto.randomUUID(),reference,q.id,tier,q.amount_kobo]);
      await pg.query('select app_private.record_kira_receipt($1,$2,3000,now())',[reference,q.amount_kobo]);
      if(tier==='standard')await pg.query("update app_private.ai_subscriptions set current_period_end=now()+interval '3 days' where user_id=$1",[u]);
    }
    expect((await pg.query<any>('select tier from app_private.ai_subscriptions where user_id=$1',[u])).rows[0].tier).toBe('pro');
    expect(await activePaidAITier(env,authUser(u))).toBe('standard');
    expect(await studentAIPolicy(env,authUser(u))).toMatchObject({pro:false,paidTier:'standard'});
    await pg.query("update app_private.ai_subscriptions set status='CANCELLED' where user_id=$1",[u]);
    expect(await activePaidAITier(env,authUser(u))).toBeNull();
  });
  it('keeps complimentary owner access and isolates availability changes to the configured tier',async()=>{const u=await person();const {sha256}=await import('../src/lib/security');const complimentary={...env,AI_UNLIMITED_EMAIL_HASHES:await sha256('synthetic@example.invalid')};expect(await studentAIPolicy(complimentary,authUser(u))).toMatchObject({pro:true,complimentary:true});await approve('standard',{amountKobo:200000,active:false});await approve('pro',{amountKobo:600000,available:false});const s=(await (await req('/ai/subscription',u)).json() as any).subscription;expect(s.catalog.standard).toMatchObject({active:false,checkoutEnabled:false});expect(s.catalog.pro).toMatchObject({available:false,checkoutEnabled:false});expect((await req('/ai/subscription-quote',u,{tier:'standard'})).status).toBe(409);expect((await req('/finance/kira-plans',u,{universityId:campus,version:'UNAUTHORIZED',amountKobo:600000,collection:fees,sourceUrl:'https://paystack.com/pricing',approvalNote:'No privilege assigned.'})).status).toBe(403);});
});
