import {beforeAll,afterAll,beforeEach,afterEach,it,expect,vi} from 'vitest';
import {Hono,type Context,type Next} from 'hono';
import {requestId} from 'hono/request-id';
import type {PGlite} from '@electric-sql/pglite';
import {createTestDatabase,testDatabaseAdapter} from './helpers/database';
import {trustedVendorRoutes} from '../src/routes/trusted-vendors';
import {usageRoutes} from '../src/routes/usage';
import {requireFullKyc} from '../src/lib/kyc';
import {AppError} from '../src/lib/errors';
import type {Bindings} from '../src/types';
let db:PGlite;
const uni=crypto.randomUUID(),otherUni=crypto.randomUUID(),staff=crypto.randomUUID(),vendor=crypto.randomUUID(),outsider=crypto.randomUUID(),scopedStaff=crypto.randomUUID();
vi.mock('../src/lib/database',()=>({database:()=>testDatabaseAdapter(db),firstRow:(r:{rows:unknown[]})=>r.rows[0]}));
vi.mock('../src/middleware/auth',()=>({currentUser:(c:Context)=>({id:c.req.header('x-user'),universityId:c.req.header('x-uni')??uni,email:'fixture@example.test',roles:['STUDENT'],operatorRoles:[]}),requireAuth:(c:Context,next:Next)=>c.req.header('x-user')?next():c.json({error:'Unauthenticated'},401)}));
const app=new Hono().use('*',requestId()).route('/trusted',trustedVendorRoutes).route('/usage',usageRoutes);app.onError((e,c)=>c.json({error:e.message},e instanceof AppError?e.status:500));
const env={} as Bindings;
async function request(path:string,user=staff,method='GET',body?:unknown,campus=uni){await db.exec('savepoint api_request');const response=await app.request('http://localhost'+path,{method,headers:{'x-user':user,'x-uni':campus,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})},env);if(response.status>=400)await db.exec('rollback to savepoint api_request');await db.exec('release savepoint api_request');return response;}
beforeAll(async()=>{db=await createTestDatabase();for(const id of [uni,otherUni])await db.query("insert into universities(id,name,slug,updated_at)values($1,'Fixture university '||$1::uuid::text,$1::uuid::text,now())",[id]);for(const id of [staff,vendor,outsider,scopedStaff])await db.query("insert into users(id,email,password_hash,email_verified_at,updated_at)values($1,$1::uuid::text||'@example.test','fixture',now(),now())",[id]);await db.query("insert into operator_roles(user_id,role,university_id)values($1,'PLATFORM_ADMIN',null),($2,'VERIFICATION_REVIEWER',$3)",[staff,scopedStaff,otherUni]);});
afterAll(async()=>{await db?.close();});beforeEach(async()=>{await db.exec('begin;');});afterEach(async()=>{await db.exec('rollback;');});
async function invitation(){const response=await request('/trusted/admin/invites',staff,'POST',{universityId:uni,email:vendor+'@example.test',reason:'Previously approached and verified business contact.'});expect(response.status).toBe(201);const result=await response.json() as {id:string,url:string};return {id:result.id,token:new URL(result.url).searchParams.get('invite')!};}
const data=()=>({requestId:crypto.randomUUID(),businessName:'Fixture shop',legalName:'Fixture business owner',birthDate:'2000-01-15',description:'A test business description for this isolated fixture.',address:'A test business address',category:'Groceries',campus:'Fixture campus',phone:'+2348012345678',adultAuthorized:true,terms:true});
async function document(owner=vendor){const mediaId=crypto.randomUUID();await db.query("insert into media_objects(id,owner_user_id,institution_id,kind,object_key,content_type,size_bytes,original_name)values($1,$2,$3,'kyc',$4,'application/pdf',10,'verification.pdf')",[mediaId,owner,uni,'test/'+mediaId]);return mediaId;}
it('binds an invitation to its verified email and prevents another account from claiming it',async()=>{const invite=await invitation();expect((await request('/trusted/invite',outsider,'POST',{token:invite.token})).status).toBe(403);expect((await request('/trusted/submit',outsider,'POST',{token:invite.token,...data(),documentMediaId:await document(outsider)})).status).toBe(409);expect((await db.query('select count(*)::int n from agent_applications')).rows[0]?.n).toBe(0);});
it('approves the documented business only through an audited reviewer and retains the bank requirement',async()=>{const invite=await invitation(),payload={token:invite.token,...data(),documentMediaId:await document()};const submission=await request('/trusted/submit',vendor,'POST',payload);expect(submission.status).toBe(201);const {id}=await submission.json() as {id:string};expect((await db.query('select count(*)::int n from agent_profiles where user_id=$1',[vendor])).rows[0]?.n).toBe(0);const a=(await db.query<{revision:string}>('select updated_at::text revision from agent_applications where id=$1',[id])).rows[0]!;const review={revision:a.revision,decision:'APPROVED',note:'Business, adult contact and uploaded verification document were reviewed.',verifiedBusinessAndContact:true,verifiedDocuments:true};expect((await request('/trusted/admin/'+id+'/review',scopedStaff,'POST',review,otherUni)).status).toBe(403);expect((await request('/trusted/admin/'+id+'/review',staff,'POST',review)).status).toBe(200);expect((await db.query('select count(*)::int n from agent_profiles where user_id=$1 and status=\'ACTIVE\'',[vendor])).rows[0]?.n).toBe(1);expect((await db.query('select count(*)::int n from agent_application_details where application_id=$1',[id])).rows[0]?.n).toBe(0);await expect(requireFullKyc(env,id,false)).resolves.toMatchObject({user_id:vendor});await expect(requireFullKyc(env,id,true)).rejects.toThrow('Complete bank verification');expect((await db.query("select count(*)::int n from app_private.audit_events where action='trusted_vendor.reviewed'and target_id=$1",[id])).rows[0]?.n).toBe(1);expect((await db.query("select count(*)::int n from app_private.audit_events where action='trusted_vendor.details_verified'and target_id=$1",[id])).rows[0]?.n).toBe(1);});
it('replays an unchanged submission and rejects changed content under the same request',async()=>{const invite=await invitation(),payload={token:invite.token,...data(),documentMediaId:await document()};const first=await request('/trusted/submit',vendor,'POST',payload),second=await request('/trusted/submit',vendor,'POST',payload);expect(first.status).toBe(201);expect(second.status).toBe(201);expect((await first.json() as {id:string}).id).toBe((await second.json() as {id:string}).id);expect((await request('/trusted/submit',vendor,'POST',{...payload,businessName:'Changed shop'})).status).toBe(409);});
it('rejects an expired invitation without creating an application',async()=>{const invite=await invitation();await db.query("update app_private.trusted_vendor_invites set expires_at=now()-interval '1 minute'where id=$1",[invite.id]);expect((await request('/trusted/submit',vendor,'POST',{token:invite.token,...data(),documentMediaId:await document()})).status).toBe(409);});
it('requires and stores one private Exclusive verification document',async()=>{const invite=await invitation();expect((await request('/trusted/submit',vendor,'POST',{token:invite.token,...data()})).status).toBe(400);const documentMediaId=await document();const response=await request('/trusted/submit',vendor,'POST',{token:invite.token,...data(),documentMediaId});expect(response.status).toBe(201);const {id}=await response.json() as {id:string};expect((await db.query<{document_media_id:string}>('select document_media_id from app_private.trusted_vendor_intakes where application_id=$1',[id])).rows[0]?.document_media_id).toBe(documentMediaId);});
function sample(){const ended=Date.now();return {id:crypto.randomUUID(),ownerUserId:vendor,platform:'android',screen:'map',startedAt:new Date(ended-30000).toISOString(),endedAt:new Date(ended).toISOString(),seconds:30};}
it('counts one foreground sample once and hides it from another university',async()=>{const payload=sample();expect((await request('/usage',vendor,'POST',payload)).status).toBe(201);expect((await request('/usage',vendor,'POST',payload)).status).toBe(201);const own=await request('/usage/admin/today');expect(own.status,await own.clone().text()).toBe(200);expect((await own.json() as {totals:{foreground_seconds:number,samples:number}}).totals).toMatchObject({foreground_seconds:30,samples:1});await db.query("insert into operator_roles(user_id,role,university_id)values($1,'FINANCE_REVIEWER',$2)",[scopedStaff,otherUni]);const other=await request('/usage/admin/today?universityId='+otherUni,scopedStaff,'GET',undefined,otherUni);expect(other.status).toBe(200);expect((await other.json() as {users:unknown[]}).users).toHaveLength(0);});
it('rejects another account’s usage and implausible elapsed time',async()=>{expect((await request('/usage',outsider,'POST',sample())).status).toBe(403);expect((await request('/usage',vendor,'POST',{...sample(),seconds:60})).status).toBe(400);expect((await db.query('select count(*)::int n from app_private.foreground_usage_samples')).rows[0]?.n).toBe(0);});
