import{describe,it,expect}from'vitest';
import{parseScheduleDocument}from'../src/lib/schedule-document';
import{aiMessages,aiSystemInstruction}from'../src/lib/ai-provider';
import{needsCampusTools}from'../src/lib/student-ai-tools';
// Transcribed from the user's FUE Zaria calendar: the model must preserve dates, not manufacture hours.
const rows=[
 ['TP & SIWES NCE III','2026-01-05','2026-04-17','First semester'],['Registration','2026-01-05','2026-01-16','First semester'],['Lectures','2026-01-19','2026-03-13','First semester'],['Mid-semester, Eid and Easter break','2026-03-14','2026-04-06','First semester'],['Lectures','2026-04-07','2026-05-22','First semester'],['Workers Day','2026-05-01','2026-05-01','First semester'],['Eid Kabir break','2026-05-23','2026-05-29','First semester'],['Examination','2026-06-01','2026-06-19','First semester'],['Democracy Day','2026-06-12','2026-06-12','First semester'],['End of semester break','2026-06-20','2026-07-05','First semester'],
 ['Lectures','2026-07-06','2026-08-21','Second semester'],['Mid-semester and Eid Maulud break','2026-08-22','2026-08-30','Second semester'],['Lectures','2026-08-31','2026-10-23','Second semester'],['Independence Day','2026-10-01','2026-10-01','Second semester'],['Examination','2026-10-26','2026-11-13','Second semester'],['Proposed next session','2027-01-04','2027-01-04','2026/2027'],
].map(([title,startsOn,endsOn,semester])=>({title,startsOn,endsOn,semester}));
describe('schedule classification and academic conversation',()=>{
 it('preserves both semesters and date ranges without producing classes',()=>{const result=parseScheduleDocument(JSON.stringify({documentType:'academic_calendar',entries:[{title:'First Semester',dayOfWeek:1,startsAt:'05:00',endsAt:'17:00'}],events:rows,warnings:[]}));expect(result.entries).toEqual([]);expect(result.events).toEqual(rows);expect(result.events.filter(e=>e.semester==='Second semester')).toHaveLength(5);});
 it('rejects calendar headings as classes even from an older response format',()=>{expect(parseScheduleDocument(JSON.stringify({entries:[{title:'First Semester',startsAt:'05:00',endsAt:'17:00'}]})).entries).toEqual([]);expect(parseScheduleDocument(JSON.stringify({entries:[{title:'Lectures',startsAt:'05:00',endsAt:'17:00'}]}),'APPROVED ACADEMIC CALENDAR').entries).toEqual([]);});
 it('does not normalize impossible or reversed dates into real events',()=>{const r=parseScheduleDocument(JSON.stringify({documentType:'academic_calendar',entries:[],events:[{title:'Exam',startsOn:'2026-02-30',endsOn:'2026-03-04'},{title:'Break',startsOn:'2026-05-10',endsOn:'2026-05-01'}]}));expect(r.events).toEqual([]);expect(r.warnings.join(' ')).toContain('row 2');});
 it('retains an ordinary class and never fills absent times',()=>{const row={title:'Fluid Mechanics',dayOfWeek:2,startsAt:'10:00',endsAt:'12:00'};expect(parseScheduleDocument(JSON.stringify({entries:[row]})).entries).toEqual([row]);});
 it('keeps short follow-ups in the student/assistant conversation',()=>{const messages=aiMessages({mode:'study',prompt:"Why can't you explain it?",history:[{prompt:'Explain fluid mechanics',text:'Earlier answer'}]});expect(messages.slice(1)).toEqual([{role:'user',content:'Explain fluid mechanics'},{role:'assistant',content:'Earlier answer'},{role:'user',content:"Why can't you explain it?"}]);expect(aiSystemInstruction('study')).toContain('complex topics are not a reason to refuse');});
 it('does not offer campus-shopping tools for a general academic explanation',()=>{expect(needsCampusTools({mode:'study',prompt:'What is fluid mechanics?'})).toBe(false);expect(needsCampusTools({mode:'study',prompt:'Why?',history:[{prompt:'Explain fluid mechanics',text:'Introduction'}]})).toBe(false);expect(needsCampusTools({mode:'study',prompt:'What are my classes today?'})).toBe(true);});
});
