import {beforeAll,afterAll,describe,it,expect,vi} from 'vitest';
import {readFileSync} from 'node:fs';
import {Hono,type Context,type Next} from 'hono';
import type {PGlite} from '@electric-sql/pglite';
import {studentGroupRoutes} from '../src/routes/student-groups';
import {communityRoutes} from '../src/routes/communities';
import {calendarRoutes} from '../src/routes/calendar';
import {learningRoutes} from '../src/routes/learning';
import {studentRoutes} from '../src/routes/student';
import {AppError} from '../src/lib/errors';
import {createTestDatabase,testDatabaseAdapter,testSqlClient} from './helpers/database';
let db:PGlite;const owner=crypto.randomUUID(),member=crypto.randomUUID(),nonmember=crypto.randomUUID(),foreign=crypto.randomUUID(),campus=crypto.randomUUID(),otherCampus=crypto.randomUUID();
vi.mock('../src/lib/database',()=>({database:()=>testDatabaseAdapter(db),sqlClient:()=>testSqlClient(db),firstRow:(r:{rows:unknown[]})=>r.rows[0]}));
vi.mock('../src/middleware/auth',()=>({requireAuth:async(_c:Context,n:Next)=>n(),currentUser:(c:Context)=>({id:c.req.header('x-user'),universityId:c.req.header('x-user')===foreign?otherCampus:campus,roles:['STUDENT']})}));
vi.mock('../src/services/community-push',()=>({deliverCommunityPush:async()=>({})}));
const app=new Hono().route('/communities',communityRoutes).route('/groups',studentGroupRoutes).route('/calendar',calendarRoutes).route('/learning',learningRoutes).route('/student',studentRoutes);
app.onError((e,c)=>c.json({error:e.message},e instanceof AppError?e.status:500));
const req=(path:string,method='GET',body?:unknown,user=owner)=>app.request(path,{method,headers:{'x-user':user,'content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});
beforeAll(async()=>{db=await createTestDatabase();for(const [i,uni] of [campus,otherCampus].entries())await db.query("insert into public.universities(id,name,slug,updated_at) values($1,$2,$3,now())",[uni,'Group campus '+i,'group-campus-'+i]);for(const [i,user] of [owner,member,nonmember,foreign].entries()){await db.query("insert into public.users(id,email,password_hash,updated_at) values($1,$2,'test-only',now())",[user,'groups'+i+'@example.invalid']);await db.query("insert into public.profiles(id,user_id,university_id,username,display_name,updated_at) values(gen_random_uuid(),$1,$2,$3,$4,now())",[user,user===foreign?otherCampus:campus,'groupuser'+i,'Group person '+i]);}},60000);
afterAll(async()=>db?.close());
describe('student communities and private study groups',()=>{
 it('creates creator admin idempotently, enforces membership/tenant and permits study members to post',async()=>{
  const requestId=crypto.randomUUID(),draft={requestId,kind:'STUDY_GROUP',name:'CPE 250 study circle',description:'Computer education',keywords:['CPE250','2025 set']};
  const created=await req('/groups','POST',draft);expect(created.status).toBe(201);const group=(await created.json()).group;
  expect((await (await req('/groups','POST',draft)).json()).group.id).toBe(group.id);
  expect((await req('/groups','POST',{...draft,name:'Changed name'})).status).toBe(409);
  expect((await req('/groups/'+group.id+'/posts')).status).toBe(200);
  expect((await req('/groups/'+group.id+'/notifications','PATCH',{enabled:true})).status).toBe(200);
  expect((await req('/groups/'+group.id+'/posts','GET',undefined,nonmember)).status).toBe(403);
  expect((await req('/groups/'+group.id,'GET',undefined,foreign)).status).toBe(404);
  expect((await req('/groups/'+group.id+'/join','POST',{},member)).status).toBe(200);
  const postDraft={requestId:crypto.randomUUID(),title:'Osmosis revision',body:'Let us revise cell membranes.',pollOptions:['Today','Tomorrow']};
  const posted=await req('/groups/'+group.id+'/posts','POST',postDraft,member);expect(posted.status).toBe(201);const post=(await posted.json()).post;
  expect((await req('/groups/'+group.id+'/posts','POST',{...postDraft,urgent:true},member)).status).toBe(403);
  expect((await req('/groups/'+group.id+'/posts','POST',{...postDraft,body:'Changed'},member)).status).toBe(409);
  expect((await req('/groups/'+group.id+'/posts/'+post.id+'/vote','POST',{optionIndex:0},owner)).status).toBe(200);
  expect((await req('/groups/'+group.id+'/posts/'+post.id+'/vote','POST',{optionIndex:3},owner)).status).toBe(404);
  const commented=await req('/groups/'+group.id+'/posts/'+post.id+'/comments','POST',{body:'I can join.'});expect(commented.status).toBe(201);const comment=(await commented.json()).comment;
  expect((await req('/groups/'+group.id+'/posts/'+post.id+'/comments/'+comment.id,'DELETE',{},member)).status).toBe(404);
  expect((await req('/groups/'+group.id+'/posts/'+post.id+'/comments/'+comment.id,'DELETE')).status).toBe(200);
  expect((await db.query("select id from app_private.notification_outbox where dedupe_key like 'community-post:%'")).rows).toHaveLength(0);
  expect((await db.query("select id from public.in_app_notifications where dedupe_key like 'community-post:%'")).rows).toHaveLength(1);
  const startKey=crypto.randomUUID();const started=await req('/groups/'+group.id+'/study/start','POST',{requestId:startKey},member);expect(started.status).toBe(201);const session=(await started.json()).active;
  expect((await (await req('/groups/'+group.id+'/study/start','POST',{requestId:startKey},member)).json()).active.id).toBe(session.id);
  await db.query("update public.student_group_study_sessions set started_at=now()-interval '35 minutes' where id=$1",[session.id]);
  expect((await req('/groups/'+group.id+'/study/stop','POST',{sessionId:session.id},owner)).status).toBe(404);
  expect((await req('/groups/'+group.id+'/study/stop','POST',{sessionId:session.id},member)).status).toBe(200);
  const insightResponse=await req('/groups/'+group.id+'/study', 'GET',undefined,member);const insights=await insightResponse.json();expect(insights,JSON.stringify(insights)).toHaveProperty('active',null);expect(insights.members.find((m:any)=>m.user_id===member).today_seconds).toBeGreaterThanOrEqual(2100);
  expect((await req('/groups/'+group.id+'/study','GET',undefined,nonmember)).status).toBe(403);
  expect((await req('/groups/'+group.id+'/join','DELETE',{},member)).status).toBe(200);
  expect((await req('/groups/'+group.id+'/posts','GET',undefined,member)).status).toBe(403);
 });
 it('allows members to post by default, lets admins restrict posting and respects notification opt-in',async()=>{
  const created=await req('/groups','POST',{requestId:crypto.randomUUID(),kind:'COMMUNITY',name:'Faculty notices'});const group=(await created.json()).group;
  const requested=await req('/groups/'+group.id+'/join','POST',{fullName:'Group member',matriculationNumber:'SCI22001',department:'Computer Science',level:'200',nickname:'Member',guidelinesVersion:1,guidelinesAccepted:true},member);expect(requested.status).toBe(202);
  expect((await req('/groups/'+group.id+'/posts','POST',{requestId:crypto.randomUUID(),title:'Before approval',body:'Cannot publish yet'},member)).status).toBe(403);
  expect((await req('/groups/'+group.id+'/requests','GET',undefined,member)).status).toBe(403);
  const reviewed=await req('/groups/'+group.id+'/requests/review','POST',{all:true,decision:'APPROVED'});expect(reviewed.status,await reviewed.clone().text()).toBe(200);
  expect((await req('/groups/'+group.id+'/posts','POST',{requestId:crypto.randomUUID(),title:'Hello',body:'A member post'},member)).status).toBe(201);
  const before=await(await req('/groups/'+group.id,'GET',undefined,member)).json();expect(before.group.notifications_enabled).toBe(true);expect(before.canPost).toBe(true);
  expect((await req('/groups/'+group.id,'PATCH',{name:'Faculty notices',description:'Member feed',membersCanPost:false},member)).status).toBe(403);
  expect((await req('/groups/'+group.id,'PATCH',{name:'Faculty notices',description:'Admin feed',membersCanPost:false})).status).toBe(200);
  expect((await req('/groups/'+group.id+'/posts','POST',{requestId:crypto.randomUUID(),title:'Hello',body:'Member after restriction'},member)).status).toBe(403);
  expect((await(await req('/groups/'+group.id,'GET',undefined,member)).json()).canPost).toBe(false);
  expect((await req('/groups/'+group.id+'/notifications','PATCH',{enabled:true},member)).status).toBe(200);
  const draft={requestId:crypto.randomUUID(),title:'Venue changed',body:'Meet at LT 2.',urgent:true,venue:'LT 2'};
  const posted=await req('/groups/'+group.id+'/posts','POST',draft);expect(posted.status).toBe(201);const post=(await posted.json()).post;
  await req('/groups/'+group.id+'/posts','POST',draft);
  expect((await db.query("select id from app_private.notification_outbox where dedupe_key like $1",['community-urgent:'+post.id+':%'])).rows).toHaveLength(1);
  expect((await req('/groups/'+group.id+'/members','POST',{username:'groupuser3'})).status).toBe(409);
  const feed=await(await req('/groups/'+group.id+'/posts','GET',undefined,member)).json();expect(feed.posts.find((p:any)=>p.id===post.id).author_role).toBe('ADMIN');
  expect((await req('/groups/'+group.id+'/notifications','PATCH',{enabled:false},member)).status).toBe(200);
  const muted=await req('/groups/'+group.id+'/posts','POST',{requestId:crypto.randomUUID(),title:'Silent update',body:'Muted member receives no alert.'});expect(muted.status).toBe(201);const mutedId=(await muted.json()).post.id;
  expect((await db.query('select id from public.in_app_notifications where dedupe_key like $1',['community-post:'+mutedId+':%'])).rows).toHaveLength(0);
  expect((await db.query('select id from app_private.notification_outbox where dedupe_key like $1',['community-post:'+mutedId+':%'])).rows).toHaveLength(0);
  expect((await req('/groups/'+group.id+'/notifications','PATCH',{enabled:true},nonmember)).status).toBe(403);
  const ownImage=crypto.randomUUID(),stolenImage=crypto.randomUUID();for(const[id,actor]of[[ownImage,owner],[stolenImage,member]])await db.query("insert into public.media_objects(id,owner_user_id,institution_id,kind,object_key,content_type,size_bytes,original_name) values($1,$2,$3,'post',$4,'image/jpeg',12,'Test photo')",[id,actor,campus,'test/'+id]);
  expect((await req('/groups/'+group.id,'PATCH',{name:'Updated faculty',description:'New description',membersCanPost:true,avatarMediaId:stolenImage})).status).toBe(400);
  expect((await req('/groups/'+group.id,'PATCH',{name:'Updated faculty',description:'New description',membersCanPost:true,avatarMediaId:ownImage})).status).toBe(200);
  const updated=await(await req('/groups/'+group.id,'GET',undefined,member)).json();expect(updated.group).toMatchObject({name:'Updated faculty',description:'New description',members_can_post:true});expect(updated.group.avatar_url).toContain('/v1/media/'+ownImage);expect(updated.canPost).toBe(true);
  const searchResponse=await req('/communities?q=Updated');expect(searchResponse.status).toBe(200);const search=await searchResponse.json();expect(search.rows.find((row:any)=>row.id===group.id)).toMatchObject({name:'Updated faculty',description:'New description',members:2});expect(search.rows.find((row:any)=>row.id===group.id).avatar_url).toContain('/v1/media/'+ownImage);
  expect((await(await req('/communities?q=Updated','GET',undefined,foreign)).json()).rows).toEqual([]);
  const members=await(await req('/groups/'+group.id+'/members','GET',undefined,nonmember)).json();expect(members.members).toHaveLength(2);expect(members.members[0].role).toBe('ADMIN');
  expect((await req('/groups/'+group.id,'PATCH',{name:'Updated faculty',description:'',membersCanPost:true},foreign)).status).toBe(404);
 });

 it('supports feed-style community images, likes, replies and admin deletion',async()=>{
  const created=await req('/groups','POST',{requestId:crypto.randomUUID(),kind:'COMMUNITY',name:'Community media test'});const group=(await created.json()).group;
  await req('/groups/'+group.id+'/join','POST',{fullName:'Group member',matriculationNumber:'CPE22001',department:'Computer Education',level:'200',nickname:'Member',guidelinesVersion:1,guidelinesAccepted:true},member);
  expect((await req('/groups/'+group.id+'/requests/review','POST',{all:true,decision:'APPROVED'})).status).toBe(200);
  const ownerImage=crypto.randomUUID(),memberImage=crypto.randomUUID();
  for(const[id,actor]of[[ownerImage,owner],[memberImage,member]])await db.query("insert into public.media_objects(id,owner_user_id,institution_id,kind,object_key,content_type,size_bytes,original_name) values($1,$2,$3,'post',$4,'image/jpeg',12,'Community image')",[id,actor,campus,'community/'+id]);
  const posted=await req('/groups/'+group.id+'/posts','POST',{requestId:crypto.randomUUID(),title:'',body:'',mediaId:memberImage},member);expect(posted.status,await posted.clone().text()).toBe(201);const post=(await posted.json()).post;
  let feed=await(await req('/groups/'+group.id+'/posts','GET',undefined,owner)).json();let row=feed.posts.find((item:any)=>item.id===post.id);
  expect(row).toMatchObject({title:'Photo',body:'',author_user_id:member,like_count:0,liked_by_me:false});expect(row.media_url).toContain('/v1/media/'+memberImage);
  expect((await req('/groups/'+group.id+'/posts/'+post.id+'/like','PUT',{},owner)).status).toBe(200);
  feed=await(await req('/groups/'+group.id+'/posts','GET',undefined,owner)).json();row=feed.posts.find((item:any)=>item.id===post.id);expect(row).toMatchObject({like_count:1,liked_by_me:true});
  expect((await req('/groups/'+group.id+'/posts/'+post.id+'/like','DELETE',{},owner)).status).toBe(200);
  const reply=await req('/groups/'+group.id+'/posts/'+post.id+'/comments','POST',{body:'',mediaId:ownerImage},owner);expect(reply.status).toBe(201);const replyId=(await reply.json()).comment.id;
  const comments=await(await req('/groups/'+group.id+'/posts/'+post.id+'/comments','GET',undefined,member)).json();expect(comments.comments.find((item:any)=>item.id===replyId).media_url).toContain('/v1/media/'+ownerImage);
  const memberReply=await req('/groups/'+group.id+'/posts/'+post.id+'/comments','POST',{body:'Member reply'},member);const memberReplyId=(await memberReply.json()).comment.id;
  expect((await req('/groups/'+group.id+'/posts/'+post.id+'/comments/'+memberReplyId,'DELETE',{},owner)).status).toBe(200);
  expect((await req('/groups/'+group.id+'/posts/'+post.id,'DELETE',{},owner)).status).toBe(200);
  expect((await req('/groups/'+group.id+'/posts/'+post.id,'DELETE',{},owner)).status).toBe(404);
 });
 it('keeps class alarms fifteen minutes early including midnight and scopes batch removal',async()=>{
  const draft={title:'Midnight lab',courseCode:'CPE100',dayOfWeek:1,startsAt:'00:10',endsAt:'01:10',reminderMinutes:0,reminderEnabled:true};
  const created=await req('/student/timetable','POST',draft);expect(created.status).toBe(201);const entry=(await created.json()).id;
  const ownAlarms=await(await req('/learning/alarms')).json();const alarm=ownAlarms.alarms.find((a:any)=>a.timetable_entry_id===entry);expect(alarm.time).toBe('23:55');expect(alarm.days).toEqual([0]);
  expect((await(await req('/learning/alarms/bulk-delete','POST',{ids:[alarm.id]},member)).json()).deleted).toBe(0);
  expect((await(await req('/learning/alarms/bulk-delete','POST',{ids:[alarm.id]})).json()).deleted).toBe(1);
  expect((await db.query('select reminder_enabled from public.timetable_entries where id=$1',[entry])).rows[0].reminder_enabled).toBe(false);
  expect((await(await req('/student/timetable/bulk-delete','POST',{ids:[entry]},member)).json()).deleted).toBe(0);
  expect((await(await req('/student/timetable/bulk-delete','POST',{ids:[entry]})).json()).deleted).toBe(1);
  expect((await db.query('select id from public.student_alarms where timetable_entry_id=$1',[entry])).rows).toHaveLength(0);
 });
 it('clears selected GPA history and draft grades only for their owner',async()=>{
  const mine=crypto.randomUUID(),theirs=crypto.randomUUID();
  for(const [term,user] of [[mine,owner],[theirs,member]]){await db.query("insert into public.gpa_terms(id,university_id,user_id,session_label,semester,level_code,gpa,earned_units,quality_points,updated_at) values($1,$2,$3,'2026/2027',1,'200',4,3,12,now())",[term,campus,user]);await db.query("insert into public.gpa_results(term_id,course_code,course_title,units,grade,grade_point) values($1,'CPE201','Computing',3,'B',4)",[term]);}
  expect((await(await req('/student/gpa/bulk-delete','POST',{ids:[mine]},member)).json()).deleted).toBe(0);
  expect((await(await req('/student/gpa/bulk-delete','POST',{ids:[mine,theirs],clearDrafts:true})).json()).deleted).toBe(1);
  expect((await db.query('select term_id from public.gpa_results')).rows).toEqual([{term_id:theirs}]);
  expect((await db.query('select course_code from public.course_drafts where user_id=$1',[owner])).rows).toHaveLength(0);
  expect((await req('/student/gpa/bulk-delete','POST',{ids:[]})).status).toBe(400);
  expect((await req('/student/gpa/bulk-delete','POST',{ids:[],clearDrafts:true})).status).toBe(200);
 });
 it('removes only selected owned calendar dates and keeps exam windows distinct',async()=>{
  const imported=await req('/calendar/import','POST',{requestId:crypto.randomUUID(),events:[{title:'Faculty examinations',startsOn:'2027-02-01',endsOn:'2027-02-05',semester:'First semester'},{title:'General examinations',startsOn:'2027-02-08',endsOn:'2027-02-20',semester:'First semester'},{title:'CED examinations',startsOn:'2027-02-25',endsOn:'2027-02-26',semester:'First semester'},{title:'Second semester examinations',startsOn:'2027-06-14',endsOn:'2027-07-06',semester:'Second semester'}]});expect(imported.status).toBe(201);
  const details=await (await req('/calendar')).json();expect(details.examPeriods.map((p:any)=>[p.startsOn,p.endsOn])).toEqual([['2027-02-01','2027-02-26'],['2027-06-14','2027-07-06']]);
  expect((await (await req('/calendar/bulk-delete','POST',{ids:[details.events[0].id]},member)).json()).deleted).toBe(0);
  expect((await (await req('/calendar/bulk-delete','POST',{ids:details.events.map((e:any)=>e.id)})).json()).deleted).toBe(4);
 });
});

 describe('community migration preserves existing memberships and post roles',()=>{
  it('backfills existing notifications and admin badges while new followers remain opted out',async()=>{
   const legacy=await createTestDatabase({excludeMigrations:['20261004101000_community_profiles_and_posting.sql']});
   try{
    await legacy.query("insert into public.universities(id,name,slug,updated_at) values($1,'Legacy campus','legacy-campus',now())",[campus]);
    for(const[i,actor]of[owner,member,nonmember].entries())await legacy.query("insert into public.users(id,email,password_hash,updated_at) values($1,$2,'test-only',now())",[actor,'legacy'+i+'@example.invalid']);
    const group=crypto.randomUUID(),post=crypto.randomUUID();
    await legacy.query("insert into public.student_groups(id,institution_id,owner_user_id,kind,name,request_id) values($1,$2,$3,'COMMUNITY','Existing community',gen_random_uuid())",[group,campus,owner]);
    for(const[actor,role]of[[owner,'ADMIN'],[member,'MEMBER']])await legacy.query('insert into public.student_group_members(group_id,institution_id,user_id,role) values($1,$2,$3,$4)',[group,campus,actor,role]);
    await legacy.query("insert into public.student_group_posts(id,group_id,institution_id,author_user_id,request_id,title,body) values($1,$2,$3,$4,gen_random_uuid(),'Existing admin update','Keep this existing post')",[post,group,campus,owner]);
    await legacy.exec(readFileSync(new URL('../../database/neon/migrations/20261004101000_community_profiles_and_posting.sql',import.meta.url),'utf8'));
    expect((await legacy.query('select user_id,notifications_enabled from public.student_group_members where group_id=$1 order by role',[group])).rows).toHaveLength(2);
    expect((await legacy.query('select notifications_enabled from public.student_group_members where group_id=$1',[group])).rows.every((row:any)=>row.notifications_enabled===true)).toBe(true);
    expect((await legacy.query('select author_role,body from public.student_group_posts where id=$1',[post])).rows[0]).toEqual({author_role:'ADMIN',body:'Keep this existing post'});
    expect((await legacy.query('select members_can_post,avatar_media_id from public.student_groups where id=$1',[group])).rows[0]).toEqual({members_can_post:true,avatar_media_id:null});
    await legacy.query('insert into public.student_group_members(group_id,institution_id,user_id) values($1,$2,$3)',[group,campus,nonmember]);
    expect((await legacy.query('select notifications_enabled from public.student_group_members where group_id=$1 and user_id=$2',[group,nonmember])).rows[0]).toEqual({notifications_enabled:false});
   }finally{await legacy.close();}
  },60000);
 });
